"use client";
import Link from "next/link";import {useMemo,useState} from "react";import {LessonProgressApi} from "@/components/course/lesson-shell";import {LessonSection,TaskStamp} from "@/components/course/lesson-primitives";import {AttentionMatrix} from "@/components/interactive/attention-matrix";import {h1,h2,tokens} from "@/components/lessons/transformer-block-flow/transformer-math";import {blockOrder,defs,exam,Family,familyCases,PositionChoice} from "./module-4-capstone-data";import styles from "./module-4-capstone.module.css";
type Props={progress:LessonProgressApi};
const normalize=(xs:number[])=>{const s=xs.reduce((a,b)=>a+b,0)||1;return xs.map(x=>x/s)};const dist=(a:number[],b:number[])=>Math.sqrt(a.reduce((s,x,i)=>s+(x-b[i])**2,0));
export function Module4CapstoneLesson({progress}:Props){
 const [order,setOrder]=useState(["MLP / FFN","QKV projections","residual + norm","attention + softmax","weighted values / heads","residual + norm"]);const [drag,setDrag]=useState("");const [raw,setRaw]=useState([25,25,25,25]);const [maskFixed,setMaskFixed]=useState(false);const [positionAnswers,setPositionAnswers]=useState<Record<number,PositionChoice>>({});const [heads,setHeads]=useState<string[]>([]);const [cache,setCache]=useState("");const [familyAnswers,setFamilyAnswers]=useState<Record<number,Family>>({});const [quizAnswers,setQuizAnswers]=useState<Record<number,number>>({});const [feedback,setFeedback]=useState("");
 const weights=normalize(raw),manual=weights.reduce<[number,number]>((a,w,i)=>[a[0]+w*h1.v[i][0],a[1]+w*h1.v[i][1]],[0,0]),baseline=h1.out[1],move=dist(manual,baseline);const tasks=defs.filter(([,t])=>progress.completedTasks[t]).length,rooms=defs.filter(([id])=>progress.visitedSections.has(id)).length,unlocked=tasks===8&&rooms===8;const lights=defs.map(([,t])=>!!progress.completedTasks[t]);
 const drop=(target:number)=>{if(!drag)return;const from=order.indexOf(drag),n=[...order];n.splice(from,1);n.splice(target,0,drag);setOrder(n);setDrag("");if(n.join("|")===blockOrder.join("|"))progress.completeTask("m4-assemble-block")};
 const setWeight=(i:number,v:number)=>{const n=[...raw];n[i]=v;setRaw(n);const w=normalize(n),out=w.reduce<[number,number]>((a,x,j)=>[a[0]+x*h1.v[j][0],a[1]+x*h1.v[j][1]],[0,0]);if(w[3]>.5&&dist(out,baseline)>.08)progress.completeTask("m4-edit-attention")};
 const choosePos=(i:number,a:PositionChoice)=>{const expected:PositionChoice[]=["learned","sinusoidal","rope"],n={...positionAnswers,[i]:a};setPositionAnswers(n);if(expected.every((x,j)=>n[j]===x))progress.completeTask("m4-position-choice")};const seeHead=(x:string)=>{const n=heads.includes(x)?heads:[...heads,x];setHeads(n);if(n.length===2)progress.completeTask("m4-head-comparison")};const chooseFamily=(i:number,a:Family)=>{const n={...familyAnswers,[i]:a};setFamilyAnswers(n);if(familyCases.every((c,j)=>n[j]===c.answer))progress.completeTask("m4-family-choice")};
 const ship=()=>{if(defs.slice(0,7).every(([,t])=>progress.completedTasks[t])){progress.completeTask("m4-ship-block");setFeedback("Transformer block shipped. Mastery exam opens after every room has been inspected.")}else setFeedback("Ship blocked: clear the first seven transformer missions.")};const submit=()=>{const s=exam.reduce((n,q,i)=>n+(quizAnswers[i]===q.c?1:0),0),p=s>=10;progress.saveQuiz(s,p);setFeedback(p?`MODULE 4 MASTERED · ${s}/12`:`${s}/12. Need 10/12.`)};
 return <main className={styles.root}>
 <section className={styles.hero}><div><span className={styles.eyebrow}>MODULE 4 · BOSS LAB</span><h1>Control the attention graph.</h1><p>Assemble the block, edit attention weights, stop future leakage, choose position and cache strategies, distinguish heads and route the correct transformer family.</p></div><div className={styles.console}><b>TRANSFORMER MISSION BOARD</b><div className={styles.lights}>{lights.map((on,i)=><i key={i} className={on?styles.on:""}/>)}</div><strong>{tasks}/8 missions</strong><p>{rooms}/8 rooms inspected</p></div></section>
 <LessonSection id="assemble-block" onVisit={progress.markVisited} className={styles.scene}><TaskStamp done={!!progress.completedTasks["m4-assemble-block"]}>MISSION 01 · ASSEMBLE BLOCK</TaskStamp><h2>Drag the operations into a valid block flow.</h2><div className={styles.flow}>{order.map((x,i)=><div key={`${x}-${i}`} className={styles.drop} onDragOver={e=>e.preventDefault()} onDrop={()=>drop(i)}><span className={styles.flowItem} draggable onDragStart={()=>setDrag(x)}>{x}</span></div>)}</div><p>Target: QKV → attention/softmax → weighted heads → residual/norm → MLP → residual/norm.</p></LessonSection>
 <LessonSection id="edit-attention" onVisit={progress.markVisited} className={styles.scene}><TaskStamp done={!!progress.completedTasks["m4-edit-attention"]}>MISSION 02 · EDIT ATTENTION</TaskStamp><h2>Move “robot” toward the information carried by “cube”.</h2><div className={styles.sliders}>{tokens.map((t,i)=><label className={styles.slider} key={t}><b>{t}</b><input type="range" min="0" max="100" value={raw[i]} onChange={e=>setWeight(i,+e.target.value)}/><small>{Math.round(weights[i]*100)}%</small></label>)}</div><div className={styles.stats}><div className={styles.stat}><span>Baseline output</span><b>[{baseline.map(x=>x.toFixed(3)).join(", ")}]</b></div><div className={styles.stat}><span>Edited output</span><b>[{manual.map(x=>x.toFixed(3)).join(", ")}]</b></div><div className={styles.stat}><span>Representation moved</span><b>{move.toFixed(3)}</b></div></div></LessonSection>
 <LessonSection id="mask-incident" onVisit={progress.markVisited} className={styles.scene}><TaskStamp done={!!progress.completedTasks["m4-fix-causal-mask"]}>MISSION 03 · FUTURE LEAKAGE</TaskStamp><h2>A decoder token is attending to a future answer token.</h2><div className={styles.controls}><button className={`${styles.button} ${maskFixed?styles.correct:""}`} onClick={()=>{setMaskFixed(true);progress.completeTask("m4-fix-causal-mask")}}>Mask future positions before softmax</button><button className={styles.button} onClick={()=>setFeedback("Wrong direction: changing tokenizer does not enforce autoregressive visibility.")}>Change tokenizer</button></div><AttentionMatrix tokens={["A","B","C"]} weights={maskFixed?[[1,0,0],[.45,.55,0],[.2,.3,.5]]:[[.45,.35,.2],[.3,.4,.3],[.2,.3,.5]]} activeRow={1} masked={maskFixed?[[false,true,true],[false,false,true],[false,false,false]]:undefined}/></LessonSection>
 <LessonSection id="position-room" onVisit={progress.markVisited} className={styles.scene}><TaskStamp done={!!progress.completedTasks["m4-position-choice"]}>MISSION 04 · POSITION STRATEGY</TaskStamp><h2>Match the mechanism to its description.</h2><div className={styles.caseGrid}>{["Trainable table indexed by absolute position.","Fixed sin/cos function of absolute position.","Position-dependent rotations applied to Q/K feature pairs."].map((text,i)=><div className={styles.case} key={text}><p>{text}</p>{(["learned","sinusoidal","rope"] as PositionChoice[]).map(a=><button key={a} className={positionAnswers[i]===a?(["learned","sinusoidal","rope"][i]===a?styles.correct:styles.wrong):""} onClick={()=>choosePos(i,a)}>{a}</button>)}</div>)}</div></LessonSection>
 <LessonSection id="head-room" onVisit={progress.markVisited} className={styles.scene}><TaskStamp done={!!progress.completedTasks["m4-head-comparison"]}>MISSION 05 · MULTI-HEAD</TaskStamp><h2>Verify that two heads form different interaction matrices.</h2><div className={styles.grid2}><div><button className={styles.button} onClick={()=>seeHead("h1")}>Inspect head 1</button><AttentionMatrix tokens={tokens} weights={h1.weights} activeRow={1}/></div><div><button className={styles.button} onClick={()=>seeHead("h2")}>Inspect head 2</button><AttentionMatrix tokens={tokens} weights={h2.weights} activeRow={1}/></div></div></LessonSection>
 <LessonSection id="cache-room" onVisit={progress.markVisited} className={styles.scene}><TaskStamp done={!!progress.completedTasks["m4-cache-choice"]}>MISSION 06 · DECODE EFFICIENCY</TaskStamp><h2>Five tokens generated; past K/V projections keep being recomputed.</h2><div className={styles.controls}>{["recompute prefix","KV cache","change BPE"].map(x=><button key={x} className={`${styles.button} ${cache===x?(x==="KV cache"?styles.correct:styles.wrong):""}`} onClick={()=>{setCache(x);if(x==="KV cache")progress.completeTask("m4-cache-choice")}}>{x}</button>)}</div></LessonSection>
 <LessonSection id="family-room" onVisit={progress.markVisited} className={styles.scene}><TaskStamp done={!!progress.completedTasks["m4-family-choice"]}>MISSION 07 · FAMILY ROUTING</TaskStamp><h2>Choose encoder, decoder or encoder-decoder.</h2><div className={styles.caseGrid}>{familyCases.map((c,i)=><div className={styles.case} key={c.text}><p>{c.text}</p>{(["encoder","decoder","encdec"] as Family[]).map(a=><button key={a} className={familyAnswers[i]===a?(a===c.answer?styles.correct:styles.wrong):""} onClick={()=>chooseFamily(i,a)}>{a}</button>)}</div>)}</div></LessonSection>
 <LessonSection id="ship-block" onVisit={progress.markVisited} className={styles.scene}><TaskStamp done={!!progress.completedTasks["m4-ship-block"]}>MISSION 08 · SHIP</TaskStamp><h2>Ship only when the attention system is coherent.</h2><button className={styles.button} onClick={ship}>Ship transformer checkpoint</button>{feedback&&<div className={styles.feedback}>{feedback}</div>}</LessonSection>
 <section className={styles.exam}><h2>Module 4 Mastery Exam</h2>{!unlocked?<div className={styles.locked}>Locked: {tasks}/8 missions · {rooms}/8 rooms.</div>:<>{exam.map((q,i)=><div className={styles.question} key={q.q}><strong>{i+1}. {q.q}</strong>{q.o.map((o,j)=><button key={o} className={quizAnswers[i]===j?styles.selected:""} onClick={()=>setQuizAnswers(a=>({...a,[i]:j}))}>{o}</button>)}</div>)}<button className={styles.button} onClick={submit}>Submit mastery exam</button>{feedback&&<div className={styles.feedback}>{feedback}</div>}</>}<div className={styles.footer}><Link href="/lessons/encoder-decoder-architectures">← Transformer families</Link><Link href="/">Course map →</Link></div></section>
 </main>
}
