"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { AiMascot } from "@/components/mascots/ai-mascot";
import { LessonProgressApi } from "@/components/course/lesson-shell";
import { DepthSwitch, LessonSection, TaskStamp } from "@/components/course/lesson-primitives";
import { tokenizerA } from "@/components/lessons/tokens-tokenization/tokenizer-data";
import styles from "./rag-ingestion-chunking.module.css";

type Props={progress:LessonProgressApi};
const rawDoc=`<nav>Home | Rooms | Spa | Contact</nav>\nHOTEL LINDEN — GUEST POLICY v3\nQuiet floors are available on levels 4 and 5. Quiet hours begin at 22:00 and end at 07:00. Guests should avoid loud music, corridor calls and door slamming during this period.\nBreakfast is served from 06:30 until 10:30 in the garden restaurant.\nLate check-in is available 24 hours through reception.\nThe gym is open 24 hours.\n<footer>© 2026 · Cookie preferences · Instagram</footer>`;
const cleanDoc=`HOTEL LINDEN — GUEST POLICY v3. Quiet floors are available on levels 4 and 5. Quiet hours begin at 22:00 and end at 07:00. Guests should avoid loud music, corridor calls and door slamming during this period. Breakfast is served from 06:30 until 10:30 in the garden restaurant. Late check-in is available 24 hours through reception. The gym is open 24 hours.`;
const quiz=[
["RAG is useful because it can…",["Retrieve external/current/private evidence into context at request time","Rewrite model weights every query","Guarantee truth automatically","Replace tokenization"],0],
["RAG vs fine-tuning differs because…",["RAG supplies retrieved evidence at inference; fine-tuning changes model parameters","They are identical","RAG always trains adapters","Fine-tuning is keyword search"],0],
["Chunk size controls…",["How much document text is grouped into each retrievable unit","Model parameter count","GPU precision","Reward model score"],0],
["Chunk overlap can help…",["Preserve information crossing chunk boundaries, at the cost of duplicated tokens/index entries","Eliminate embeddings","Train the tokenizer","Guarantee citations"],0],
["Useful metadata can support…",["Filtering by source/date/tenant/type before or during retrieval","Changing attention heads","Backpropagation","PPO"],0],
["Embedding a chunk means…",["Mapping its content to a vector representation for similarity search","Putting it directly in model weights","Converting it to JSON only","Creating a system prompt"],0],
["Grounded generation should ideally…",["Use retrieved evidence and preserve source references/citations when needed","Invent missing evidence","Hide sources","Ignore retrieval scores"],0],
["A huge chunk is always better than a small chunk.",["True","False"],1],
] as const;

function makeChunks(text:string,size:number,overlap:number){const words=text.split(/\s+/).filter(Boolean);const chunks:string[]=[];const step=Math.max(1,size-overlap);for(let start=0;start<words.length;start+=step){chunks.push(words.slice(start,start+size).join(" "));if(start+size>=words.length)break;}return chunks;}

export function RagIngestionChunkingLesson({progress}:Props){
 const [why,setWhy]=useState<string[]>([]),[formats,setFormats]=useState<string[]>([]),[cleaned,setCleaned]=useState(false),[chunkSize,setChunkSize]=useState(18),[chunkTouched,setChunkTouched]=useState(false),[overlap,setOverlap]=useState(2),[overlapTouched,setOverlapTouched]=useState(false),[metadata,setMetadata]=useState<string[]>([]),[indexSteps,setIndexSteps]=useState<string[]>([]),[selectedChunk,setSelectedChunk]=useState<number|null>(null),[explain,setExplain]=useState(""),[explainFeedback,setExplainFeedback]=useState(""),[answers,setAnswers]=useState<Record<number,number>>({});
 const chunks=useMemo(()=>makeChunks(cleanDoc,chunkSize,Math.min(overlap,chunkSize-1)),[chunkSize,overlap]);
 const targetChunk=chunks.findIndex(c=>c.toLowerCase().includes("quiet hours begin at 22:00")&&c.toLowerCase().includes("end at 07:00"));
 const duplicateCost=Math.max(0,(chunks.reduce((s,c)=>s+tokenizerA(c).length,0)-tokenizerA(cleanDoc).length));
 const taskIds=["rag-why","rag-ingest","rag-clean","rag-chunk","rag-overlap","rag-metadata","rag-index","rag-assemble","rag-ingest-explain"],sectionIds=["why-rag","ingest","clean","chunk","overlap","metadata","embed-index","assemble","explain"];
 const taskCount=taskIds.filter(id=>progress.completedTasks[id]).length,readCount=sectionIds.filter(id=>progress.visitedSections.has(id)).length,unlocked=taskCount===9&&readCount===9;
 const quizScore=quiz.reduce((s,q,i)=>s+(answers[i]===q[2]?1:0),0),quizComplete=Object.keys(answers).length===quiz.length;
 const mark=(v:string,current:string[],setter:(v:string[])=>void,n:number,task:string)=>{const next=[...new Set([...current,v])];setter(next);if(next.length>=n)progress.completeTask(task)};
 const submitExplain=()=>{const t=explain.toLowerCase();const hits=["retrieve","chunk","overlap","metadata","embed","index","context","citation"].filter(w=>t.includes(w)).length;if(explain.length<100||hits<4){setExplainFeedback("Go deeper: describe ingest/clean → chunk → metadata → embeddings/index → retrieve → context/citation.");return;}setExplainFeedback("Strong. You described RAG as a retrieval pipeline around the model, not as new knowledge magically written into its weights.");progress.completeTask("rag-ingest-explain")};
 return <main className={styles.root}>
  <section className={styles.hero}><div><span className={styles.eyebrow}>MODULE 9 · RAG DOCUMENT LAB</span><h1>Do not stuff the whole knowledge base into the prompt.</h1><p>RAG is an information pipeline: prepare documents, split them into retrievable units, index representations, retrieve useful evidence for the current query, then give only selected evidence to the model.</p><DepthSwitch value={progress.depth} onChange={progress.setDepth}/><TaskStamp done={taskCount===9}>{taskCount}/9 ingestion missions complete</TaskStamp></div><div className={styles.stage}><AiMascot variant="mail" accent="#b492ff" mood={cleaned?"happy":"thinking"} size={100} label="DOC"/><AiMascot variant="tile" accent="#8de475" mood={indexSteps.length>=3?"excited":"thinking"} size={100} label="INDEX"/><AiMascot variant="briefcase" accent="#6ed8d1" mood={selectedChunk!==null?"excited":"happy"} size={100} label="RAG"/></div></section>

  <LessonSection id="why-rag" onVisit={progress.markVisited} className={styles.scene}><h2>1. Why RAG exists</h2><div className={styles.grid3}>{[
   ["fresh","Fresh/private knowledge","Retrieve material that was not reliably inside pretraining weights."],
   ["evidence","Evidence","Make the answer depend on inspectable retrieved sources."],
   ["update","Fast updates","Change indexed documents without retraining the base model."],
  ].map(([id,title,copy])=><button className={`${styles.panel} ${why.includes(id)?styles.correct:""}`} key={id} onClick={()=>mark(id,why,setWhy,3,"rag-why")}><b>{title}</b><p>{copy}</p></button>)}</div><p>Fine-tuning can adapt behavior/knowledge patterns in weights. RAG retrieves external evidence at request time. Production systems can use both.</p></LessonSection>

  <LessonSection id="ingest" onVisit={progress.markVisited} className={styles.scene}><h2>2. Ingestion starts before vectors.</h2><p>A source can be PDF, HTML, Markdown, database rows or other formats. First extract useful content and structure.</p><div className={styles.grid3}>{["HTML parser","PDF text/layout parser","Database/API loader"].map(name=><button className={`${styles.panel} ${formats.includes(name)?styles.correct:""}`} key={name} onClick={()=>mark(name,formats,setFormats,3,"rag-ingest")}><b>{name}</b><p>Convert source-specific representation into normalized document records.</p></button>)}</div></LessonSection>

  <LessonSection id="clean" onVisit={progress.markVisited} className={styles.scene}><h2>3. Search engines should not retrieve cookie banners as knowledge.</h2><div className={styles.grid2}><pre className={styles.raw}>{cleaned?cleanDoc:rawDoc}</pre><div className={styles.panel}><b>Cleaning operations</b><p>Remove navigation/footer boilerplate, preserve title/version, normalize whitespace, keep content relevant to retrieval.</p><button className={styles.button} onClick={()=>{setCleaned(true);progress.completeTask("rag-clean")}}>Remove boilerplate</button></div></div></LessonSection>

  <LessonSection id="chunk" onVisit={progress.markVisited} className={styles.scene}><h2>4. Chunk size changes what can be retrieved as one unit.</h2><div className={styles.control}><label>Chunk size <b>{chunkSize} words</b></label><input type="range" min="8" max="42" value={chunkSize} onChange={e=>{setChunkSize(+e.target.value);setChunkTouched(true);if(+e.target.value>=12&&+e.target.value<=28)progress.completeTask("rag-chunk")}}/></div><div className={styles.chunks}>{chunks.map((chunk,i)=><div className={`${styles.chunk} ${i===targetChunk?styles.correct:""}`} key={`${i}-${chunk}`}><b>chunk {i+1}</b><p>{chunk}</p><small>{tokenizerA(chunk).length} toy tokens</small></div>)}</div><p>{targetChunk>=0?"✓ One chunk contains the full quiet-hours fact.":"⚠ The exact quiet-hours relationship is split across boundaries. Try a different size/overlap."}</p></LessonSection>

  <LessonSection id="overlap" onVisit={progress.markVisited} className={styles.scene}><h2>5. Overlap buys boundary safety with duplicate index cost.</h2><div className={styles.control}><label>Overlap <b>{overlap} words</b></label><input type="range" min="0" max="10" value={overlap} onChange={e=>{setOverlap(+e.target.value);setOverlapTouched(true);if(+e.target.value>=3&&+e.target.value<=7)progress.completeTask("rag-overlap")}}/></div><div className={styles.grid3}><div className={styles.panel}><b>Chunks</b><p>{chunks.length}</p></div><div className={styles.panel}><b>Document tokens</b><p>{tokenizerA(cleanDoc).length}</p></div><div className={styles.panel}><b>Repeated toy tokens</b><p>+{duplicateCost}</p></div></div>{overlapTouched&&<p className={styles.feedback}>Overlap can preserve cross-boundary meaning, but it increases storage/retrieval duplication. It is a tuning parameter, not a ritual.</p>}</LessonSection>

  <LessonSection id="metadata" onVisit={progress.markVisited} className={styles.scene}><h2>6. Metadata gives retrieval another axis besides similarity.</h2><div className={styles.grid3}>{["source:hotel-policy","version:v3","tenant:hotel-linden","updated:2026-08-20","language:en","doc_type:policy"].map(item=><button key={item} className={`${styles.panel} ${metadata.includes(item)?styles.correct:""}`} onClick={()=>mark(item,metadata,setMetadata,4,"rag-metadata")}><b>{item}</b></button>)}</div><div className={styles.meta}>{metadata.map(m=><span key={m}>{m}</span>)}</div><p>Useful metadata enables tenant isolation, freshness filters, document-type constraints and better citation traces.</p></LessonSection>

  <LessonSection id="embed-index" onVisit={progress.markVisited} className={styles.scene}><h2>7. Chunk text → embedding vector → searchable index.</h2><div className={styles.pipeline}>{[
   ["chunk","CHUNK"],["embed","EMBEDDING MODEL"],["vector","VECTOR + METADATA"],["index","INDEX"],
  ].map(([id,title],i)=><span key={id}><button className={`${styles.node} ${indexSteps.includes(id)?styles.correct:""}`} onClick={()=>mark(id,indexSteps,setIndexSteps,4,"rag-index")}>{title}</button>{i<3&&<span className={styles.arrow}>→</span>}</span>)}</div><p>The embedding model and the LLM can be separate models. Indexing stores vectors/metadata so future queries can find similar chunks efficiently.</p></LessonSection>

  <LessonSection id="assemble" onVisit={progress.markVisited} className={styles.scene}><h2>8. Retrieval is only useful when the right evidence reaches context.</h2><p>User query: <b>“When do quiet hours start and end?”</b></p><div className={styles.chunks}>{chunks.map((chunk,i)=><button className={`${styles.chunk} ${selectedChunk===i?(i===targetChunk?styles.correct:styles.wrong):""}`} key={i} onClick={()=>{setSelectedChunk(i);if(i===targetChunk)progress.completeTask("rag-assemble")}}><b>retrieve chunk {i+1}</b><p>{chunk}</p></button>)}</div>{selectedChunk===targetChunk&&<div className={styles.context}><b>CONTEXT EVIDENCE</b><p>{chunks[targetChunk]}</p><p>Answer: Quiet hours begin at 22:00 and end at 07:00. <b>[Hotel Linden Guest Policy v3]</b></p></div>}</LessonSection>

  <LessonSection id="explain" onVisit={progress.markVisited} className={`${styles.scene} ${styles.explain}`}><h2>9. Explain ingestion before retrieval.</h2><textarea value={explain} onChange={e=>setExplain(e.target.value)} placeholder="Explain ingest, cleaning, chunking/overlap, metadata, embeddings/index and how retrieved chunks become grounded context."/><button className={styles.button} onClick={submitExplain}>Check explanation</button>{explainFeedback&&<p className={styles.feedback}>{explainFeedback}</p>}</LessonSection>

  <section className={styles.quiz}><h2>RAG ingestion mastery quiz</h2>{!unlocked?<div className={styles.locked}>🔒 Complete all nine document-lab rooms. {taskCount}/9 tasks · {readCount}/9 sections.</div>:<>{quiz.map((q,i)=><div className={styles.question} key={q[0]}><strong>{i+1}. {q[0]}</strong>{q[1].map((option,oi)=><button key={option} className={answers[i]===oi?styles.selected:""} onClick={()=>setAnswers(current=>({...current,[i]:oi}))}>{option}</button>)}{answers[i]!==undefined&&<small>{answers[i]===q[2]?"✓ Correct":`Correct: ${q[1][q[2]]}`}</small>}</div>)}<button className={styles.button} disabled={!quizComplete} onClick={()=>progress.saveQuiz(quizScore,quizScore>=7)}>Submit · {quizScore}/8</button>{quizComplete&&<p className={styles.feedback}>{quizScore>=7?"★ INGESTION & CHUNKING MASTERED":"Pass is 7/8. Revisit chunk boundaries and metadata."}</p>}</>}</section>
  <div className={styles.footer}><Link href="/lessons/module-8-capstone">← Reasoning module</Link><Link href="/lessons/retrieval-ranking-lab">Retrieval & Ranking →</Link></div>
 </main>
}
