"use client";

import Link from "next/link";
import { useState } from "react";
import { LessonProgressApi } from "@/components/course/lesson-shell";
import { DepthSwitch, LessonSection, TaskStamp } from "@/components/course/lesson-primitives";
import { chooseCases, defs, Family, quiz } from "./tokenizer-families-data";
import styles from "./tokenizer-families.module.css";

type Props={progress:LessonProgressApi};
const bpe=[['l','o','w','e','r'],['lo','w','e','r'],['low','e','r'],['low','er'],['lower']];
const wordpiece=[['play','##ing'],['un','##believ','##able'],['token','##ization']];
const sentencepiece=[['▁AI','▁models','▁learn'],['▁New','▁York','▁City'],['▁token','ization','▁rocks']];

export function TokenizerFamiliesLesson({progress}:Props){
 const [seen,setSeen]=useState<Family[]>([]);const [bpeStep,setBpeStep]=useState(0);const [wp,setWp]=useState(0);const [sp,setSp]=useState(0);const [white,setWhite]=useState(false);const [unknownMode,setUnknownMode]=useState<"unk"|"pieces"|"bytes">("unk");const [unknownSeen,setUnknownSeen]=useState<string[]>([]);const [vocab,setVocab]=useState(8000);const [answers,setAnswers]=useState<Record<number,Family>>({});const [explanation,setExplanation]=useState("");const [feedback,setFeedback]=useState("");const [quizAnswers,setQuizAnswers]=useState<Record<number,number>>({});const [quizFeedback,setQuizFeedback]=useState("");
 const tasks=defs.filter(([,t])=>progress.completedTasks[t]).length,rooms=defs.filter(([id])=>progress.visitedSections.has(id)).length,unlocked=tasks===9&&rooms===9;
 const seq=Math.round(34-Math.log2(vocab/1000)*3.2),rare=Math.round(Math.max(2,15-Math.log2(vocab/1000)*2));
 const copy={simple:"BPE, WordPiece and SentencePiece all create reusable subword pieces, but they are not the same machine. Their training rules and treatment of raw text differ.",real:"BPE learns adjacent merges; WordPiece uses a different vocabulary-building/segmentation objective and is often taught with continuation pieces; SentencePiece can model raw text directly and represents whitespace explicitly.",expert:"These tokenizer families share a subword goal but differ in vocabulary induction, segmentation model and preprocessing assumptions. SentencePiece is a framework supporting models such as unigram and BPE; WordPiece's vocabulary construction is distinct from vanilla BPE, so the names should not be used interchangeably."} as const;
 const inspect=(f:Family)=>{const n=seen.includes(f)?seen:[...seen,f];setSeen(n);if(n.length===3)progress.completeTask("inspect-tokenizer-families")};
 const unknown=(m:string)=>{setUnknownMode(m as typeof unknownMode);const n=unknownSeen.includes(m)?unknownSeen:[...unknownSeen,m];setUnknownSeen(n);if(n.length===3)progress.completeTask("compare-unknown-handling")};
 const choose=(i:number,a:Family)=>{const n={...answers,[i]:a};setAnswers(n);if(chooseCases.every((c,j)=>n[j]===c.answer))progress.completeTask("choose-tokenizer-family")};
 const explain=()=>{const t=explanation.toLowerCase();const hits=["bpe","merge","wordpiece","sentencepiece","whitespace","vocab","subword"].filter(k=>t.includes(k));if(explanation.trim().length<110||hits.length<5){setFeedback("Explain the common subword goal and at least one concrete difference among BPE, WordPiece and SentencePiece, including raw text/whitespace handling.");return;}setFeedback("Good. You described three related tokenizer designs without collapsing them into one algorithm.");progress.completeTask("explain-tokenizer-families")};
 const submitQuiz=()=>{const s=quiz.reduce((n,q,i)=>n+(quizAnswers[i]===q.c?1:0),0),p=s>=6;progress.saveQuiz(s,p);setQuizFeedback(p?`Passed ${s}/7.`:`${s}/7. Need 6/7.`)};
 return <main className={styles.root}>
  <section className={styles.hero}><div><span className={styles.eyebrow}>MODULE 3 · TOKENIZER FAMILY WORKSHOP</span><h1>Three ways to build subwords.</h1><p>{copy[progress.depth]}</p><DepthSwitch value={progress.depth} onChange={progress.setDepth}/></div><div className={styles.bench}><b>OPEN ALL BENCHES</b><div className={styles.familyGrid}>{(["bpe","wordpiece","sentencepiece"] as Family[]).map(f=><button key={f} className={styles.family} onClick={()=>inspect(f)}>{f.toUpperCase()}<br/><small>{seen.includes(f)?"inspected":"open"}</small></button>)}</div><p>{tasks}/9 experiments complete</p></div></section>
  <LessonSection id="three-families" onVisit={progress.markVisited} className={styles.scene}><TaskStamp done={!!progress.completedTasks["inspect-tokenizer-families"]}>01 · THREE FAMILIES</TaskStamp><h2>Related goal, different machinery.</h2><div className={styles.familyGrid}><div className={styles.family}>BPE<br/><small>adjacent merge rules</small></div><div className={styles.family}>WordPiece<br/><small>subword vocabulary/segmentation scoring</small></div><div className={styles.family}>SentencePiece<br/><small>raw text modeling framework</small></div></div></LessonSection>
  <LessonSection id="bpe-workshop" onVisit={progress.markVisited} className={styles.scene}><TaskStamp done={!!progress.completedTasks["build-bpe-token"]}>02 · BPE</TaskStamp><h2>Repeatedly merge adjacent symbols.</h2><div className={styles.pieceRow}>{bpe[bpeStep].map((x,i)=><span className={styles.piece} key={i}>{x}</span>)}</div><button className={styles.button} onClick={()=>setBpeStep(s=>{const n=Math.min(4,s+1);if(n===4)progress.completeTask("build-bpe-token");return n})}>Apply next merge</button><p>Step {bpeStep}/4. Real merge tables are learned from corpus statistics.</p></LessonSection>
  <LessonSection id="wordpiece-workshop" onVisit={progress.markVisited} className={styles.scene}><TaskStamp done={!!progress.completedTasks["build-wordpiece-token"]}>03 · WORDPIECE</TaskStamp><h2>Inspect continuation subwords.</h2><div className={styles.pieceRow}>{wordpiece[wp].map((x,i)=><span className={`${styles.piece} ${styles.wp}`} key={i}>{x}</span>)}</div><button className={styles.button} onClick={()=>setWp(s=>{const n=(s+1)%wordpiece.length;if(s>=1)progress.completeTask("build-wordpiece-token");return n})}>Next example</button><p><b>##</b> is a common educational rendering meaning “this piece continues the current word”; it is not a universal marker across all tokenizers.</p></LessonSection>
  <LessonSection id="sentencepiece-workshop" onVisit={progress.markVisited} className={styles.scene}><TaskStamp done={!!progress.completedTasks["inspect-sentencepiece"]}>04 · SENTENCEPIECE</TaskStamp><h2>Treat raw text as the source stream.</h2><div className={styles.pieceRow}>{sentencepiece[sp].map((x,i)=><span className={`${styles.piece} ${styles.sp}`} key={i}>{x}</span>)}</div><button className={styles.button} onClick={()=>{setSp(s=>(s+1)%3);progress.completeTask("inspect-sentencepiece")}}>Inspect another raw-text segmentation</button><p>SentencePiece is a tokenizer framework; it can use algorithms such as unigram or BPE rather than being “the opposite of BPE”.</p></LessonSection>
  <LessonSection id="whitespace" onVisit={progress.markVisited} className={styles.scene}><TaskStamp done={!!progress.completedTasks["inspect-whitespace-markers"]}>05 · WHITESPACE</TaskStamp><h2>Make spaces visible.</h2><button className={styles.button} onClick={()=>{setWhite(true);progress.completeTask("inspect-whitespace-markers")}}>Reveal raw stream markers</button>{white&&<div className={styles.pieceRow}>{["▁New","▁York","▁is","▁busy","."].map((x,i)=><span className={`${styles.piece} ${styles.sp}`} key={i}>{x}</span>)}</div>}<p>The `▁` marker is commonly used in SentencePiece renderings to encode preceding whitespace/boundary information.</p></LessonSection>
  <LessonSection id="unknowns" onVisit={progress.markVisited} className={styles.scene}><TaskStamp done={!!progress.completedTasks["compare-unknown-handling"]}>06 · UNSEEN TEXT</TaskStamp><h2>What happens to a strange string?</h2><p>Try three toy fallback policies for <code>xy🛸z</code>.</p><div className={styles.controls}>{["unk","pieces","bytes"].map(m=><button key={m} className={styles.button} onClick={()=>unknown(m)}>{m}</button>)}</div><div className={styles.pieceRow}>{unknownMode==="unk"?["<UNK>"]:unknownMode==="pieces"?["x","y","🛸","z"]:["78","79","f0","9f","9b","b8","7a"].map((x,i)=><span className={styles.piece} key={i}>{x}</span>)}</div><p>Fallback details vary by tokenizer/model; byte-level or byte-fallback designs can avoid many hard unknowns.</p></LessonSection>
  <LessonSection id="tradeoffs" onVisit={progress.markVisited} className={styles.scene}><TaskStamp done={!!progress.completedTasks["compare-tokenizer-tradeoffs"]}>07 · VOCABULARY TRADEOFF</TaskStamp><h2>Bigger vocabulary, usually fewer pieces — but more embedding rows.</h2><div className={styles.controls}><label className={styles.panel}>Vocabulary {vocab}<input style={{width:"100%"}} type="range" min="2000" max="64000" step="2000" value={vocab} onChange={e=>setVocab(+e.target.value)}/></label><button className={styles.button} onClick={()=>{if(vocab>=40000)progress.completeTask("compare-tokenizer-tradeoffs")}}>Measure</button></div><div className={styles.stats}><div className={styles.stat}><span>Sequence proxy</span><b>{seq}</b></div><div className={styles.stat}><span>Rare splits proxy</span><b>{rare}</b></div><div className={styles.stat}><span>Embedding rows</span><b>{vocab}</b></div></div></LessonSection>
  <LessonSection id="choose-family" onVisit={progress.markVisited} className={styles.scene}><TaskStamp done={!!progress.completedTasks["choose-tokenizer-family"]}>08 · CHOOSE THE DESIGN</TaskStamp><h2>Match the description, not the brand name.</h2><div className={styles.choiceGrid}>{chooseCases.map((c,i)=><div className={styles.case} key={c.text}><p>{c.text}</p>{(["bpe","wordpiece","sentencepiece"] as Family[]).map(a=><button key={a} className={answers[i]===a?(a===c.answer?styles.correct:styles.wrong):""} onClick={()=>choose(i,a)}>{a}</button>)}</div>)}</div></LessonSection>
  <LessonSection id="explain-families" onVisit={progress.markVisited} className={`${styles.scene} ${styles.explain}`}><TaskStamp done={!!progress.completedTasks["explain-tokenizer-families"]}>09 · EXPLAIN IT BACK</TaskStamp><h2>Why are BPE, WordPiece and SentencePiece not synonyms?</h2><textarea value={explanation} onChange={e=>setExplanation(e.target.value)}/><button className={styles.button} onClick={explain}>Check explanation</button>{feedback&&<div className={styles.feedback}>{feedback}</div>}</LessonSection>
  <section className={styles.quiz}><h2>Tokenizer Family Check</h2>{!unlocked?<div className={styles.locked}>Locked: {tasks}/9 tasks · {rooms}/9 rooms.</div>:<>{quiz.map((q,i)=><div className={styles.question} key={q.q}><strong>{i+1}. {q.q}</strong>{q.o.map((o,j)=><button key={o} className={quizAnswers[i]===j?styles.selected:""} onClick={()=>setQuizAnswers(a=>({...a,[i]:j}))}>{o}</button>)}</div>)}<button className={styles.button} onClick={submitQuiz}>Submit quiz</button>{quizFeedback&&<div className={styles.feedback}>{quizFeedback}</div>}</>}<div className={styles.footer}><Link href="/lessons/tokens-tokenization">← Tokens</Link><Link href="/lessons/embeddings-vectors">Embeddings →</Link></div></section>
 </main>
}
