"use client";

import Link from "next/link";
import { useState } from "react";
import { AiMascot } from "@/components/mascots/ai-mascot";
import { LessonProgressApi } from "@/components/course/lesson-shell";
import { DepthSwitch, LessonSection, TaskStamp } from "@/components/course/lesson-primitives";
import styles from "./efficient-adaptation.module.css";

type Props={progress:LessonProgressApi};
const quiz=[
 ["PEFT means…",["Parameter-efficient fine-tuning methods that update a small subset/additional parameters","Pretraining every parameter from scratch","Prompt caching","Evaluation only"],0],
 ["LoRA approximates an update with…",["Low-rank trainable matrices added around a frozen/base weight transformation","A vector database","A tokenizer merge","Only a larger batch"],0],
 ["QLoRA commonly combines…",["A quantized frozen base model with trainable LoRA adapters","Full FP32 fine-tuning only","RAG and RLHF only","KV cache and BPE"],0],
 ["Knowledge distillation trains…",["A smaller/student model to imitate useful teacher behavior/distributions","A reward model only","A tokenizer","A database"],0],
 ["Model merging can…",["Combine parameter deltas/checkpoints but may create interference and requires evaluation","Guarantee perfect skill addition","Avoid all testing","Only merge prompts"],0],
 ["Catastrophic forgetting means…",["New training can degrade previously learned capabilities","The context window overflowed","A GPU cache expired","A tool timed out"],0],
 ["Quantization-aware training…",["Simulates/accounts for quantization effects during training so the model can adapt to them","Only runs after inference","Means LoRA rank=4","Is the same as pruning"],0],
 ["Domain fine-tuning should still be evaluated on…",["Target domain plus retained/general capabilities that matter","Only training loss","Only parameter count","Only token price"],0],
] as const;

export function EfficientAdaptationLesson({progress}:Props){
 const [mode,setMode]=useState<"full"|"peft">("full"),[seenModes,setSeenModes]=useState<string[]>([]),[rank,setRank]=useState(2),[loraTouched,setLoraTouched]=useState(false),[qloraSteps,setQloraSteps]=useState<string[]>([]),[adapterChoice,setAdapterChoice]=useState(""),[teacherMix,setTeacherMix]=useState(0),[merge,setMerge]=useState(50),[mergeTouched,setMergeTouched]=useState(false),[newDomain,setNewDomain]=useState(0),[replay,setReplay]=useState(0),[continualTouched,setContinualTouched]=useState(false),[bits,setBits]=useState(16),[qat,setQat]=useState(false),[explain,setExplain]=useState(""),[explainFeedback,setExplainFeedback]=useState(""),[answers,setAnswers]=useState<Record<number,number>>({});
 const taskIds=["adapt-full-peft","adapt-lora","adapt-qlora","adapt-adapters","adapt-distill","adapt-merge","adapt-continual","adapt-qat","adapt-explain"];
 const sectionIds=["full-vs-peft","lora","qlora","adapters","distillation","merging","continual","qat","explain"];
 const taskCount=taskIds.filter(id=>progress.completedTasks[id]).length,readCount=sectionIds.filter(id=>progress.visitedSections.has(id)).length,unlocked=taskCount===9&&readCount===9;
 const trainFraction=mode==="full"?100:Math.max(.3,rank/64*100);
 const loraParams=rank*2*1024;
 const qloraDone=["quant","freeze","adapter"].every(x=>qloraSteps.includes(x));
 const studentQuality=Math.round(48+teacherMix*.45),studentCost=Math.max(18,100-Math.round(teacherMix*.55));
 const mergeA=Math.round(86-(merge/100)*24),mergeB=Math.round(62+(merge/100)*27);
 const oldSkill=Math.max(20,92-newDomain*.62+replay*.42),newSkill=Math.min(96,45+newDomain*.55);
 const quantQuality=Math.max(70,96-(16-bits)*1.1+(qat?5:0));
 const quizScore=quiz.reduce((s,q,i)=>s+(answers[i]===q[2]?1:0),0),quizComplete=Object.keys(answers).length===quiz.length;
 const mark=(v:string,current:string[],setter:(x:string[])=>void,n:number,task:string)=>{const next=[...new Set([...current,v])];setter(next);if(next.length>=n)progress.completeTask(task)};
 const submitExplain=()=>{const t=explain.toLowerCase();const hits=["lora","rank","frozen","quant","distill","merge","forget","adapter"].filter(w=>t.includes(w)).length;if(explain.length<100||hits<4){setExplainFeedback("Go deeper: explain why LoRA/PEFT update fewer parameters, what QLoRA quantizes, and at least one risk from merging or continual learning.");return;}setExplainFeedback("Strong. You described efficient adaptation as changing where/how much we train, not as a different kind of model intelligence.");progress.completeTask("adapt-explain")};
 return <main className={styles.root}>
  <section className={styles.hero}><div><span className={styles.eyebrow}>MODULE 7 · ADAPTATION LAB</span><h1>Change the model without rebuilding the whole factory.</h1><p>Full fine-tuning can update every trainable weight. PEFT methods try to get useful adaptation with a much smaller trainable footprint. Then we explore compression, distillation, merging and the danger of forgetting old skills.</p><DepthSwitch value={progress.depth} onChange={progress.setDepth}/><TaskStamp done={taskCount===9}>{taskCount}/9 adaptation missions complete</TaskStamp></div><div className={styles.lab}><AiMascot variant="tile" accent="#91e575" mood={taskCount>2?"happy":"thinking"} size={105} label="ADAPTER"/><AiMascot variant="briefcase" accent="#70d9d1" mood={taskCount>5?"excited":"happy"} size={105} label="BASE"/></div></section>

  <LessonSection id="full-vs-peft" onVisit={progress.markVisited} className={styles.scene}><h2>1. Which weights are allowed to move?</h2><div className={styles.grid2}>{(["full","peft"] as const).map(m=><button key={m} className={`${styles.panel} ${mode===m?styles.correct:""}`} onClick={()=>{setMode(m);mark(m,seenModes,setSeenModes,2,"adapt-full-peft")}}><b>{m==="full"?"FULL FINE-TUNING":"PEFT / ADAPTER APPROACH"}</b><p>{m==="full"?"Potentially update the base model's full trainable parameter set.":"Freeze most base weights and train a small added/subset parameter set."}</p></button>)}</div><div className={styles.matrix}>{Array.from({length:64},(_,i)=><i key={i} className={`${styles.cell} ${mode==="full"||i<Math.max(1,Math.round(rank/2))?styles.train:""}`}/>)}</div><p>Approx toy trainable fraction: <b>{trainFraction.toFixed(2)}%</b>.</p></LessonSection>

  <LessonSection id="lora" onVisit={progress.markVisited} className={styles.scene}><h2>2. LoRA: learn a low-rank update beside a frozen weight.</h2><p>Instead of directly updating a large weight matrix W, LoRA learns a lower-rank update ΔW ≈ B·A. Rank controls adapter capacity and parameter count.</p><div className={styles.control}><label>LoRA rank r <b>{rank}</b></label><input type="range" min="1" max="32" value={rank} onChange={e=>{setRank(+e.target.value);setLoraTouched(true);if(+e.target.value>=4)progress.completeTask("adapt-lora")}}/></div><div className={styles.equation}>{`y = W_frozen x + scale · B_r(A_r x)\nToy adapter params ≈ 2 · 1024 · r = ${loraParams.toLocaleString()}`}</div>{loraTouched&&<p className={styles.feedback}>Smaller rank → fewer trainable parameters; larger rank → more adaptation capacity and cost.</p>}</LessonSection>

  <LessonSection id="qlora" onVisit={progress.markVisited} className={styles.scene}><h2>3. QLoRA: shrink the frozen base, train the adapters.</h2><div className={styles.grid3}>{[["quant","1 · Quantize base","Represent the frozen base at low precision for memory efficiency."],["freeze","2 · Freeze base","Base quantized weights are not the primary trainable update."],["adapter","3 · Train LoRA","Keep higher-precision trainable low-rank adapters/optimizer machinery as required by the method."]].map(([id,title,copy])=><button key={id} className={`${styles.panel} ${qloraSteps.includes(id)?styles.correct:""}`} onClick={()=>mark(id,qloraSteps,setQloraSteps,3,"adapt-qlora")}><b>{title}</b><p>{copy}</p></button>)}</div>{qloraDone&&<p className={styles.feedback}>✓ QLoRA is not “quantize everything and train every 4-bit weight normally.” The core idea is quantized frozen base + efficient trainable adapters.</p>}</LessonSection>

  <LessonSection id="adapters" onVisit={progress.markVisited} className={styles.scene}><h2>4. Adapters and domain fine-tuning are architectural choices about where adaptation lives.</h2><p>A legal-support company wants domain terminology without retraining a foundation model from scratch. Choose the most targeted option.</p>{[["scratch","Pretrain a new foundation model from random initialization"],["adapter","Train a domain adapter / PEFT layer on curated legal examples"],["nothing","Never adapt and never use retrieval"]].map(([id,text])=><button key={id} className={`${styles.choice} ${adapterChoice===id?(id==="adapter"?styles.correct:styles.wrong):""}`} onClick={()=>{setAdapterChoice(id);if(id==="adapter")progress.completeTask("adapt-adapters")}}>{text}</button>)}</LessonSection>

  <LessonSection id="distillation" onVisit={progress.markVisited} className={styles.scene}><h2>5. Distillation: teach a smaller student from a stronger teacher.</h2><div className={styles.teacher}><AiMascot variant="star" accent="#ffe05b" mood="happy" size={105} label="TEACHER"/><span className={styles.arrow}>→</span><AiMascot variant="tile" accent="#91e575" mood={teacherMix>60?"excited":"thinking"} size={82} label="STUDENT"/></div><div className={styles.control}><label>Teacher supervision / soft-target mix <b>{teacherMix}%</b></label><input type="range" min="0" max="100" value={teacherMix} onChange={e=>{setTeacherMix(+e.target.value);if(+e.target.value>=65)progress.completeTask("adapt-distill")}}/></div><div className={styles.grid2}><div className={styles.panel}><b>Toy student quality</b><div className={styles.meter}><i style={{width:`${studentQuality}%`}}/></div><p>{studentQuality}%</p></div><div className={styles.panel}><b>Toy serving cost</b><div className={styles.meter}><i style={{width:`${studentCost}%`}}/></div><p>{studentCost}% of teacher baseline</p></div></div><p>Distillation can use teacher logits, labels, generated examples or other supervision. It is not guaranteed to preserve every capability.</p></LessonSection>

  <LessonSection id="merging" onVisit={progress.markVisited} className={styles.scene}><h2>6. Model merging: blend checkpoints/deltas, then test for interference.</h2><div className={styles.control}><label>Mix toward Specialist B <b>{merge}%</b></label><input type="range" min="0" max="100" value={merge} onChange={e=>{setMerge(+e.target.value);setMergeTouched(true);if(+e.target.value>=35&&+e.target.value<=65)progress.completeTask("adapt-merge")}}/></div><div className={styles.grid2}><div className={styles.panel}><b>Skill A retained</b><div className={styles.meter}><i style={{width:`${mergeA}%`}}/></div><p>{mergeA}%</p></div><div className={styles.panel}><b>Skill B gained</b><div className={styles.meter}><i style={{width:`${mergeB}%`}}/></div><p>{mergeB}%</p></div></div>{mergeTouched&&<p className={styles.warning}>Merging is not guaranteed additive magic. Weight-space compatibility and task interference must be evaluated.</p>}</LessonSection>

  <LessonSection id="continual" onVisit={progress.markVisited} className={styles.scene}><h2>7. Continual learning can make yesterday's skill disappear.</h2><div className={styles.controls}><div className={styles.control}><label>Train on new domain <b>{newDomain}%</b></label><input type="range" min="0" max="100" value={newDomain} onChange={e=>{setNewDomain(+e.target.value);setContinualTouched(true)}}/></div><div className={styles.control}><label>Replay/retention mix <b>{replay}%</b></label><input type="range" min="0" max="100" value={replay} onChange={e=>{setReplay(+e.target.value);setContinualTouched(true);if(newDomain>65&&+e.target.value>35)progress.completeTask("adapt-continual")}}/></div></div><div className={styles.grid2}><div className={styles.panel}><b>Old capability</b><div className={styles.meter}><i style={{width:`${oldSkill}%`}}/></div><p>{Math.round(oldSkill)}%</p></div><div className={styles.panel}><b>New domain capability</b><div className={styles.meter}><i style={{width:`${newSkill}%`}}/></div><p>{Math.round(newSkill)}%</p></div></div>{continualTouched&&newDomain>60&&replay<20&&<p className={styles.warning}>Catastrophic forgetting: new optimization improved the new domain while degrading an old capability.</p>}</LessonSection>

  <LessonSection id="qat" onVisit={progress.markVisited} className={styles.scene}><h2>8. Quantization-aware training lets the model feel low precision before deployment.</h2><div className={styles.controls}><div className={styles.control}><label>Target precision <b>{bits}-bit</b></label><input type="range" min="4" max="16" step="4" value={bits} onChange={e=>setBits(+e.target.value)}/></div><button className={`${styles.button} ${qat?styles.correct:""}`} onClick={()=>{setQat(true);progress.completeTask("adapt-qat")}}>Enable fake-quant / QAT simulation</button></div><div className={styles.meter}><i style={{width:`${quantQuality}%`}}/></div><p>Toy retained quality: {quantQuality.toFixed(1)}%. QAT exposes training to simulated quantization effects so parameters can adapt before actual low-precision deployment.</p></LessonSection>

  <LessonSection id="explain" onVisit={progress.markVisited} className={`${styles.scene} ${styles.explain}`}><h2>9. Explain adaptation like an engineer.</h2><textarea value={explain} onChange={e=>setExplain(e.target.value)} placeholder="Explain full FT vs PEFT, LoRA rank, QLoRA, distillation, merging and catastrophic forgetting."/><button className={styles.button} onClick={submitExplain}>Check explanation</button>{explainFeedback&&<p className={styles.feedback}>{explainFeedback}</p>}</LessonSection>

  <section className={styles.quiz}><h2>Efficient adaptation mastery quiz</h2>{!unlocked?<div className={styles.locked}>🔒 Complete all nine adaptation rooms. {taskCount}/9 tasks · {readCount}/9 sections.</div>:<>{quiz.map((q,i)=><div className={styles.question} key={q[0]}><strong>{i+1}. {q[0]}</strong>{q[1].map((option,oi)=><button key={option} className={answers[i]===oi?styles.selected:""} onClick={()=>setAnswers(current=>({...current,[i]:oi}))}>{option}</button>)}{answers[i]!==undefined&&<small>{answers[i]===q[2]?"✓ Correct":`Correct: ${q[1][q[2]]}`}</small>}</div>)}<button className={styles.button} disabled={!quizComplete} onClick={()=>progress.saveQuiz(quizScore,quizScore>=7)}>Submit · {quizScore}/8</button>{quizComplete&&<p className={styles.feedback}>{quizScore>=7?"★ EFFICIENT ADAPTATION MASTERED":"Pass is 7/8. Review LoRA/QLoRA and continual learning."}</p>}</>}</section>
  <div className={styles.footer}><Link href="/lessons/posttraining-arena">← Post-Training Arena</Link><Link href="/lessons/module-7-capstone">Module 7 Boss Lab →</Link></div>
 </main>
}
