export type LessonStatus = "available" | "planned";
export type CourseLesson = { id:string; title:string; slug:string; shortTitle:string; status:LessonStatus; estimatedMinutes:number; };
export type CourseModule = { id:string; title:string; eyebrow:string; color:string; lessons:CourseLesson[]; };
export type LessonSectionDefinition = { id:string; title:string; taskId:string; };

export const courseModules: CourseModule[] = [
  { id:"module-1", title:"AI From Absolute Zero", eyebrow:"FOUNDATIONS", color:"#2357ff", lessons:[
    {id:"what-is-ai",title:"What is Artificial Intelligence?",shortTitle:"What is AI?",slug:"/lessons/what-is-ai",status:"available",estimatedMinutes:24},{id:"ai-vs-software",title:"AI vs normal software",shortTitle:"AI vs software",slug:"/lessons/ai-vs-software",status:"available",estimatedMinutes:28},{id:"ai-ml-dl",title:"AI vs Machine Learning vs Deep Learning",shortTitle:"AI / ML / DL",slug:"/lessons/ai-ml-dl",status:"available",estimatedMinutes:30},{id:"generative-vs-predictive",title:"Generative AI vs predictive AI",shortTitle:"Generative vs predictive",slug:"/lessons/generative-vs-predictive",status:"available",estimatedMinutes:30},{id:"symbolic-vs-neural",title:"Symbolic AI vs neural AI",shortTitle:"Symbolic vs neural",slug:"/lessons/symbolic-vs-neural",status:"available",estimatedMinutes:32},{id:"training-vs-inference",title:"Training vs inference",shortTitle:"Training vs inference",slug:"/lessons/training-vs-inference",status:"available",estimatedMinutes:34},{id:"models-algorithms-data",title:"Models, algorithms and datasets",shortTitle:"Model / algorithm / data",slug:"/lessons/models-algorithms-data",status:"available",estimatedMinutes:32},{id:"parameters",title:"Parameters vs hyperparameters",shortTitle:"Parameters",slug:"/lessons/parameters",status:"available",estimatedMinutes:30},{id:"features-labels",title:"Features and labels",shortTitle:"Features & labels",slug:"/lessons/features-labels",status:"available",estimatedMinutes:28},{id:"learning-types",title:"Supervised, unsupervised and self-supervised learning",shortTitle:"Learning types",slug:"/lessons/learning-types",status:"available",estimatedMinutes:32},{id:"reinforcement-learning",title:"Reinforcement learning",shortTitle:"Reinforcement learning",slug:"/lessons/reinforcement-learning",status:"available",estimatedMinutes:32},{id:"generalization",title:"Generalization, overfitting and underfitting",shortTitle:"Generalization",slug:"/lessons/generalization",status:"available",estimatedMinutes:30},{id:"splits-checkpoints",title:"Train / validation / test sets and checkpoints",shortTitle:"Splits & checkpoints",slug:"/lessons/splits-checkpoints",status:"available",estimatedMinutes:30},{id:"learning-across-time-tasks",title:"Online, transfer and representation learning",shortTitle:"Learning across time",slug:"/lessons/learning-across-time-tasks",status:"available",estimatedMinutes:34},{id:"scope-uncertainty",title:"Scope and uncertainty",shortTitle:"Scope & uncertainty",slug:"/lessons/scope-uncertainty",status:"available",estimatedMinutes:28},{id:"module-1-capstone",title:"Module 1 Boss Level",shortTitle:"Boss Level",slug:"/lessons/module-1-capstone",status:"available",estimatedMinutes:40}
  ]},
  {id:"module-2",title:"Neural Networks Without the Mystery",eyebrow:"NEURAL NETWORKS",color:"#ff5f57",lessons:[
    {id:"neural-networks",title:"What is a neural network?",shortTitle:"Neural networks",slug:"/lessons/neural-networks",status:"available",estimatedMinutes:36},{id:"weights-bias-activations",title:"Weights, bias and activation functions",shortTitle:"Weights / bias / activations",slug:"/lessons/weights-bias-activations",status:"available",estimatedMinutes:34},{id:"loss-gradients-backprop",title:"Loss, gradient descent and backpropagation",shortTitle:"Loss & backprop",slug:"/lessons/loss-gradients-backprop",status:"available",estimatedMinutes:38},{id:"sgd-batches-epochs",title:"SGD, batches and epochs",shortTitle:"SGD / batches / epochs",slug:"/lessons/sgd-batches-epochs",status:"available",estimatedMinutes:32},{id:"gradient-health-normalization",title:"Vanishing, exploding gradients and normalization",shortTitle:"Gradient health",slug:"/lessons/gradient-health-normalization",status:"available",estimatedMinutes:36},{id:"regularization-dropout",title:"Regularization and dropout",shortTitle:"Regularization & dropout",slug:"/lessons/regularization-dropout",status:"available",estimatedMinutes:32},{id:"residual-mlp",title:"Residual connections and MLPs",shortTitle:"Residuals & MLPs",slug:"/lessons/residual-mlp",status:"available",estimatedMinutes:34},{id:"cnn-rnn-lstm-attention",title:"CNN, RNN, LSTM and attention",shortTitle:"Architecture Museum",slug:"/lessons/cnn-rnn-lstm-attention",status:"available",estimatedMinutes:40},{id:"module-2-capstone",title:"Module 2 Boss Lab",shortTitle:"Boss Lab",slug:"/lessons/module-2-capstone",status:"available",estimatedMinutes:44}
  ]},
  {id:"module-3",title:"How Language Becomes Numbers",eyebrow:"LANGUAGE → VECTORS",color:"#9e6cff",lessons:[
    {id:"tokens-tokenization",title:"Tokens and tokenization",shortTitle:"Tokens & tokenization",slug:"/lessons/tokens-tokenization",status:"available",estimatedMinutes:36},{id:"tokenizer-families",title:"BPE, WordPiece and SentencePiece",shortTitle:"Tokenizer families",slug:"/lessons/tokenizer-families",status:"available",estimatedMinutes:32},{id:"embeddings-vectors",title:"Embeddings, vectors and semantic search",shortTitle:"Embeddings & vectors",slug:"/lessons/embeddings-vectors",status:"available",estimatedMinutes:38},{id:"module-3-capstone",title:"Module 3 Boss Lab",shortTitle:"Boss Lab",slug:"/lessons/module-3-capstone",status:"available",estimatedMinutes:42}
  ]},
  {id:"module-4",title:"Transformers Visually, Step by Step",eyebrow:"TRANSFORMERS",color:"#16a66a",lessons:[
    {id:"transformer-block-flow",title:"Transformer block flow",shortTitle:"Transformer block",slug:"/lessons/transformer-block-flow",status:"available",estimatedMinutes:42},{id:"positions-masks-cache",title:"Position, masks, KV cache and efficient attention",shortTitle:"Position & efficiency",slug:"/lessons/positions-masks-cache",status:"available",estimatedMinutes:40},{id:"encoder-decoder-architectures",title:"Encoder, decoder and cross-attention",shortTitle:"Transformer families",slug:"/lessons/encoder-decoder-architectures",status:"available",estimatedMinutes:38},{id:"module-4-capstone",title:"Module 4 Boss Lab",shortTitle:"Boss Lab",slug:"/lessons/module-4-capstone",status:"available",estimatedMinutes:44}
  ]},
  {id:"module-5",title:"How an LLM Actually Produces Text",eyebrow:"LLM GENERATION",color:"#5f88ff",lessons:[
    {id:"next-token-sampling",title:"Next-token prediction and sampling",shortTitle:"Next-token machine",slug:"/lessons/next-token-sampling",status:"available",estimatedMinutes:42},{id:"model-zoo-routing",title:"Model zoo, MoE and routing",shortTitle:"Model Zoo & routing",slug:"/lessons/model-zoo-routing",status:"available",estimatedMinutes:40},{id:"module-5-capstone",title:"Module 5 Boss Lab",shortTitle:"Boss Lab",slug:"/lessons/module-5-capstone",status:"available",estimatedMinutes:44}
  ]},
  {id:"module-6",title:"Context & Prompting",eyebrow:"CONTEXT ENGINEERING",color:"#b092ff",lessons:[
    {id:"context-backpack",title:"Context window and context engineering",shortTitle:"Context Backpack",slug:"/lessons/context-backpack",status:"available",estimatedMinutes:42},{id:"prompting-instruction-hierarchy",title:"Prompting and instruction hierarchy",shortTitle:"Prompting & hierarchy",slug:"/lessons/prompting-instruction-hierarchy",status:"available",estimatedMinutes:40},{id:"module-6-capstone",title:"Module 6 Boss Lab",shortTitle:"Incident Boss Lab",slug:"/lessons/module-6-capstone",status:"available",estimatedMinutes:44}
  ]},
  {id:"module-7",title:"Training & Post-Training",eyebrow:"TRAINING PIPELINE",color:"#ff9d62",lessons:[
    {id:"pretraining-factory",title:"Pretraining Factory",shortTitle:"Pretraining Factory",slug:"/lessons/pretraining-factory",status:"available",estimatedMinutes:44},
    {id:"posttraining-arena",title:"SFT, RLHF, DPO and RLAIF",shortTitle:"Post-Training Arena",slug:"/lessons/posttraining-arena",status:"available",estimatedMinutes:44},
    {id:"efficient-adaptation",title:"LoRA, QLoRA and efficient adaptation",shortTitle:"Efficient Adaptation",slug:"/lessons/efficient-adaptation",status:"available",estimatedMinutes:42},
    {id:"module-7-capstone",title:"Module 7 Boss Lab",shortTitle:"Training Boss Lab",slug:"/lessons/module-7-capstone",status:"available",estimatedMinutes:46}
  ]}
];

export const whatIsAiSections: readonly LessonSectionDefinition[]=[{id:"cold-open",title:"AI or not AI?",taskId:"ai-or-not"},{id:"core-idea",title:"The three moves",taskId:"three-moves"},{id:"rules-vs-learning",title:"Rules vs learning",taskId:"teach-machine"},{id:"layers",title:"Open the AI machine",taskId:"inspect-layers"},{id:"training-loop",title:"Train it",taskId:"training-loop"},{id:"probability",title:"AI makes guesses",taskId:"probability-lab"},{id:"family-tree",title:"AI / ML / DL",taskId:"family-tree"},{id:"explain-back",title:"Explain it back",taskId:"explain-back"}];
export const aiVsSoftwareSections: readonly LessonSectionDefinition[]=[{id:"be-the-computer",title:"Be the computer",taskId:"trace-rules"},{id:"same-input",title:"Same input, same result",taskId:"repeat-program"},{id:"rule-explosion",title:"When rules explode",taskId:"grow-rules"},{id:"learn-boundary",title:"Let examples shape behavior",taskId:"learn-boundary"},{id:"choose-engine",title:"Rules, ML or both?",taskId:"choose-engine"},{id:"hybrid-system",title:"Build a hybrid system",taskId:"hybrid-builder"},{id:"debug-it",title:"Debugging feels different",taskId:"debug-contrast"},{id:"boring-wins",title:"When boring software wins",taskId:"boring-wins"},{id:"explain-software",title:"Explain the difference",taskId:"explain-software"}];
export const aiMlDlSections: readonly LessonSectionDefinition[]=[{id:"nested-world",title:"Walk inside the hierarchy",taskId:"enter-zones"},{id:"sort-examples",title:"Put examples on the right level",taskId:"sort-spectrum"},{id:"symbolic-ai",title:"AI without machine learning",taskId:"solve-symbolic"},{id:"classic-ml",title:"Machine learning without deep learning",taskId:"nearest-neighbor"},{id:"deep-learning",title:"Why deep is deep",taskId:"layer-elevator"},{id:"tradeoffs",title:"Compare the three approaches",taskId:"compare-approaches"},{id:"build-hierarchy",title:"Build the nesting yourself",taskId:"hierarchy-build"},{id:"myths",title:"Destroy the common myths",taskId:"myth-flips"},{id:"explain-hierarchy",title:"Explain AI / ML / DL",taskId:"explain-hierarchy"}];
export const generativePredictiveSections: readonly LessonSectionDefinition[]=[{id:"two-machines",title:"One input, two jobs",taskId:"run-two-machines"},{id:"output-shapes",title:"What shape is the answer?",taskId:"sort-output-shapes"},{id:"token-factory",title:"Generate by predicting the next piece",taskId:"token-factory"},{id:"prediction-lab",title:"Build a predictive score",taskId:"predictive-score"},{id:"generation-lab",title:"Control a generator",taskId:"generation-controls"},{id:"same-model",title:"One model can serve different product jobs",taskId:"same-model-modes"},{id:"choose-pattern",title:"Generative, predictive or hybrid?",taskId:"choose-product-pattern"},{id:"failure-modes",title:"How the failures differ",taskId:"compare-failures"},{id:"explain-gen-pred",title:"Explain it back",taskId:"explain-gen-pred"}];
export const symbolicNeuralSections: readonly LessonSectionDefinition[]=[{id:"open-two-minds",title:"Open two kinds of intelligence",taskId:"inspect-two-minds"},{id:"knowledge-graph",title:"Reason through explicit symbols",taskId:"prove-symbolic-chain"},{id:"neural-learner",title:"Learn a pattern from examples",taskId:"train-neural-pattern"},{id:"break-symbolic",title:"Break the rule world",taskId:"repair-symbolic"},{id:"break-neural",title:"Poison the examples",taskId:"repair-neural"},{id:"inside-decision",title:"Inspect how decisions differ",taskId:"inspect-decisions"},{id:"tradeoff-console",title:"Compare strengths and costs",taskId:"compare-symbolic-neural"},{id:"hybrid-brain",title:"Build a neuro-symbolic pipeline",taskId:"build-hybrid-brain"},{id:"explain-symbolic-neural",title:"Explain it back",taskId:"explain-symbolic-neural"}];
export const trainingInferenceSections: readonly LessonSectionDefinition[]=[{id:"two-floors",title:"Training floor vs inference floor",taskId:"inspect-factory-floors"},{id:"training-line",title:"Run the training loop",taskId:"run-training-line"},{id:"optimizer-hill",title:"Walk downhill on loss",taskId:"optimize-weight"},{id:"checkpoint",title:"Freeze a checkpoint",taskId:"freeze-checkpoint"},{id:"inference-line",title:"Serve new requests",taskId:"serve-inference"},{id:"accidental-learning",title:"Catch accidental weight updates",taskId:"stop-accidental-learning"},{id:"compute-console",title:"Compare compute and latency",taskId:"compare-compute"},{id:"lifecycle",title:"Build the model lifecycle",taskId:"build-lifecycle"},{id:"explain-train-infer",title:"Explain it back",taskId:"explain-train-infer"}];
export const modelAlgorithmDataSections: readonly LessonSectionDefinition[]=[{id:"three-things",title:"Meet data, algorithm and model",taskId:"inspect-three-things"},{id:"assemble-pipeline",title:"Assemble the learning pipeline",taskId:"assemble-learning-pipeline"},{id:"same-algorithm",title:"Same algorithm, different datasets",taskId:"compare-datasets"},{id:"same-data",title:"Same data, different algorithms",taskId:"compare-algorithms"},{id:"inspect-artifacts",title:"Open the files",taskId:"classify-artifacts"},{id:"data-quality",title:"Change the data, change the model",taskId:"damage-dataset"},{id:"diagnose-layer",title:"Diagnose what changed",taskId:"diagnose-layer"},{id:"analogy-limits",title:"Use the analogy, then break it",taskId:"break-analogy"},{id:"explain-model-data",title:"Explain it back",taskId:"explain-model-data"}];
