"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { AiMascot } from "@/components/mascots/ai-mascot";
import { LessonProgressApi } from "@/components/course/lesson-shell";
import { DepthSwitch, LessonSection, TaskStamp } from "@/components/course/lesson-primitives";
import styles from "./pretraining-factory.module.css";

type Props={progress:LessonProgressApi};
const records=[
{id:"a",title:"Clean encyclopedia paragraph",quality:9,duplicate:false,contam:false},
{id:"b",title:"Public code documentation",quality:8,duplicate:false,contam:false},
{id:"c",title:"Spam keyword page",quality:1,duplicate:false,contam:false},
{id:"d",title:"Duplicate encyclopedia copy",quality:9,duplicate:true,contam:false},
{id:"e",title:"Held-out benchmark answer key",quality:10,duplicate:false,contam:true},
{id:"f",title:"Forum conversation",quality:6,duplicate:false,contam:false},
] as const;
const parallelCases=[
{text:"Replicate the full model on 8 GPUs; each GPU processes a different batch shard, then gradients are combined.",answer:"data"},
{text:"Split one huge matrix multiplication across multiple devices because the tensor itself is too large for one GPU.",answer:"tensor"},
{text:"Put early transformer blocks on one stage and later blocks on another; microbatches flow through the stages.",answer:"pipeline"},
{text:"The whole model cannot fit on one device, so different parameter/layer regions live on different devices.",answer:"model"},
] as const;
const quiz=[
["Pretraining primarily teaches a language model by…",["Optimizing a predictive objective over a very large corpus","Writing every fact into SQL","Giving only human preference labels","Running browser tools"],0],
["Deduplication matters because…",["Repeated examples can distort data weighting and memorization risk","It changes the tokenizer into a vector DB","It adds GPUs","It is the same as RLHF"],0],
["Evaluation contamination means…",["Held-out benchmark/test information leaked into training data or selection","A GPU overheated","The context window overflowed","A prompt used XML"],0],
["Cross-entropy loss rewards…",["Higher probability on the correct target token","Bigger parameter counts automatically","Longer prompts","More tool calls"],0],
["Data parallelism generally…",["Replicates the model and splits data/batches across workers","Splits one tensor multiply only","Splits layers only","Runs inference only"],0],
["Tensor parallelism generally…",["Partitions tensor operations/weights across devices","Duplicates webpages","Creates synthetic data","Is a tokenizer"],0],
["Pipeline parallelism generally…",["Splits model stages/layers across devices and pipelines microbatches","Only changes batch size","Only runs on CPUs","Is prompt caching"],0],
["A training checkpoint can contain…",["Model weights and often optimizer/training state needed to resume","Only the user prompt","Only test examples","Only tool schemas"],0],
] as const;

export function PretrainingFactoryLesson({progress}:Props){
 const [selected,setSelected]=useState<string[]>([]),[removed,setRemoved]=useState<string[]>([]),[contamFound,setContamFound]=useState(false),[synthetic,setSynthetic]=useState(10),[syntheticMoved,setSyntheticMoved]=useState(false),[correctProb,setCorrectProb]=useState(.18),[objectiveMoved,setObjectiveMoved]=useState(false),[clusterSteps,setClusterSteps]=useState(0),[parallel,setParallel]=useState<Record<number,string>>({}),[checkpoint,setCheckpoint]=useState(false),[crashed,setCrashed]=useState(false),[recovered,setRecovered]=useState(false),[explain,setExplain]=useState(""),[explainFeedback,setExplainFeedback]=useState(""),[answers,setAnswers]=useState<Record<number,number>>({});
 const accepted=records.filter(r=>selected.includes(r.id));
 const loss=-Math.log(Math.max(.001,correctProb));
 const goodCorpus=selected.includes("a")&&selected.includes("b")&&selected.includes("f")&&!selected.includes("c");
 const cleaningDone=removed.includes("c")&&removed.includes("d");
 const parallelDone=parallelCases.every((item,i)=>parallel[i]===item.answer);
 const taskIds=["pretrain-build-corpus","pretrain-clean-data","pretrain-find-contamination","pretrain-synthetic","pretrain-objective","pretrain-scale","pretrain-parallelism","pretrain-checkpoint","pretrain-explain"];
 const sectionIds=["corpus","cleaning","contamination","synthetic","objective","scale","parallelism","checkpoint","explain"];
 const taskCount=taskIds.filter(id=>progress.completedTasks[id]).length,readCount=sectionIds.filter(id=>progress.visitedSections.has(id)).length,unlocked=taskCount===9&&readCount===9;
 const quizScore=quiz.reduce((s,q,i)=>s+(answers[i]===q[2]?1:0),0),quizComplete=Object.keys(answers).length===quiz.length;
 const submitExplain=()=>{const t=explain.toLowerCase();const hits=["corpus","clean","duplicate","objective","loss","gradient","parallel","checkpoint"].filter(w=>t.includes(w)).length;if(explain.length<100||hits<4){setExplainFeedback("Go deeper: describe corpus preparation, the predictive loss, gradient-based optimization at scale and why checkpoints exist.");return;}setExplainFeedback("Strong. You described pretraining as a data + objective + distributed optimization system, not 'reading the internet.'");progress.completeTask("pretrain-explain")};
 return <main className={styles.root}>
  <section className={styles.hero}><div><span className={styles.eyebrow}>MODULE 7 · PRETRAINING FACTORY</span><h1>Before chat behavior, there is a gigantic prediction factory.</h1><p>Build the corpus, remove junk and duplicates, protect held-out evaluations, optimize next-token loss across a cluster, and save checkpoints so a week-long run is not one fragile process.</p><DepthSwitch value={progress.depth} onChange={progress.setDepth}/><TaskStamp done={taskCount===9}>{taskCount}/9 factory missions complete</TaskStamp></div><div className={styles.factory}><AiMascot variant="briefcase" accent="#69d7d0" mood={taskCount>2?"happy":"thinking"} size={100} label="DATA"/><AiMascot variant="tile" accent="#84df6e" mood={taskCount>5?"happy":"thinking"} size={100} label="GPU"/><AiMascot variant="star" accent="#ffe05b" mood={taskCount===9?"excited":"happy"} size={100} label="CKPT"/></div></section>

  <LessonSection id="corpus" onVisit={progress.markVisited} className={styles.scene}><h2>1. Build a corpus — do not just vacuum everything.</h2><div className={styles.grid3}>{records.filter(r=>!["d","e"].includes(r.id)).map(r=><button key={r.id} className={`${styles.panel} ${selected.includes(r.id)?styles.correct:""}`} onClick={()=>{const next=selected.includes(r.id)?selected.filter(x=>x!==r.id):[...selected,r.id];setSelected(next);if(next.includes("a")&&next.includes("b")&&next.includes("f")&&!next.includes("c"))progress.completeTask("pretrain-build-corpus")}}><b>{r.title}</b><p>quality signal: {r.quality}/10</p></button>)}</div>{goodCorpus&&<p className={styles.feedback}>✓ Good first pass: diverse useful text/code/conversation, obvious spam excluded.</p>}</LessonSection>

  <LessonSection id="cleaning" onVisit={progress.markVisited} className={styles.scene}><h2>2. Clean, filter and deduplicate.</h2><div className={styles.belt}>{records.filter(r=>["c","d","a"].includes(r.id)).map(r=><button className={styles.crate} key={r.id} onClick={()=>{const next=[...new Set([...removed,r.id])];setRemoved(next);if(next.includes("c")&&next.includes("d"))progress.completeTask("pretrain-clean-data")}}>{r.title}<br/><small>{r.duplicate?"duplicate":"unique"} · quality {r.quality}</small></button>)}</div><p>Click the spam and duplicate. Filtering changes what the optimizer sees; deduplication also reduces accidental over-weighting/memorization of repeated content.</p>{cleaningDone&&<p className={styles.feedback}>✓ Junk filtered, duplicate collapsed.</p>}</LessonSection>

  <LessonSection id="contamination" onVisit={progress.markVisited} className={styles.scene}><h2>3. Keep the exam out of the textbook.</h2><div className={styles.grid2}><div className={styles.panel}><b>TRAIN CORPUS</b><p>Data used to optimize weights.</p></div><button className={`${styles.panel} ${contamFound?styles.wrong:""}`} onClick={()=>{setContamFound(true);progress.completeTask("pretrain-find-contamination")}}><b>Suspicious file: benchmark_answers.json</b><p>Exact held-out benchmark questions + answers found inside crawl snapshot.</p></button></div>{contamFound&&<p className={styles.warning}>✓ Remove/quarantine it. If evaluation answers leak into training, the benchmark can overstate generalization.</p>}</LessonSection>

  <LessonSection id="synthetic" onVisit={progress.markVisited} className={styles.scene}><h2>4. Synthetic data is a lever, not free truth.</h2><div className={styles.control}><label>Synthetic share <b>{synthetic}%</b></label><input type="range" min="0" max="80" value={synthetic} onChange={e=>{setSynthetic(+e.target.value);setSyntheticMoved(true);if(+e.target.value>=20&&+e.target.value<=50)progress.completeTask("pretrain-synthetic")}}/></div><div className={styles.grid3}><div className={styles.panel}><b>Useful</b><p>Generate targeted examples, reasoning traces or rare formats.</p></div><div className={styles.panel}><b>Risk</b><p>Model-generated errors/biases can be amplified if synthetic quality is not controlled.</p></div><div className={styles.panel}><b>Mix</b><p>Source diversity, filtering and evaluation matter more than a magic percentage.</p></div></div>{syntheticMoved&&<p className={styles.feedback}>Current toy mix: {100-synthetic}% collected / {synthetic}% synthetic.</p>}</LessonSection>

  <LessonSection id="objective" onVisit={progress.markVisited} className={styles.scene}><h2>5. Pretraining objective: put probability on the target token.</h2><p>Context: <b>“The ocean is”</b> · target token: <b>“ blue”</b>. Cross-entropy for this one target is <code>-log(p_target)</code>.</p><div className={styles.control}><label>Probability assigned to correct token <b>{Math.round(correctProb*100)}%</b></label><input type="range" min="0.02" max="0.98" step="0.02" value={correctProb} onChange={e=>{setCorrectProb(+e.target.value);setObjectiveMoved(true);if(+e.target.value>.75)progress.completeTask("pretrain-objective")}}/></div><div className={styles.loss}><i style={{width:`${Math.min(100,loss/4*100)}%`}}/></div><p>Cross-entropy loss: <b>{loss.toFixed(3)}</b>. Higher probability on the correct target lowers loss.</p></LessonSection>

  <LessonSection id="scale" onVisit={progress.markVisited} className={styles.scene}><h2>6. Backprop still happens — now across a giant distributed system.</h2><div className={styles.cluster}>{Array.from({length:8},(_,i)=><button className={styles.gpu} key={i} onClick={()=>{const next=clusterSteps+1;setClusterSteps(next);if(next>=4)progress.completeTask("pretrain-scale")}}>GPU {i+1}<br/><small>microbatch {i%4+1}</small></button>)}</div><p>Each step is still forward → loss → gradients → optimizer update, but communication, synchronization, memory and throughput become infrastructure problems. Click at least four workers: {clusterSteps}/4.</p></LessonSection>

  <LessonSection id="parallelism" onVisit={progress.markVisited} className={styles.scene}><h2>7. Distributed training has multiple kinds of “parallel.”</h2>{parallelCases.map((item,i)=><div className={styles.panel} key={item.text}><p>{item.text}</p>{["data","tensor","pipeline","model"].map(choice=><button key={choice} className={`${styles.button} ${parallel[i]===choice?(choice===item.answer?styles.correct:styles.wrong):""}`} onClick={()=>{const next={...parallel,[i]:choice};setParallel(next);if(parallelCases.every((x,j)=>next[j]===x.answer))progress.completeTask("pretrain-parallelism")}}>{choice}</button>)}</div>)}{parallelDone&&<p className={styles.feedback}>✓ You separated batch replication, tensor partitioning and stage/layer partitioning. Real training stacks often combine them.</p>}</LessonSection>

  <LessonSection id="checkpoint" onVisit={progress.markVisited} className={styles.scene}><h2>8. Save state before something inevitably fails.</h2><div className={styles.grid3}><button className={`${styles.panel} ${checkpoint?styles.correct:""}`} onClick={()=>setCheckpoint(true)}><b>SAVE CHECKPOINT</b><p>Weights + training/optimizer state at step 420,000.</p></button><button className={`${styles.panel} ${crashed?styles.wrong:""}`} disabled={!checkpoint} onClick={()=>setCrashed(true)}><b>SIMULATE NODE FAILURE</b><p>One worker disappears during a long run.</p></button><button className={`${styles.panel} ${recovered?styles.correct:""}`} disabled={!crashed} onClick={()=>{setRecovered(true);progress.completeTask("pretrain-checkpoint")}}><b>RESTORE</b><p>Reload saved state instead of starting training from random initialization.</p></button></div>{recovered&&<p className={styles.feedback}>✓ Resume from checkpoint. Checkpoints are also useful for evaluation, rollback and later post-training.</p>}</LessonSection>

  <LessonSection id="explain" onVisit={progress.markVisited} className={`${styles.scene} ${styles.explain}`}><h2>9. Explain pretraining without saying “the model reads the internet.”</h2><textarea value={explain} onChange={e=>setExplain(e.target.value)} placeholder="Explain corpus preparation, next-token objective, cross-entropy, backprop at scale, parallelism and checkpoints."/><button className={styles.button} onClick={submitExplain}>Check explanation</button>{explainFeedback&&<p className={styles.feedback}>{explainFeedback}</p>}</LessonSection>

  <section className={styles.quiz}><h2>Pretraining mastery quiz</h2>{!unlocked?<div className={styles.locked}>🔒 Complete all nine factory stations first. {taskCount}/9 tasks · {readCount}/9 sections.</div>:<>{quiz.map((q,i)=><div className={styles.question} key={q[0]}><strong>{i+1}. {q[0]}</strong>{q[1].map((option,oi)=><button key={option} className={answers[i]===oi?styles.selected:""} onClick={()=>setAnswers(current=>({...current,[i]:oi}))}>{option}</button>)}{answers[i]!==undefined&&<small>{answers[i]===q[2]?"✓ Correct":`Correct: ${q[1][q[2]]}`}</small>}</div>)}<button className={styles.button} disabled={!quizComplete} onClick={()=>progress.saveQuiz(quizScore,quizScore>=7)}>Submit · {quizScore}/8</button>{quizComplete&&<p className={styles.feedback}>{quizScore>=7?"★ PRETRAINING FACTORY MASTERED":"Pass is 7/8. Review contamination and parallelism."}</p>}</>}</section>
  <div className={styles.footer}><Link href="/lessons/module-6-capstone">← Context module</Link><Link href="/lessons/posttraining-arena">Post-Training Arena →</Link></div>
 </main>
}
