"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { LessonProgressApi } from "@/components/course/lesson-shell";
import { LessonSection, TaskStamp } from "@/components/course/lesson-primitives";
import { CacheLayer, CacheStack } from "@/components/visualizations/cache-stack";
import { calculateCost, CostInputs, CostMeter, CostRates } from "@/components/visualizations/cost-meter";
import styles from "./module-23-capstone.module.css";

type Props={progress:LessonProgressApi};
const cacheLayers:CacheLayer[]=[{id:"prefix",title:"Prefix cache",stores:"reused stable system prefix",key:"model+prefix",hit:70,accent:"#78a7ff"},{id:"semantic",title:"Semantic cache",stores:"safe similar FAQ result",key:"meaning+scope",hit:35,accent:"#ffb773"},{id:"tool",title:"Tool result",stores:"fresh read-only API result",key:"tool+args+scope+TTL",hit:45,accent:"#ffe06b"},{id:"retrieval",title:"Retrieval cache",stores:"document IDs/ranks",key:"query+filters+index version",hit:58,accent:"#8fa4ff"}];
const baselineCases=[["input/output model billing","model"],["paid search API","tool"],["embedding refresh","embedding"],["self-hosted GPU seconds","gpu"]] as const;
const successCases=[["attempt cost $0.03, success 60%","$0.05"],["attempt cost $0.04, success 80%","$0.05"],["attempt cost $0.02, success 40%","$0.05"]] as const;
const routeCases=[["FAQ classification","small"],["standard support synthesis","mid"],["high-risk legal/financial reasoning","large"],["uncertain small-model result","escalate"]] as const;
const cacheCases=[["same long system policy prefix","prefix"],["semantically equivalent public FAQ within same version/scope","semantic"],["weather GET result for same city within 5-minute TTL","tool"],["same RAG query/filter against unchanged index","retrieval"]] as const;
const invalidateCases=[["policy version changes","invalidate"],["user/tenant scope changes","invalidate"],["semantic similarity falls below threshold","miss"],["weather TTL expires","invalidate"]] as const;
const budgetCases=[["max 10 model/tool steps","step"],["max $0.05 estimated task spend","cost"],["max 12k input + 2k output tokens","token"],["no retry ceiling","bad"]] as const;
const quiz=[
["Cost per successful task differs from cost per attempt when…",["Some attempts fail/retry","All attempts always succeed","Only CSS changes","No model is used"],0],
["Routing easy tasks to cheaper eligible models can…",["Reduce average cost while preserving quality targets if escalation exists","Guarantee all quality","Remove need for evals","Eliminate context"],0],
["Prefix cache is best for…",["Repeated eligible input prefixes","Arbitrary similar final answers","Destructive tool writes","User identity"],0],
["Semantic cache needs careful…",["Similarity threshold, user/scope/version boundaries","GPU fan speed only","Token IDs only","No invalidation"],0],
["Tool-result cache should consider…",["Side effects, freshness, auth scope and TTL","Only model temperature","Only prompt length","Only provider name"],0],
["Retrieval cache should include…",["Query/filters/index or source version in its identity","Only output text","Only GPU id","Only response temperature"],0],
["Agent budgets can limit…",["Steps/tokens/cost/time","Only fonts","Only weights","Only citations"],0],
["Increasing cache hit rate is always good even with stale results.",["True","False"],1],
["Retry loops can make a cheaper model more expensive per successful task.",["True","False"],0],
["Cost optimization without quality/success measurement can be misleading.",["True","False"],0],
["Self-hosted inference has no economic cost once GPU is purchased.",["True","False"],1],
["The useful target is often cost per successful, quality-acceptable outcome.",["True","False"],0],
] as const;

export function Module23CapstoneLesson({progress}:Props){
 const [inputs,setInputs]=useState<CostInputs>({inputTokens:8000,outputTokens:1200,cachedInputTokens:0,reasoningUnits:1500,embeddingCalls:1,toolCalls:3,gpuSeconds:0,retries:1}),[rates]=useState<CostRates>({inputPerM:3,outputPerM:12,cachedPerM:.75,reasoningPerK:.002,embeddingEach:.0002,toolEach:.002,gpuPerSecond:.0008}),[budget,setBudget]=useState(.05),[successRate,setSuccessRate]=useState(62),[baseline,setBaseline]=useState<Record<number,string>>({}),[success,setSuccess]=useState<Record<number,string>>({}),[route,setRoute]=useState<Record<number,string>>({}),[routeMode,setRouteMode]=useState(0),[cache,setCache]=useState<Record<number,string>>({}),[activeCache,setActiveCache]=useState("prefix"),[invalid,setInvalid]=useState<Record<number,string>>({}),[budgets,setBudgets]=useState<Record<number,string>>({}),[budgetLocked,setBudgetLocked]=useState(false),[explain,setExplain]=useState(""),[feedback,setFeedback]=useState(""),[answers,setAnswers]=useState<Record<number,number>>({});
 const tasks=["m23-baseline","m23-success","m23-route","m23-cache","m23-invalidate","m23-budget","m23-target","m23-explain"],sections=["baseline","success","route","cache","invalidate","budget","target","explain"];
 const done=tasks.filter(t=>progress.completedTasks[t]).length,read=sections.filter(s=>progress.visitedSections.has(s)).length,unlocked=done===8&&read===8;
 const score=quiz.reduce((n,q,i)=>n+(answers[i]===q[2]?1:0),0),quizDone=Object.keys(answers).length===quiz.length;
 const cost=useMemo(()=>calculateCost(inputs,rates),[inputs,rates]);const effectiveQuality=76+routeMode*5-Math.max(0,(5000-inputs.inputTokens)/900);const effectiveSuccess=Math.min(96,successRate+routeMode*6-Math.max(0,inputs.retries-2)*2);const costPerSuccess=cost.total/Math.max(.01,effectiveSuccess/100);const targetHit=costPerSuccess<=budget&&effectiveQuality>=84&&effectiveSuccess>=80;
 const solve=(current:Record<number,string>,setter:(next:Record<number,string>)=>void,cases:readonly (readonly [string,string])[],i:number,answer:string,task:string)=>{const next={...current,[i]:answer};setter(next);if(cases.every((x,j)=>next[j]===x[1]))progress.completeTask(task)};
 const submit=()=>{const t=explain.toLowerCase();const hits=["success","retry","route","cache","prefix","semantic","tool","retrieval","invalidate","budget","quality","cost"].filter(w=>t.includes(w)).length;if(explain.length<165||hits<9){setFeedback("Go deeper: explain cost-per-success, retry amplification, routing, cache selection/invalidation, budgets and quality/success guardrails.");return;}setFeedback("Strong. You optimized a quality-acceptable outcome rather than minimizing one isolated request price.");progress.completeTask("m23-explain")};
 return <main className={styles.root}>
  <section className={styles.hero}><div><span className={styles.eyebrow}>MODULE 23 · QUALITY UNDER BUDGET BOSS</span><h1>Get below $0.05 without making the agent stupid.</h1><p>Reduce real system spend through routing, caching and bounded retries while preserving quality ≥84 and success ≥80%.</p><TaskStamp done={done===8}>{done}/8 boss missions complete</TaskStamp></div><CostMeter inputs={inputs} rates={rates} budget={budget}/></section>

  <LessonSection id="baseline" onVisit={progress.markVisited} className={styles.scene}><h2>1. Measure every variable-cost layer first.</h2>{baselineCases.map((c,i)=><div className={styles.card} key={c[0]}><p>{c[0]}</p>{["model","tool","embedding","gpu"].map(answer=><button key={answer} className={`${styles.button} ${baseline[i]===answer?(answer===c[1]?styles.good:styles.bad):""}`} onClick={()=>solve(baseline,setBaseline,baselineCases,i,answer,"m23-baseline")}>{answer}</button>)}</div>)}<CostMeter inputs={inputs} rates={rates} budget={budget}/></LessonSection>

  <LessonSection id="success" onVisit={progress.markVisited} className={styles.scene}><h2>2. Convert attempt cost into cost per successful task.</h2>{successCases.map((c,i)=><div className={styles.card} key={c[0]}><p>{c[0]}</p>{["$0.05","$0.03","$0.08"].map(answer=><button key={answer} className={`${styles.button} ${success[i]===answer?(answer===c[1]?styles.good:styles.bad):""}`} onClick={()=>solve(success,setSuccess,successCases,i,answer,"m23-success")}>{answer}</button>)}</div>)}<label className={styles.slider}>Observed base success <b>{successRate}%</b><input type="range" min="40" max="95" value={successRate} onChange={e=>{setSuccessRate(+e.target.value);progress.completeTask("m23-success")}}/></label><div className={styles.big}><span>attempt ${cost.total.toFixed(4)}</span><b>→ ${costPerSuccess.toFixed(4)} / success</b></div></LessonSection>

  <LessonSection id="route" onVisit={progress.markVisited} className={styles.scene}><h2>3. Add a model cascade instead of paying premium price everywhere.</h2>{routeCases.map((c,i)=><div className={styles.card} key={c[0]}><p>{c[0]}</p>{["small","mid","large","escalate"].map(answer=><button key={answer} className={`${styles.button} ${route[i]===answer?(answer===c[1]?styles.good:styles.bad):""}`} onClick={()=>solve(route,setRoute,routeCases,i,answer,"m23-route")}>{answer}</button>)}</div>)}<div className={styles.routing}><button className={routeMode===0?styles.active:""} onClick={()=>setRouteMode(0)}>largest model always</button><button className={routeMode===1?styles.active:""} onClick={()=>{setRouteMode(1);setInputs(x=>({...x,inputTokens:7000,outputTokens:900,reasoningUnits:800}));progress.completeTask("m23-route")}}>small→mid escalation</button><button className={routeMode===2?styles.active:""} onClick={()=>{setRouteMode(2);setInputs(x=>({...x,inputTokens:6500,outputTokens:850,reasoningUnits:500}));progress.completeTask("m23-route")}}>small→mid→large by uncertainty</button></div></LessonSection>

  <LessonSection id="cache" onVisit={progress.markVisited} className={styles.scene}><h2>4. Choose the cache by what is being reused.</h2><CacheStack layers={cacheLayers} active={activeCache} onSelect={setActiveCache}/>{cacheCases.map((c,i)=><div className={styles.card} key={c[0]}><p>{c[0]}</p>{["prefix","semantic","tool","retrieval"].map(answer=><button key={answer} className={`${styles.button} ${cache[i]===answer?(answer===c[1]?styles.good:styles.bad):""}`} onClick={()=>{solve(cache,setCache,cacheCases,i,answer,"m23-cache");setActiveCache(answer)}}>{answer}</button>)}</div>)}<label className={styles.slider}>Cached stable prefix tokens <b>{inputs.cachedInputTokens}</b><input type="range" min="0" max={inputs.inputTokens} step="500" value={Math.min(inputs.cachedInputTokens,inputs.inputTokens)} onChange={e=>setInputs(x=>({...x,cachedInputTokens:+e.target.value}))}/></label></LessonSection>

  <LessonSection id="invalidate" onVisit={progress.markVisited} className={styles.scene}><h2>5. Cache correctness beats hit rate.</h2>{invalidateCases.map((c,i)=><div className={styles.card} key={c[0]}><p>{c[0]}</p>{["invalidate","miss"].map(answer=><button key={answer} className={`${styles.button} ${invalid[i]===answer?(answer===c[1]?styles.good:styles.bad):""}`} onClick={()=>solve(invalid,setInvalid,invalidateCases,i,answer,"m23-invalidate")}>{answer}</button>)}</div>)}</LessonSection>

  <LessonSection id="budget" onVisit={progress.markVisited} className={styles.scene}><h2>6. Bound autonomous spend before optimization.</h2>{budgetCases.map((c,i)=><div className={styles.card} key={c[0]}><p>{c[0]}</p>{["step","cost","token","bad"].map(answer=><button key={answer} className={`${styles.button} ${budgets[i]===answer?(answer===c[1]?styles.good:styles.bad):""}`} onClick={()=>solve(budgets,setBudgets,budgetCases,i,answer,"m23-budget")}>{answer}</button>)}</div>)}<div className={styles.sliders}><label>Task budget <b>${budget.toFixed(3)}</b><input type="range" min="0.02" max="0.1" step="0.005" value={budget} onChange={e=>{setBudget(+e.target.value);setBudgetLocked(false)}}/></label><label>Failed retries <b>{inputs.retries}</b><input type="range" min="0" max="5" value={inputs.retries} onChange={e=>{setInputs(x=>({...x,retries:+e.target.value}));setBudgetLocked(false)}}/></label></div><button className={styles.primary} onClick={()=>{setBudgetLocked(true);progress.completeTask("m23-budget")}}>Lock economic guardrails</button></LessonSection>

  <LessonSection id="target" onVisit={progress.markVisited} className={styles.scene}><h2>7. Hit all three targets at once.</h2><div className={styles.target}><span className={costPerSuccess<=budget?styles.pass:styles.fail}>cost / success <b>${costPerSuccess.toFixed(4)} ≤ ${budget.toFixed(3)}</b></span><span className={effectiveQuality>=84?styles.pass:styles.fail}>quality proxy <b>{effectiveQuality.toFixed(0)} ≥ 84</b></span><span className={effectiveSuccess>=80?styles.pass:styles.fail}>success proxy <b>{effectiveSuccess.toFixed(0)}% ≥ 80%</b></span></div><div className={styles.sliders}><label>Input/context tokens <b>{inputs.inputTokens}</b><input type="range" min="3000" max="12000" step="500" value={inputs.inputTokens} onChange={e=>setInputs(x=>({...x,inputTokens:+e.target.value,cachedInputTokens:Math.min(x.cachedInputTokens,+e.target.value)}))}/></label><label>Cached prefix <b>{inputs.cachedInputTokens}</b><input type="range" min="0" max={inputs.inputTokens} step="500" value={inputs.cachedInputTokens} onChange={e=>setInputs(x=>({...x,cachedInputTokens:+e.target.value}))}/></label></div><CostMeter inputs={inputs} rates={rates} budget={budget}/><button className={styles.primary} disabled={!targetHit||!budgetLocked} onClick={()=>progress.completeTask("m23-target")}>Ship this economic configuration</button></LessonSection>

  <LessonSection id="explain" onVisit={progress.markVisited} className={styles.scene}><h2>8. Explain why “use the cheapest model” is not an economics strategy.</h2><textarea className={styles.textarea} value={explain} onChange={e=>setExplain(e.target.value)} placeholder="Explain cost-per-success, retries, routing, cache selection/invalidation, budgets and quality/success guardrails."/><button className={styles.primary} onClick={submit}>Check explanation</button>{feedback&&<p className={styles.feedback}>{feedback}</p>}</LessonSection>

  <section className={styles.quiz}><h2>Module 23 mastery exam</h2>{!unlocked?<div className={styles.locked}>🔒 Complete all eight boss rooms. {done}/8 tasks · {read}/8 sections.</div>:<>{quiz.map((q,i)=><div className={styles.question} key={q[0]}><strong>{i+1}. {q[0]}</strong>{q[1].map((option,oi)=><button key={option} className={answers[i]===oi?styles.selected:""} onClick={()=>setAnswers(a=>({...a,[i]:oi}))}>{option}</button>)}{answers[i]!==undefined&&<small>{answers[i]===q[2]?"✓ Correct":`Correct: ${q[1][q[2]]}`}</small>}</div>)}<button className={styles.primary} disabled={!quizDone} onClick={()=>progress.saveQuiz(score,score>=10)}>Submit · {score}/12</button>{quizDone&&<p className={styles.feedback}>{score>=10?"★ AI ECONOMICS + CACHING MASTERED":"Pass is 10/12. Revisit cost-per-success and cache invalidation."}</p>}</>}</section>
  <div className={styles.footer}><Link href="/lessons/cache-lab">← Cache Lab</Link><Link href="/lessons/evals-lab">Evals & Observability →</Link></div>
 </main>
}
