"use client";

import { useState } from "react";
import styles from "./academy-signature-lab.module.css";
import { AiMascot } from "@/components/mascots/ai-mascot";

const BATCH5=new Set(["coding-agent-ekosistem","kada-koristiti-koji-agent","hermes-advanced","openclaw-advanced","coding-agenti-advanced","agent-framework-pregled","vibe-website","vibe-automation","vibe-product","vibe-marketing"]);
export function hasAcademySignatureLabBatch5(slug:string){return BATCH5.has(slug)}
export function AcademySignatureLabBatch5({slug,accent,onComplete}:{slug:string;accent:string;onComplete:(done:boolean)=>void}){
 if(slug==="coding-agent-ekosistem")return <CategoryLab accent={accent} onComplete={onComplete}/>;
 if(slug==="kada-koristiti-koji-agent")return <AgentChoiceLab accent={accent} onComplete={onComplete}/>;
 if(slug==="hermes-advanced")return <HermesAdvancedLab accent={accent} onComplete={onComplete}/>;
 if(slug==="openclaw-advanced")return <OpenClawAdvancedLab accent={accent} onComplete={onComplete}/>;
 if(slug==="coding-agenti-advanced")return <CodingAdvancedLab accent={accent} onComplete={onComplete}/>;
 if(slug==="agent-framework-pregled")return <FrameworkMapLab accent={accent} onComplete={onComplete}/>;
 if(slug==="vibe-website")return <VibePipelineLab accent={accent} onComplete={onComplete} kind="website"/>;
 if(slug==="vibe-automation")return <VibePipelineLab accent={accent} onComplete={onComplete} kind="automation"/>;
 if(slug==="vibe-product")return <VibePipelineLab accent={accent} onComplete={onComplete} kind="product"/>;
 if(slug==="vibe-marketing")return <MarketingLab accent={accent} onComplete={onComplete}/>;
 return null;
}
function Shell({accent,title,description,done,children}:{accent:string;title:string;description:string;done:boolean;children:React.ReactNode}){return <section className={styles.shell} style={{"--lab":accent} as React.CSSProperties}><header className={styles.head}><div><span>SIGNATURE LAB · AGENT SYSTEMS</span><h3>{title}</h3><p>{description}</p></div><AiMascot variant="star" accent={accent} mood={done?"excited":"thinking"} size={90} label={done?"DONE":"LAB"}/></header>{children}<div className={styles.doneBar} data-done={done}>{done?"✓ Sistem je složen":"Završi sve odluke"}</div></section>}
function SelectRows({rows,options,answers,setAnswers,onComplete}:{rows:{label:string;answer:string}[];options:string[];answers:Record<number,string>;setAnswers:(v:Record<number,string>)=>void;onComplete:(d:boolean)=>void}){return <div className={styles.toolList} style={{padding:20}}>{rows.map((row,i)=><div key={row.label} data-visible="true"><span>SCENARIO</span><b>{row.label}</b><select value={answers[i]??""} onChange={e=>{const next={...answers,[i]:e.target.value};setAnswers(next);onComplete(rows.every((r,j)=>next[j]===r.answer))}} style={{padding:8,borderRadius:8}}><option value="">Choose</option>{options.map(o=><option key={o}>{o}</option>)}</select></div>)}</div>}
function CategoryLab({accent,onComplete}:{accent:string;onComplete:(d:boolean)=>void}){const rows=[{label:"Cursor / Windsurf",answer:"Editor copilot"},{label:"Codex / Claude Code / Aider",answer:"Coding agent"},{label:"v0 / Lovable / Bolt",answer:"Product builder"},{label:"OpenHands / SWE-agent",answer:"Autonomous coding"}];const options=["Editor copilot","Coding agent","Product builder","Autonomous coding"];const[a,setA]=useState<Record<number,string>>({});const done=rows.every((r,i)=>a[i]===r.answer);return <Shell accent={accent} title="Razvrstaj alate po načinu rada, ne po hype-u." description="Brendovi se menjaju. Kategorija ti govori gde alat radi, kakav context ima i koliko izvršenja preuzima." done={done}><SelectRows rows={rows} options={options} answers={a} setAnswers={setA} onComplete={onComplete}/></Shell>}
function AgentChoiceLab({accent,onComplete}:{accent:string;onComplete:(d:boolean)=>void}){const rows=[{label:"Koordinacija web/fajlovi/alati",answer:"Hermes"},{label:"Kanali + gateway + automation",answer:"OpenClaw"},{label:"Implementacija u repository-ju",answer:"Codex"},{label:"Dubok terminal/codebase rad",answer:"Claude Code"},{label:"Brzi UI prototip",answer:"v0 / Lovable / Bolt"}];const options=["Hermes","OpenClaw","Codex","Claude Code","v0 / Lovable / Bolt"];const[a,setA]=useState<Record<number,string>>({});const done=rows.every((r,i)=>a[i]===r.answer);return <Shell accent={accent} title="Izaberi pravog agenta za posao." description="Ne traži jedan alat koji radi sve. Smanji trenje tako što odgovornost prati prirodu zadatka." done={done}><SelectRows rows={rows} options={options} answers={a} setAnswers={setA} onComplete={onComplete}/></Shell>}
function HermesAdvancedLab({accent,onComplete}:{accent:string;onComplete:(d:boolean)=>void}){const steps=["Persistent memory","Skill loaded","MCP discovered","Subtask delegated","Parallel result merged","Approval gate","Checkpoint saved"];const[done,setDone]=useState<string[]>([]);const complete=done.length===steps.length;return <Shell accent={accent} title="Pretvori jednog agenta u operativni sistem." description="Memory, skills, MCP, delegation, parallelism, approvals i checkpointing su različiti slojevi oko modela." done={complete}><div className={styles.responseChecklist} style={{padding:20}}>{steps.map(s=><button key={s} data-done={done.includes(s)} onClick={()=>{const next=done.includes(s)?done:[...done,s];setDone(next);onComplete(next.length===steps.length)}}><span>{done.includes(s)?"✓":"○"}</span>{s}</button>)}</div></Shell>}
function OpenClawAdvancedLab({accent,onComplete}:{accent:string;onComplete:(d:boolean)=>void}){const rows=[{label:"Slack support question",answer:"Support agent"},{label:"Scheduled morning brief",answer:"Briefing agent"},{label:"Write action with customer impact",answer:"Human approval"},{label:"Primary agent unavailable",answer:"Fallback agent"}];const options=["Support agent","Briefing agent","Human approval","Fallback agent"];const[a,setA]=useState<Record<number,string>>({});const done=rows.every((r,i)=>a[i]===r.answer);return <Shell accent={accent} title="Rutiraj task kroz gateway, fallback i approval." description="Advanced gateway mora da sačuva session continuity i bezbedan status kroz različite kanale." done={done}><SelectRows rows={rows} options={options} answers={a} setAnswers={setA} onComplete={onComplete}/></Shell>}
function CodingAdvancedLab({accent,onComplete}:{accent:string;onComplete:(d:boolean)=>void}){const steps=["Issue + acceptance criteria","Branch","Plan","Tests first","Multi-file implementation","Full test suite","Independent review","PR"];const[index,setIndex]=useState(0);const done=index===steps.length;return <Shell accent={accent} title="Vodi veliki repository bez haotičnih izmena." description="Issue → branch → plan → test → implement → regression → review → PR." done={done}><div className={styles.pipeline} style={{gridTemplateColumns:"repeat(4,1fr)"}}>{steps.map((s,i)=><button key={s} data-state={i<index?"done":i===index?"active":"waiting"} onClick={()=>{if(i===index){const n=index+1;setIndex(n);onComplete(n===steps.length)}}}><span>{i<index?"✓":i+1}</span><b>{s}</b><small>{i===index?"NEXT":""}</small></button>)}</div></Shell>}
function FrameworkMapLab({accent,onComplete}:{accent:string;onComplete:(d:boolean)=>void}){const rows=[{label:"LangGraph / CrewAI / AutoGen",answer:"Orchestration"},{label:"OpenAI Agents SDK / Google ADK / PydanticAI",answer:"Agent SDK"},{label:"OpenHands / SWE-agent / Aider",answer:"Coding agents"},{label:"Composio / n8n / Dify",answer:"Tool & automation"},{label:"Vapi / LiveKit / Pipecat",answer:"Voice"}];const options=["Orchestration","Agent SDK","Coding agents","Tool & automation","Voice"];const[a,setA]=useState<Record<number,string>>({});const done=rows.every((r,i)=>a[i]===r.answer);return <Shell accent={accent} title="Napravi mentalnu mapu framework ekosistema." description="Ne uči API svakog brenda. Razumi koju arhitektonsku ulogu alat preuzima." done={done}><SelectRows rows={rows} options={options} answers={a} setAnswers={setA} onComplete={onComplete}/></Shell>}
const pipelines={website:["Ideja","Agent brief","Struktura","Dizajn","Implementacija","GitHub","Deployment","Live test"],automation:["Problem","API / webhook","n8n workflow","AI agent","MCP / integracija","Approval","Result readback"],product:["Requirements","Agent plan","UI","Backend","Database","Authentication","Tests","Deployment"]} as const;
function VibePipelineLab({accent,onComplete,kind}:{accent:string;onComplete:(d:boolean)=>void;kind:keyof typeof pipelines}){const steps=[...pipelines[kind]];const[index,setIndex]=useState(0);const done=index===steps.length;return <Shell accent={accent} title={`Vibe ${kind}: od ideje do dokaza.`} description="Brzina dolazi iz jasnog pipeline-a, ne iz preskakanja testova i deployment provere." done={done}><div className={styles.pipeline} style={{gridTemplateColumns:"repeat(4,1fr)"}}>{steps.map((s,i)=><button key={s} data-state={i<index?"done":i===index?"active":"waiting"} onClick={()=>{if(i===index){const n=index+1;setIndex(n);onComplete(n===steps.length)}}}><span>{i<index?"✓":i+1}</span><b>{s}</b><small>{i===index?"RUN":""}</small></button>)}</div></Shell>}
function MarketingLab({accent,onComplete}:{accent:string;onComplete:(d:boolean)=>void}){const checks=["Brand context","Target audience","Market research sources","Messaging","SEO intent","Fact check","Link check","CTA check"];const[done,setDone]=useState<string[]>([]);const complete=done.length===checks.length;return <Shell accent={accent} title="AI marketing bez haluciniranih činjenica i generičnog tona." description="Agent ubrzava research/content execution, ali brand context, source verification, linkovi i CTA moraju da prođu kontrolu." done={complete}><div className={styles.responseChecklist} style={{padding:20}}>{checks.map(c=><button key={c} data-done={done.includes(c)} onClick={()=>{const n=done.includes(c)?done:[...done,c];setDone(n);onComplete(n.length===checks.length)}}><span>{done.includes(c)?"✓":"○"}</span>{c}</button>)}</div></Shell>}
