"use client";

import { useState } from "react";
import { AiMascot } from "@/components/mascots/ai-mascot";
import styles from "./academy-signature-lab.module.css";

const BATCH6=new Set(["kako-rade-digitalni-projekti","fajlovi-folderi-struktura","sta-je-github","razgovor-sa-coding-agentom","codex-development-tim","vibe-coding-od-ideje-do-live","ai-agenti-za-development","content-type-i-headers","sta-je-n8n","sta-je-mcp"]);
export function hasAcademySignatureLabBatch6(slug:string){return BATCH6.has(slug)}
export function AcademySignatureLabBatch6({slug,accent,onComplete}:{slug:string;accent:string;onComplete:(d:boolean)=>void}){
 if(slug==="kako-rade-digitalni-projekti")return <DigitalLayers accent={accent} onComplete={onComplete}/>;
 if(slug==="fajlovi-folderi-struktura")return <ProjectStructure accent={accent} onComplete={onComplete}/>;
 if(slug==="sta-je-github")return <GitVsGitHub accent={accent} onComplete={onComplete}/>;
 if(slug==="razgovor-sa-coding-agentom")return <CodingBrief accent={accent} onComplete={onComplete}/>;
 if(slug==="codex-development-tim")return <CodexTeam accent={accent} onComplete={onComplete}/>;
 if(slug==="vibe-coding-od-ideje-do-live")return <VibeLifecycle accent={accent} onComplete={onComplete}/>;
 if(slug==="ai-agenti-za-development")return <DevAgentArchitecture accent={accent} onComplete={onComplete}/>;
 if(slug==="content-type-i-headers")return <HeadersLab accent={accent} onComplete={onComplete}/>;
 if(slug==="sta-je-n8n")return <N8nAnatomy accent={accent} onComplete={onComplete}/>;
 if(slug==="sta-je-mcp")return <McpAnatomy accent={accent} onComplete={onComplete}/>;
 return null;
}
function Shell({accent,title,description,done,children}:{accent:string;title:string;description:string;done:boolean;children:React.ReactNode}){return <section className={styles.shell} style={{"--lab":accent} as React.CSSProperties}><header className={styles.head}><div><span>SIGNATURE LAB · FOUNDATIONS</span><h3>{title}</h3><p>{description}</p></div><AiMascot variant="tile" accent={accent} mood={done?"excited":"thinking"} size={90} label={done?"DONE":"LAB"}/></header>{children}<div className={styles.doneBar} data-done={done}>{done?"✓ Mentalni model potvrđen":"Završi simulator"}</div></section>}
function Sequence({steps,index,setIndex,onComplete}:{steps:string[];index:number;setIndex:(n:number)=>void;onComplete:(d:boolean)=>void}){return <div className={styles.pipeline} style={{gridTemplateColumns:`repeat(${Math.min(steps.length,5)},1fr)`}}>{steps.map((s,i)=><button key={s} data-state={i<index?"done":i===index?"active":"waiting"} onClick={()=>{if(i===index){const n=index+1;setIndex(n);onComplete(n===steps.length)}}}><span>{i<index?"✓":i+1}</span><b>{s}</b><small>{i===index?"NEXT":""}</small></button>)}</div>}
function DigitalLayers({accent,onComplete}:{accent:string;onComplete:(d:boolean)=>void}){const layers=["Browser / UI","Frontend","Backend / API","Database","Production server"];const[index,setIndex]=useState(0);return <Shell accent={accent} title="Prati jedan klik kroz ceo digitalni sistem." description="UI ne čuva sve podatke i database ne živi u browseru. Klik putuje kroz više odgovornosti." done={index===layers.length}><Sequence steps={layers} index={index} setIndex={setIndex} onComplete={onComplete}/>{index>=3&&<p className={styles.callout}>Browser request → frontend code → API/backend → database → response → UI update.</p>}</Shell>}
function ProjectStructure({accent,onComplete}:{accent:string;onComplete:(d:boolean)=>void}){const rows=[{label:"package.json",answer:"Dependencies + scripts"},{label:"README.md",answer:"Setup + purpose"},{label:".gitignore",answer:"Exclude generated/secrets"},{label:".env",answer:"Secrets / environment"},{label:"app/ or src/",answer:"Source code"}];const options=rows.map(r=>r.answer);const[a,setA]=useState<Record<number,string>>({});const done=rows.every((r,i)=>a[i]===r.answer);return <Shell accent={accent} title="Pročitaj projekat pre nego što ga menjaš." description="Folder struktura ti govori gde je source, config, documentation i šta nikada ne sme da ode na GitHub." done={done}><div className={styles.toolList} style={{padding:20}}>{rows.map((r,i)=><div key={r.label} data-visible="true"><span>FILE</span><b>{r.label}</b><select value={a[i]??""} onChange={e=>{const n={...a,[i]:e.target.value};setA(n);onComplete(rows.every((x,j)=>n[j]===x.answer))}} style={{padding:8,borderRadius:8}}><option value="">What is it?</option>{options.map(o=><option key={o}>{o}</option>)}</select></div>)}</div></Shell>}
function GitVsGitHub({accent,onComplete}:{accent:string;onComplete:(d:boolean)=>void}){const rows=[{label:"commit",answer:"Git"},{label:"local branch",answer:"Git"},{label:"pull request",answer:"GitHub"},{label:"issue",answer:"GitHub"},{label:"remote repository hosting",answer:"GitHub"}];const[a,setA]=useState<Record<number,string>>({});const done=rows.every((r,i)=>a[i]===r.answer);return <Shell accent={accent} title="Odvoji Git od GitHub-a." description="Git je version-control sistem koji može da radi lokalno; GitHub hostuje remote repository i timski workflow." done={done}><div className={styles.toolList} style={{padding:20}}>{rows.map((r,i)=><div key={r.label} data-visible="true"><span>CONCEPT</span><b>{r.label}</b><select value={a[i]??""} onChange={e=>{const n={...a,[i]:e.target.value};setA(n);onComplete(rows.every((x,j)=>n[j]===x.answer))}} style={{padding:8,borderRadius:8}}><option value="">Choose</option><option>Git</option><option>GitHub</option></select></div>)}</div></Shell>}
function CodingBrief({accent,onComplete}:{accent:string;onComplete:(d:boolean)=>void}){const parts=["Goal","Current state","Files/scope","Constraints","Expected result","Test / verification"];const[selected,setSelected]=useState<string[]>([]);const done=selected.length===parts.length;return <Shell accent={accent} title="Napravi engineering brief koji agent ne mora da pogađa." description="Dobar task definiše cilj i granice pre nego što coding agent otvori editor." done={done}><div className={styles.responseChecklist} style={{padding:20}}>{parts.map(p=><button key={p} data-done={selected.includes(p)} onClick={()=>{const n=selected.includes(p)?selected:[...selected,p];setSelected(n);onComplete(n.length===parts.length)}}><span>{selected.includes(p)?"✓":"○"}</span>{p}</button>)}</div></Shell>}
function CodexTeam({accent,onComplete}:{accent:string;onComplete:(d:boolean)=>void}){const steps=["Read repository","Explain current behavior","Plan change","Implement","Show diff","Run tests","Fix regression","Final verification"];const[index,setIndex]=useState(0);return <Shell accent={accent} title="Codex kao član tima, ne autocomplete." description="Agent prvo gradi model codebase-a, zatim menja, pokazuje diff i dokazuje rezultat testom." done={index===steps.length}><Sequence steps={steps} index={index} setIndex={setIndex} onComplete={onComplete}/></Shell>}
function VibeLifecycle({accent,onComplete}:{accent:string;onComplete:(d:boolean)=>void}){const steps=["Idea","Requirements","Project structure","Design","Implementation","Tests","Commit","Push","Deploy","Public check","Iteration"];const[index,setIndex]=useState(0);return <Shell accent={accent} title="Vibe coding nije 'prompt → gotovo'." description="Brz product loop i dalje ima requirements, test, Git, deployment i javni readback." done={index===steps.length}><Sequence steps={steps} index={index} setIndex={setIndex} onComplete={onComplete}/></Shell>}
function DevAgentArchitecture({accent,onComplete}:{accent:string;onComplete:(d:boolean)=>void}){const blocks=["Model","Context","Tools","Memory","Permissions","Agent loop","Human approval","Verification"];const[added,setAdded]=useState<string[]>([]);const done=added.length===blocks.length;return <Shell accent={accent} title="Sastavi development agenta oko modela." description="Chat model postaje agent tek kada dobije environment, tool loop, state/context granice i način provere." done={done}><div className={styles.n8nFlow} style={{flexWrap:"wrap"}}>{blocks.map((b,i)=><button key={b} onClick={()=>{const n=added.includes(b)?added:[...added,b];setAdded(n);onComplete(n.length===blocks.length)}} style={{minWidth:140,flex:"1 1 150px",border:"2px solid #17191d",borderRadius:14,padding:14,background:added.includes(b)?"#d9f7e6":"#f4f4f2",cursor:"pointer"}}><span>{added.includes(b)?"✓":i+1}</span><b style={{display:"block",marginTop:18}}>{b}</b></button>)}</div></Shell>}
function HeadersLab({accent,onComplete}:{accent:string;onComplete:(d:boolean)=>void}){const [content,setContent]=useState("text/plain");const [auth,setAuth]=useState(false);const [accept,setAccept]=useState(false);const valid=content==="application/json"&&auth&&accept;return <Shell accent={accent} title="Isti body, drugačiji headers — potpuno drugačiji rezultat." description="Server mora da zna kako da parsira body, ko šalje zahtev i kakav response klijent očekuje." done={valid}><div className={styles.apiBuilder}><div className={styles.apiColumns}><div><span>HEADERS</span><select value={content} onChange={e=>{setContent(e.target.value);onComplete(e.target.value==="application/json"&&auth&&accept)}} style={{width:"100%",padding:10,margin:"10px 0",borderRadius:8}}><option>text/plain</option><option>application/json</option></select><button className={styles.actionButton} style={{margin:"8px 0"}} onClick={()=>{setAuth(true);onComplete(content==="application/json"&&accept)}}>{auth?"✓ Authorization: Bearer TOKEN":"Add Authorization"}</button><button className={styles.actionButton} style={{margin:"8px 0"}} onClick={()=>{setAccept(true);onComplete(content==="application/json"&&auth)}}>{accept?"✓ Accept: application/json":"Add Accept"}</button></div><div><span>SERVER RESULT</span><pre>{content!=="application/json"?"415 / parser cannot read JSON body":!auth?"401 / missing identity":!accept?"200 but response format unclear":"200 OK\n{\"status\":\"accepted\"}"}</pre></div></div></div></Shell>}
function N8nAnatomy({accent,onComplete}:{accent:string;onComplete:(d:boolean)=>void}){const rows=[{label:"Webhook",answer:"Trigger"},{label:"HTTP Request",answer:"Action"},{label:"{{$json.email}}",answer:"Expression"},{label:"Google OAuth",answer:"Credentials"},{label:"execution #481",answer:"Execution"}];const options=["Trigger","Action","Expression","Credentials","Execution"];const[a,setA]=useState<Record<number,string>>({});const done=rows.every((r,i)=>a[i]===r.answer);return <Shell accent={accent} title="Rastavi n8n workflow na njegove osnovne delove." description="Trigger pokreće, action radi, credentials daju pristup, expression mapira podatke, execution pokazuje šta se stvarno desilo." done={done}><div className={styles.toolList} style={{padding:20}}>{rows.map((r,i)=><div key={r.label} data-visible="true"><span>n8n</span><b>{r.label}</b><select value={a[i]??""} onChange={e=>{const n={...a,[i]:e.target.value};setA(n);onComplete(rows.every((x,j)=>n[j]===x.answer))}} style={{padding:8,borderRadius:8}}><option value="">Choose</option>{options.map(o=><option key={o}>{o}</option>)}</select></div>)}</div></Shell>}
function McpAnatomy({accent,onComplete}:{accent:string;onComplete:(d:boolean)=>void}){const steps=["AI host","MCP client","MCP server","Capability discovery","Tool call","Real application","Tool result"];const[index,setIndex]=useState(0);return <Shell accent={accent} title="Prati capability od modela do stvarne aplikacije i nazad." description="MCP standardizuje priključak, ali model i dalje ne izvršava spoljnu akciju sam — runtime/server to radi." done={index===steps.length}><Sequence steps={steps} index={index} setIndex={setIndex} onComplete={onComplete}/></Shell>}
