"use client";

import { AiMascot } from "@/components/mascots/ai-mascot";
import styles from "./cost-meter.module.css";

export type CostInputs={inputTokens:number;outputTokens:number;cachedInputTokens:number;reasoningUnits:number;embeddingCalls:number;toolCalls:number;gpuSeconds:number;retries:number};
export type CostRates={inputPerM:number;outputPerM:number;cachedPerM:number;reasoningPerK:number;embeddingEach:number;toolEach:number;gpuPerSecond:number};
export function calculateCost(input:CostInputs,rates:CostRates){const multiplier=1+Math.max(0,input.retries);const model=((input.inputTokens-input.cachedInputTokens)*rates.inputPerM/1e6+input.cachedInputTokens*rates.cachedPerM/1e6+input.outputTokens*rates.outputPerM/1e6+input.reasoningUnits*rates.reasoningPerK/1000)*multiplier;const embeddings=input.embeddingCalls*rates.embeddingEach;const tools=input.toolCalls*rates.toolEach*multiplier;const gpu=input.gpuSeconds*rates.gpuPerSecond;return{model,embeddings,tools,gpu,total:model+embeddings+tools+gpu}}
export function CostMeter({inputs,rates,budget=.05}:{inputs:CostInputs;rates:CostRates;budget?:number}){const cost=calculateCost(inputs,rates);const over=cost.total>budget;return <div className={styles.wrap}><div className={styles.head}><AiMascot variant="briefcase" accent={over?"#ff8d8d":"#78dca8"} mood={over?"wow":"excited"} size={72} label={over?"OVER":"COST"}/><div><span>cost / task</span><b>${cost.total.toFixed(4)}</b><small>budget ${budget.toFixed(3)}</small></div></div><div className={styles.parts}><span><i style={{width:`${cost.total?cost.model/cost.total*100:0}%`}}/>model <b>${cost.model.toFixed(4)}</b></span><span><i style={{width:`${cost.total?cost.embeddings/cost.total*100:0}%`}}/>embeddings <b>${cost.embeddings.toFixed(4)}</b></span><span><i style={{width:`${cost.total?cost.tools/cost.total*100:0}%`}}/>tools <b>${cost.tools.toFixed(4)}</b></span><span><i style={{width:`${cost.total?cost.gpu/cost.total*100:0}%`}}/>GPU <b>${cost.gpu.toFixed(4)}</b></span></div><p>Teaching meter: rates are user-configurable toy values. Real pricing, billing units and cache discounts vary by provider/model/service and change over time.</p></div>}
