"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { LessonProgressApi } from "@/components/course/lesson-shell";
import { LessonSection, TaskStamp } from "@/components/course/lesson-primitives";
import { InferenceFactory } from "@/components/visualizations/inference-factory";
import styles from "./module-22-capstone.module.css";

type Props={progress:LessonProgressApi};
const incidentCases=[
["Queue growing from 2 → 18 requests","capacity"],["TTFT rises from 350ms → 2.4s","latency"],["GPU 98% while queue keeps growing","overload"],["Output quality suddenly wrong while serving metrics normal","not-capacity"],
] as const;
const shardCases=[
["Model weights do not fit one GPU, split layer tensor math across 4 GPUs","tensor"],["Place different layer stages on separate GPUs","pipeline"],["Need more independent request capacity with model already fitting one GPU","replica"],
] as const;
const cacheCases=[
["Many requests share the same long system prefix","prefix-cache-good"],["Every request has totally unique prefix","prefix-cache-low"],["Cache hit avoids some repeated prefix/prefill work when runtime supports it","true"],["Prefix cache means final answers are reused regardless of user query","false"],
] as const;
const specCases=[
["Draft model fast + fairly accurate relative to target","good"],["Draft model slow and target rejects almost everything","bad"],["Target model still verifies proposed tokens","true"],
] as const;
const sloCases=[
["TTFT < 800ms","latency-slo"],["Decode > 35 tok/s","decode-slo"],["Serve >= 28 req/s","throughput-slo"],["Queue remains bounded under expected load","capacity-slo"],
] as const;
const quiz=[
["A growing queue under steady traffic usually means…",["Demand exceeds immediate capacity/scheduling throughput","The model is training","JSON is invalid","The tokenizer disappeared"],0],
["Increasing batch size can improve…",["Accelerator throughput, with latency trade-offs","Training data quality","OAuth security","Source credibility"],0],
["Adding replicas primarily helps…",["Horizontal request-serving capacity","Fit one oversized tensor onto one GPU","Tokenize text","Graph traversal"],0],
["Tensor parallelism primarily helps…",["Split one model's tensor/layer computation across devices","Create independent full replicas","Increase web search credibility","Store session cookies"],0],
["Prefix/prompt caching can reduce…",["Repeated work for shared input prefixes when supported","All decode work for every unique answer","Need for model weights","Need for authentication"],0],
["Cache hit rate means…",["Fraction of eligible accesses served from cache rather than recomputed/missed","Model accuracy","GPU clock speed","Number of users"],0],
["Speculative decoding requires…",["Draft proposal plus target verification","Only a bigger prompt","Only more replicas","Only more context"],0],
["TTFT measures…",["Request-to-first-token latency","Inter-token delay only","Total training time","File download speed"],0],
["ITL measures…",["Latency between output tokens after generation starts","Time to load weights","Token price","Queue length"],0],
["High utilization + bounded queue + SLO-compliant latency can be healthy.",["True","False"],0],
["High utilization + exploding queue should be interpreted as success because the GPU is busy.",["True","False"],1],
["Production capacity should be evaluated with workload distributions, not only one benchmark prompt.",["True","False"],0],
] as const;

export function Module22CapstoneLesson({progress}:Props){
 const [incident,setIncident]=useState<Record<number,string>>({}),[arrival,setArrival]=useState(32),[batch,setBatch]=useState(2),[replicas,setReplicas]=useState(1),[batchLocked,setBatchLocked]=useState(false),[scaleLocked,setScaleLocked]=useState(false),[shard,setShard]=useState<Record<number,string>>({}),[tp,setTp]=useState(1),[cache,setCache]=useState<Record<number,string>>({}),[cacheHit,setCacheHit]=useState(15),[spec,setSpec]=useState<Record<number,string>>({}),[acceptance,setAcceptance]=useState(35),[slo,setSlo]=useState<Record<number,string>>({}),[explain,setExplain]=useState(""),[feedback,setFeedback]=useState(""),[answers,setAnswers]=useState<Record<number,number>>({});
 const tasks=["m22-incident","m22-batch","m22-scale","m22-shard","m22-cache","m22-spec","m22-slo","m22-explain"],sections=["incident","batch","scale","shard","cache","spec","slo","explain"];
 const done=tasks.filter(t=>progress.completedTasks[t]).length,read=sections.filter(s=>progress.visitedSections.has(s)).length,unlocked=done===8&&read===8;
 const score=quiz.reduce((n,q,i)=>n+(answers[i]===q[2]?1:0),0),quizDone=Object.keys(answers).length===quiz.length;
 const solve=(current:Record<number,string>,setter:(next:Record<number,string>)=>void,cases:readonly (readonly [string,string])[],i:number,answer:string,task:string)=>{const next={...current,[i]:answer};setter(next);if(cases.every((x,j)=>next[j]===x[1]))progress.completeTask(task)};
 const metrics=useMemo(()=>{const perReplica=6+batch*1.65;const capacity=replicas*perReplica;const pressure=arrival/Math.max(1,capacity);const queue=Math.max(0,Math.round((arrival-capacity)*1.5));const basePrefill=680*(1-cacheHit/100);const ttft=Math.round(180+basePrefill+queue*45+Math.max(0,pressure-1)*450);const speculative=1+acceptance/100*1.4;const tps=Math.round(Math.max(8,46/(1+Math.max(0,pressure-.8)*.75))*speculative);const gpu=Math.min(99,Math.round(34+pressure*58));const served=Math.min(arrival,capacity);return{capacity,queue,ttft,tps,gpu,served,pressure}},[arrival,batch,replicas,cacheHit,acceptance]);
 const meetsSlo=metrics.ttft<800&&metrics.tps>35&&metrics.served>=28&&metrics.queue<=3;
 const submit=()=>{const t=explain.toLowerCase();const hits=["queue","batch","replica","tensor","pipeline","cache","hit","speculative","ttft","itl","throughput","utilization"].filter(w=>t.includes(w)).length;if(explain.length<165||hits<9){setFeedback("Go deeper: diagnose queue/capacity, batching, replicas vs sharding, prefix cache hit rate, speculative decoding, TTFT/ITL/throughput and utilization/SLO context.");return;}setFeedback("Strong. You described inference optimization as an SLO/capacity system rather than a single GPU-utilization number.");progress.completeTask("m22-explain")};
 return <main className={styles.root}>
  <section className={styles.hero}><div><span className={styles.eyebrow}>MODULE 22 · INFRASTRUCTURE INCIDENT BOSS</span><h1>32 requests per second hit one replica. The queue starts screaming.</h1><p>Diagnose the bottleneck, tune batching, scale replicas, shard only when needed, increase prefix-cache reuse and add speculation until the service meets latency and throughput SLOs.</p><TaskStamp done={done===8}>{done}/8 boss missions complete</TaskStamp></div><InferenceFactory stage={metrics.queue>3?"queue":"decode"} queue={metrics.queue} batch={batch} replicas={replicas} gpuUtil={metrics.gpu} ttft={metrics.ttft} tps={metrics.tps}/></section>

  <LessonSection id="incident" onVisit={progress.markVisited} className={styles.scene}><h2>1. Diagnose signals before changing infrastructure.</h2>{incidentCases.map((c,i)=><div className={styles.card} key={c[0]}><p>{c[0]}</p>{["capacity","latency","overload","not-capacity"].map(answer=><button key={answer} className={`${styles.button} ${incident[i]===answer?(answer===c[1]?styles.good:styles.bad):""}`} onClick={()=>solve(incident,setIncident,incidentCases,i,answer,"m22-incident")}>{answer}</button>)}</div>)}<div className={styles.metricGrid}><div><span>arrival</span><b>{arrival} req/s</b></div><div><span>capacity</span><b>{metrics.capacity.toFixed(1)}</b></div><div><span>queue</span><b>{metrics.queue}</b></div><div><span>TTFT</span><b>{metrics.ttft}ms</b></div></div></LessonSection>

  <LessonSection id="batch" onVisit={progress.markVisited} className={styles.scene}><h2>2. Increase useful batching without turning latency into sludge.</h2><div className={styles.sliders}><label>Arrival <b>{arrival} req/s</b><input type="range" min="10" max="45" value={arrival} onChange={e=>{setArrival(+e.target.value);setBatchLocked(false)}}/></label><label>Batch target <b>{batch}</b><input type="range" min="1" max="16" value={batch} onChange={e=>{setBatch(+e.target.value);setBatchLocked(false)}}/></label></div><InferenceFactory stage="queue" queue={metrics.queue} batch={batch} replicas={replicas} gpuUtil={metrics.gpu} ttft={metrics.ttft} tps={metrics.tps}/><button className={styles.primary} disabled={batch<4} onClick={()=>{setBatchLocked(true);progress.completeTask("m22-batch")}}>Lock batching change</button>{batchLocked&&<p className={styles.feedback}>Batching improved aggregate capacity, but queue pressure may still require more replicas.</p>}</LessonSection>

  <LessonSection id="scale" onVisit={progress.markVisited} className={styles.scene}><h2>3. Add full-model replicas for horizontal request capacity.</h2><label className={styles.slider}>Replicas <b>{replicas}</b><input type="range" min="1" max="6" value={replicas} onChange={e=>{setReplicas(+e.target.value);setScaleLocked(false)}}/></label><InferenceFactory stage="queue" queue={metrics.queue} batch={batch} replicas={replicas} gpuUtil={metrics.gpu} ttft={metrics.ttft} tps={metrics.tps}/><button className={styles.primary} disabled={metrics.served<28} onClick={()=>{setScaleLocked(true);progress.completeTask("m22-scale")}}>Lock horizontal capacity</button>{scaleLocked&&<p className={styles.feedback}>✓ Aggregate capacity now covers the target throughput. Keep checking TTFT and queue.</p>}</LessonSection>

  <LessonSection id="shard" onVisit={progress.markVisited} className={styles.scene}><h2>4. Use sharding for model fit/compute — not as a synonym for replicas.</h2>{shardCases.map((c,i)=><div className={styles.card} key={c[0]}><p>{c[0]}</p>{["tensor","pipeline","replica"].map(answer=><button key={answer} className={`${styles.button} ${shard[i]===answer?(answer===c[1]?styles.good:styles.bad):""}`} onClick={()=>solve(shard,setShard,shardCases,i,answer,"m22-shard")}>{answer}</button>)}</div>)}<label className={styles.slider}>Tensor-parallel degree for oversized model <b>{tp}</b><input type="range" min="1" max="8" value={tp} onChange={e=>{setTp(+e.target.value);if(+e.target.value>=4)progress.completeTask("m22-shard")}}/></label></LessonSection>

  <LessonSection id="cache" onVisit={progress.markVisited} className={styles.scene}><h2>5. Shared long prefixes can create valuable prefill-cache hits.</h2>{cacheCases.map((c,i)=><div className={styles.card} key={c[0]}><p>{c[0]}</p>{["prefix-cache-good","prefix-cache-low","true","false"].map(answer=><button key={answer} className={`${styles.button} ${cache[i]===answer?(answer===c[1]?styles.good:styles.bad):""}`} onClick={()=>solve(cache,setCache,cacheCases,i,answer,"m22-cache")}>{answer}</button>)}</div>)}<label className={styles.slider}>Toy prefix cache hit rate <b>{cacheHit}%</b><input type="range" min="0" max="90" value={cacheHit} onChange={e=>{setCacheHit(+e.target.value);if(+e.target.value>=60)progress.completeTask("m22-cache")}}/></label><div className={styles.cacheBar}><i style={{width:`${cacheHit}%`}}/><span>{cacheHit}% hits · {100-cacheHit}% misses</span></div></LessonSection>

  <LessonSection id="spec" onVisit={progress.markVisited} className={styles.scene}><h2>6. Let a cheap draft process propose tokens, but keep target verification.</h2>{specCases.map((c,i)=><div className={styles.card} key={c[0]}><p>{c[0]}</p>{["good","bad","true"].map(answer=><button key={answer} className={`${styles.button} ${spec[i]===answer?(answer===c[1]?styles.good:styles.bad):""}`} onClick={()=>solve(spec,setSpec,specCases,i,answer,"m22-spec")}>{answer}</button>)}</div>)}<label className={styles.slider}>Draft acceptance <b>{acceptance}%</b><input type="range" min="0" max="95" value={acceptance} onChange={e=>{setAcceptance(+e.target.value);if(+e.target.value>=65)progress.completeTask("m22-spec")}}/></label><p>Current toy decode speed: <b>{metrics.tps} tok/s</b>. Real speedups depend on draft cost, target verification, acceptance patterns, hardware and runtime implementation.</p></LessonSection>

  <LessonSection id="slo" onVisit={progress.markVisited} className={styles.scene}><h2>7. Optimize against the user-facing SLO, not a vanity metric.</h2>{sloCases.map((c,i)=><div className={styles.card} key={c[0]}><p>{c[0]}</p>{["latency-slo","decode-slo","throughput-slo","capacity-slo"].map(answer=><button key={answer} className={`${styles.button} ${slo[i]===answer?(answer===c[1]?styles.good:styles.bad):""}`} onClick={()=>solve(slo,setSlo,sloCases,i,answer,"m22-slo")}>{answer}</button>)}</div>)}<div className={styles.slo}><span className={metrics.ttft<800?styles.pass:styles.fail}>TTFT {metrics.ttft}ms / 800</span><span className={metrics.tps>35?styles.pass:styles.fail}>decode {metrics.tps} / 35 tok/s</span><span className={metrics.served>=28?styles.pass:styles.fail}>served {metrics.served.toFixed(1)} / 28 req/s</span><span className={metrics.queue<=3?styles.pass:styles.fail}>queue {metrics.queue} / 3</span></div><button className={styles.primary} disabled={!meetsSlo} onClick={()=>progress.completeTask("m22-slo")}>Declare incident resolved</button></LessonSection>

  <LessonSection id="explain" onVisit={progress.markVisited} className={styles.scene}><h2>8. Explain why the incident was not “the model is slow.”</h2><textarea className={styles.textarea} value={explain} onChange={e=>setExplain(e.target.value)} placeholder="Explain queue/batching, replicas, tensor/pipeline sharding, prefix cache hit rate, speculative decoding, TTFT/ITL/throughput and utilization/SLO context."/><button className={styles.primary} onClick={submit}>Check explanation</button>{feedback&&<p className={styles.feedback}>{feedback}</p>}</LessonSection>

  <section className={styles.quiz}><h2>Module 22 mastery exam</h2>{!unlocked?<div className={styles.locked}>🔒 Complete all eight boss rooms. {done}/8 tasks · {read}/8 sections.</div>:<>{quiz.map((q,i)=><div className={styles.question} key={q[0]}><strong>{i+1}. {q[0]}</strong>{q[1].map((option,oi)=><button key={option} className={answers[i]===oi?styles.selected:""} onClick={()=>setAnswers(a=>({...a,[i]:oi}))}>{option}</button>)}{answers[i]!==undefined&&<small>{answers[i]===q[2]?"✓ Correct":`Correct: ${q[1][q[2]]}`}</small>}</div>)}<button className={styles.primary} disabled={!quizDone} onClick={()=>progress.saveQuiz(score,score>=10)}>Submit · {score}/12</button>{quizDone&&<p className={styles.feedback}>{score>=10?"★ INFERENCE INFRASTRUCTURE MASTERED":"Pass is 10/12. Revisit capacity, sharding and latency metrics."}</p>}</>}</section>
  <div className={styles.footer}><Link href="/lessons/scaling-serving-lab">← Scaling & Serving</Link><Link href="/lessons/ai-cost-challenge">AI Economics →</Link></div>
 </main>
}
