"use client";
import Link from "next/link";import {useState} from "react";import {LessonProgressApi} from "@/components/course/lesson-shell";import {DepthSwitch,LessonSection,TaskStamp} from "@/components/course/lesson-primitives";import {AttentionMatrix} from "@/components/interactive/attention-matrix";import {cases,crossWeights,decoderMask,decoderWeights,defs,encoderWeights,Family,quiz,source,target} from "./encoder-decoder-data";import styles from "./encoder-decoder-architectures.module.css";
type Props={progress:LessonProgressApi};
export function EncoderDecoderArchitecturesLesson({progress}:Props){
 const [compare,setCompare]=useState(2);const [encSeen,setEncSeen]=useState(false);const [decStep,setDecStep]=useState(0);const [crossRow,setCrossRow]=useState(0);const [crossSeen,setCrossSeen]=useState<number[]>([]);const [families,setFamilies]=useState<string[]>([]);const [answers,setAnswers]=useState<Record<number,Family>>({});const [explanation,setExplanation]=useState("");const [feedback,setFeedback]=useState("");const [quizAnswers,setQuizAnswers]=useState<Record<number,number>>({});const [quizFeedback,setQuizFeedback]=useState("");
 const tasks=defs.filter(([,t])=>progress.completedTasks[t]).length,rooms=defs.filter(([id])=>progress.visitedSections.has(id)).length,unlocked=tasks===9&&rooms===9;
 const copy={simple:"Transformers come in three common shapes: encoders build context-rich representations, decoders generate causally, and encoder-decoder systems let a generator attend to a separate encoded source.",real:"Encoder self-attention is commonly bidirectional over an input. Decoder self-attention is causal. Encoder-decoder architectures add cross-attention: decoder queries retrieve information from encoder output keys/values.",expert:"Transformer families differ mainly in attention graph and training objective. Encoder-only stacks expose bidirectional context, decoder-only stacks enforce causal factorization, while seq2seq models couple source encoding and target autoregression through cross-attention."} as const;
 const seeFamily=(f:string,task:string)=>{const n=families.includes(f)?families:[...families,f];setFamilies(n);progress.completeTask(task)};const cross=(r:number)=>{setCrossRow(r);const n=crossSeen.includes(r)?crossSeen:[...crossSeen,r];setCrossSeen(n);if(n.length===3)progress.completeTask("run-cross-attention")};const choose=(i:number,a:Family)=>{const n={...answers,[i]:a};setAnswers(n);if(cases.every((c,j)=>n[j]===c.answer))progress.completeTask("choose-transformer-family")};const explain=()=>{const t=explanation.toLowerCase();const hits=["encoder","decoder","causal","bidirectional","cross","query","key","value","source","target"].filter(k=>t.includes(k));if(explanation.trim().length<130||hits.length<6){setFeedback("Explain encoder bidirectional self-attention, decoder causal self-attention, and cross-attention where decoder queries read encoder K/V.");return;}setFeedback("Strong. You explained the transformer families through their attention graph and job.");progress.completeTask("explain-transformer-families")};const submit=()=>{const s=quiz.reduce((n,q,i)=>n+(quizAnswers[i]===q.c?1:0),0),p=s>=6;progress.saveQuiz(s,p);setQuizFeedback(p?`Passed ${s}/7.`:`${s}/7. Need 6/7.`)};
 return <main className={styles.root}>
 <section className={styles.hero}><div><span className={styles.eyebrow}>MODULE 4 · TRANSFORMER ARCHITECTURE THEATER</span><h1>Who reads? Who generates? Who looks across?</h1><p>{copy[progress.depth]}</p><DepthSwitch value={progress.depth} onChange={progress.setDepth}/></div><div className={styles.stage}><b>THREE STAGE DESIGNS</b><div className={styles.modelRow}><div className={`${styles.modelBox} ${styles.enc}`}>ENCODER</div></div><div className={styles.modelRow}><div className={`${styles.modelBox} ${styles.dec}`}>DECODER</div></div><div className={styles.modelRow}><div className={`${styles.modelBox} ${styles.enc}`}>ENCODER</div><div className={`${styles.modelBox} ${styles.cross}`}>CROSS</div><div className={`${styles.modelBox} ${styles.dec}`}>DECODER</div></div><p>{tasks}/9 experiments</p></div></section>
 <LessonSection id="why-transformers" onVisit={progress.markVisited} className={styles.scene}><TaskStamp done={!!progress.completedTasks["compare-recurrence-transformers"]}>01 · WHY TRANSFORMERS</TaskStamp><h2>Shorten dependency paths and parallelize sequence work.</h2><div className={styles.controls}><label>Distance {compare}<input type="range" min="2" max="30" value={compare} onChange={e=>setCompare(+e.target.value)}/></label><button className={styles.button} onClick={()=>{if(compare>=18)progress.completeTask("compare-recurrence-transformers")}}>Compare paths</button></div><div className={styles.stats}><div className={styles.stat}><span>Strict recurrent path</span><b>{compare-1} transitions</b></div><div className={styles.stat}><span>Attention interaction</span><b>direct within layer</b></div><div className={styles.stat}><span>Training positions</span><b>parallel-friendly</b></div></div><p>Transformers did not make recurrence mathematically impossible or useless; they offered a much more parallel training graph and short direct paths between distant positions.</p></LessonSection>
 <LessonSection id="encoder" onVisit={progress.markVisited} className={styles.scene}><TaskStamp done={!!progress.completedTasks["inspect-encoder"]}>02 · ENCODER</TaskStamp><h2>Let every input token use both left and right context.</h2><div className={styles.tokens}>{source.map(t=><span className={styles.token} key={t}>{t}</span>)}</div><button className={styles.button} onClick={()=>{setEncSeen(true);progress.completeTask("inspect-encoder")}}>Open bidirectional self-attention</button>{encSeen&&<AttentionMatrix tokens={source} weights={encoderWeights} activeRow={1}/>}<p>An encoder transforms all source positions into context-rich representations. “red” can look at both “the” and “cube”.</p></LessonSection>
 <LessonSection id="decoder" onVisit={progress.markVisited} className={styles.scene}><TaskStamp done={!!progress.completedTasks["inspect-decoder"]}>03 · DECODER</TaskStamp><h2>Generate without seeing future target tokens.</h2><div className={styles.timeline}>{target.map((t,i)=><span key={t} className={`${styles.step} ${i<=decStep?styles.active:""}`}>{t}</span>)}</div><div className={styles.controls}><button className={styles.button} onClick={()=>setDecStep(s=>{const n=Math.min(2,s+1);if(n===2)progress.completeTask("inspect-decoder");return n})}>Generate next →</button></div><AttentionMatrix tokens={target} weights={decoderWeights} activeRow={decStep} masked={decoderMask}/><p>At target position t, causal self-attention sees previous target positions, not future ground-truth tokens.</p></LessonSection>
 <LessonSection id="cross-attention" onVisit={progress.markVisited} className={styles.scene}><TaskStamp done={!!progress.completedTasks["run-cross-attention"]}>04 · CROSS-ATTENTION</TaskStamp><h2>Decoder queries read encoder keys and values.</h2><div className={styles.grid2}><div className={styles.panel}><b>ENCODER K/V</b><div className={styles.tokens}>{source.map(t=><span className={styles.token} key={t}>{t}</span>)}</div></div><div className={styles.panel}><b>DECODER Q</b><div className={styles.tokens}>{target.map((t,i)=><button className={`${styles.token} ${styles.target}`} key={t} onClick={()=>cross(i)}>{t}</button>)}</div></div></div><div className={styles.stats}>{source.map((t,i)=><div className={styles.stat} key={t}><span>{target[crossRow]} → {t}</span><b>{Math.round(crossWeights[crossRow][i]*100)}%</b></div>)}</div><p>Click all three target queries. Toy pattern: `cube` strongly reads source `cube`; `rouge` strongly reads source `red`.</p></LessonSection>
 <LessonSection id="encoder-only" onVisit={progress.markVisited} className={styles.scene}><TaskStamp done={!!progress.completedTasks["inspect-encoder-only"]}>05 · ENCODER-ONLY</TaskStamp><h2>Build representations from the whole visible input.</h2><button className={styles.button} onClick={()=>seeFamily("encoder","inspect-encoder-only")}>Inspect encoder-only pipeline</button><div className={styles.modelRow}><div className={`${styles.modelBox} ${styles.enc}`}>bidirectional encoder stack</div><b>→</b><div className={styles.modelBox}>classification / embeddings / token labels</div></div></LessonSection>
 <LessonSection id="decoder-only" onVisit={progress.markVisited} className={styles.scene}><TaskStamp done={!!progress.completedTasks["inspect-decoder-only"]}>06 · DECODER-ONLY</TaskStamp><h2>Factor text autoregressively.</h2><button className={styles.button} onClick={()=>seeFamily("decoder","inspect-decoder-only")}>Inspect decoder-only pipeline</button><div className={styles.modelRow}><div className={`${styles.modelBox} ${styles.dec}`}>causal decoder stack</div><b>→</b><div className={styles.modelBox}>next-token distribution</div><b>→</b><div className={styles.modelBox}>append token & repeat</div></div></LessonSection>
 <LessonSection id="encoder-decoder" onVisit={progress.markVisited} className={styles.scene}><TaskStamp done={!!progress.completedTasks["inspect-encoder-decoder"]}>07 · ENCODER-DECODER</TaskStamp><h2>Separate source understanding from target generation.</h2><button className={styles.button} onClick={()=>seeFamily("encdec","inspect-encoder-decoder")}>Inspect seq2seq pipeline</button><div className={styles.modelRow}><div className={`${styles.modelBox} ${styles.enc}`}>source encoder</div><b>→ K/V →</b><div className={`${styles.modelBox} ${styles.cross}`}>cross-attention</div><b>← Q ←</b><div className={`${styles.modelBox} ${styles.dec}`}>target decoder</div></div></LessonSection>
 <LessonSection id="choose-architecture" onVisit={progress.markVisited} className={styles.scene}><TaskStamp done={!!progress.completedTasks["choose-transformer-family"]}>08 · CHOOSE THE FAMILY</TaskStamp><h2>Match attention graph to task.</h2><div className={styles.grid3}>{cases.map((c,i)=><div className={styles.case} key={c.text}><p>{c.text}</p>{(["encoder","decoder","encdec"] as Family[]).map(a=><button key={a} className={answers[i]===a?(a===c.answer?styles.correct:styles.wrong):""} onClick={()=>choose(i,a)}>{a}</button>)}</div>)}</div></LessonSection>
 <LessonSection id="explain-families" onVisit={progress.markVisited} className={`${styles.scene} ${styles.explain}`}><TaskStamp done={!!progress.completedTasks["explain-transformer-families"]}>09 · EXPLAIN IT BACK</TaskStamp><h2>Explain encoder-only, decoder-only and encoder-decoder by what each attention path can see.</h2><textarea value={explanation} onChange={e=>setExplanation(e.target.value)}/><button className={styles.button} onClick={explain}>Check explanation</button>{feedback&&<div className={styles.feedback}>{feedback}</div>}</LessonSection>
 <section className={styles.quiz}><h2>Transformer Families Check</h2>{!unlocked?<div className={styles.locked}>Locked: {tasks}/9 tasks · {rooms}/9 rooms.</div>:<>{quiz.map((q,i)=><div className={styles.question} key={q.q}><strong>{i+1}. {q.q}</strong>{q.o.map((o,j)=><button key={o} className={quizAnswers[i]===j?styles.selected:""} onClick={()=>setQuizAnswers(a=>({...a,[i]:j}))}>{o}</button>)}</div>)}<button className={styles.button} onClick={submit}>Submit quiz</button>{quizFeedback&&<div className={styles.feedback}>{quizFeedback}</div>}</>}<div className={styles.footer}><Link href="/lessons/positions-masks-cache">← Position & efficiency</Link><Link href="/">Course map →</Link></div></section>
 </main>
}
