"use client";

import Link from "next/link";
import { motion, Reorder } from "motion/react";
import { ReactNode, useEffect, useState } from "react";
import { LessonProgressApi } from "@/components/course/lesson-shell";
import { DepthSwitch, LessonSection, TaskStamp } from "@/components/course/lesson-primitives";
import styles from "./scope-uncertainty.module.css";

type Props={progress:LessonProgressApi};
type Scope="specialized"|"broad"|"agi-concept";
type Verdict="true"|"false";
const sections=[{id:"scope-spectrum",taskId:"inspect-scope-spectrum"},{id:"narrow-vs-agi",taskId:"classify-scope"},{id:"deterministic-machine",taskId:"test-determinism"},{id:"probability-machine",taskId:"sample-probability"},{id:"sampling-controls",taskId:"control-sampling"},{id:"hybrid-system",taskId:"build-hybrid-system"},{id:"confidence-traps",taskId:"diagnose-confidence"},{id:"scope-traps",taskId:"repair-scope-myths"},{id:"explain-scope",taskId:"explain-scope"}] as const;
const scopeCases=[
 {id:"s1",text:"Spam filter trained to classify emails as spam/not spam.",answer:"specialized" as Scope},
 {id:"s2",text:"Chess engine that plays chess at superhuman level but does not independently run unrelated office tasks.",answer:"specialized" as Scope},
 {id:"s3",text:"A foundation model that can write, summarize, translate, code and analyze images across many domains.",answer:"broad" as Scope},
 {id:"s4",text:"A hypothetical system that robustly learns and performs a very wide range of intellectual tasks at broadly human-comparable generality, according to whatever operational AGI definition a researcher adopts.",answer:"agi-concept" as Scope},
 {id:"s5",text:"A route-optimization model for delivery vehicles.",answer:"specialized" as Scope},
 {id:"s6",text:"A multimodal assistant with broad capabilities but uneven reliability, tool dependence and task-specific limitations.",answer:"broad" as Scope}
] as const;
const confidenceCases=[
 {id:"c1",text:"Classifier says 90% CAT. Therefore it is guaranteed to be a cat.",answer:"false" as Verdict,why:"90% is not certainty. The model can still be wrong, and its probabilities may not be perfectly calibrated."},
 {id:"c2",text:"A language model can assign probabilities to multiple possible next tokens.",answer:"true" as Verdict,why:"Generation starts from a distribution over candidate continuations."},
 {id:"c3",text:"If temperature is zero/greedy decoding is used, the underlying model has stopped being probabilistic.",answer:"false" as Verdict,why:"The model can still compute a probability/logit distribution; the decoding policy simply chooses deterministically from it under idealized conditions."},
 {id:"c4",text:"A fixed random seed always guarantees bit-for-bit identical results on every hardware/runtime/provider.",answer:"false" as Verdict,why:"Seeds can improve reproducibility, but implementation, parallelism, kernels, provider behavior and floating-point details can still differ."},
 {id:"c5",text:"A deterministic software pipeline can contain a probabilistic model inside it.",answer:"true" as Verdict,why:"Many production systems combine deterministic validation/routing/business rules with probabilistic predictions."},
 {id:"c6",text:"A highly capable model automatically proves consciousness or human-like understanding.",answer:"false" as Verdict,why:"Capability breadth, subjective consciousness and human-like cognition are different claims and should not be conflated."}
] as const;
const myths=[
 {id:"m1",front:"Narrow AI means it can only do exactly one tiny thing.",back:"Too simplistic. Narrow/specialized means capability is bounded relative to general intelligence; some modern systems can cover many tasks without settling the AGI question."},
 {id:"m2",front:"AGI has one universally accepted test and threshold.",back:"No. AGI is a contested umbrella term with multiple operational definitions and benchmarks."},
 {id:"m3",front:"Probabilistic means random nonsense.",back:"No. A model can place very high probability on sensible outputs while still representing uncertainty and alternatives."},
 {id:"m4",front:"Deterministic means intelligent; probabilistic means AI.",back:"Wrong axis. Both AI and non-AI systems can contain deterministic and probabilistic components."},
 {id:"m5",front:"Broad capability = autonomy.",back:"Not necessarily. A model may answer across many domains while an application tightly limits actions, memory, tools or permissions."},
 {id:"m6",front:"If output repeats exactly twice, the whole system is deterministic.",back:"Not enough evidence. Caching, greedy decoding or one sampled repeat can produce identical outputs without proving every layer is deterministic."}
] as const;
const quiz=[
 {q:"Best distinction between specialized/narrow AI and AGI?",o:["Scope and generality of capability, using an explicit definition rather than a magical product label","One uses GPUs and one does not","One is deterministic and one probabilistic","AGI means any chatbot"],c:0,w:"Narrow vs AGI is about breadth/generality and operational criteria, not hardware or sampling mode."},
 {q:"Does a broad multimodal foundation model automatically settle whether AGI exists?",o:["No — broad capability and AGI classification depend on definitions, robustness and evaluation criteria","Yes, any multimodal system is AGI","Yes, if it codes","Only if temperature=1"],c:0,w:"Breadth is evidence about capability, but AGI is not a universally agreed product category."},
 {q:"A deterministic function ideally does what?",o:["Same input + same state produces the same output","Samples a different answer each time","Always uses AI","Always has no bugs"],c:0,w:"Determinism concerns repeatability given identical relevant conditions."},
 {q:"What does a probabilistic classifier output conceptually?",o:["A distribution/scores over possible outcomes from which a decision may be made","A guarantee","Only random noise","A checkpoint"],c:0,w:"Probabilistic models represent relative likelihood/scores, not guaranteed truth."},
 {q:"What does temperature mainly affect in language-model sampling?",o:["How sharply or broadly the decoding distribution is sampled","The learned weights during normal inference","The train/test split","Whether the model is AGI"],c:0,w:"Temperature is an inference/sampling control, not a learned weight."},
 {q:"Can deterministic rules wrap a probabilistic model?",o:["Yes — validation, permission, threshold and routing logic often do","No","Only in games","Only offline"],c:0,w:"Hybrid systems commonly mix both."},
 {q:"90% confidence means...",o:["High model confidence/score under that setup, not a logical guarantee of correctness","Guaranteed truth","AGI","No uncertainty"],c:0,w:"Calibration and data distribution matter; a confidence score is not certainty."}
] as const;
function Heading({n,k,title,children}:{n:string;k:string;title:string;children:ReactNode}){return <div className={styles.heading}><span>{n}</span><div><b>{k}</b><h2>{title}</h2><p>{children}</p></div></div>}
function ScopeBot({wide=false}:{wide?:boolean}){return <motion.div className={styles.scopeBot} animate={{scale:wide?[1,1.08,1]:[1,1.03,1],y:[0,-5,0]}} transition={{duration:wide?1.4:3,repeat:Infinity}}><div><i/><i/><strong>{wide?"∞":"1"}</strong></div><b>{wide?"BROAD":"FOCUS"}</b></motion.div>}
function DiceBot({active=false}:{active?:boolean}){return <motion.div className={styles.diceBot} animate={{rotate:active?[0,8,-8,0]:[0,1,-1,0],y:[0,-4,0]}} transition={{duration:active?1.1:3,repeat:Infinity}}><div><i/><i/><strong>⚄</strong></div><b>CHANCE</b></motion.div>}
function Quiz({progress,open}:{progress:LessonProgressApi;open:boolean}){const[a,setA]=useState<Record<number,number>>({});const[sub,setSub]=useState(false);const score=quiz.reduce((n,q,i)=>n+(a[i]===q.c?1:0),0);const pass=score>=6;if(!open)return <div className={styles.lock}>🎲🔒<h3>Uncertainty exam locked.</h3><p>Test scope, repeatability and sampling first.</p></div>;return <div className={styles.quiz}>{quiz.map((q,i)=><section key={q.q}><h3><span>{i+1}</span>{q.q}</h3><div>{q.o.map((x,j)=><button disabled={sub} className={`${a[i]===j?styles.selected:""} ${sub&&j===q.c?styles.correct:""} ${sub&&a[i]===j&&j!==q.c?styles.wrong:""}`} onClick={()=>setA(v=>({...v,[i]:j}))} key={x}>{x}</button>)}</div>{sub&&<p>{q.w}</p>}</section>)}{!sub?<button disabled={Object.keys(a).length!==quiz.length} onClick={()=>{setSub(true);progress.saveQuiz(score,pass)}}>CHECK SCOPE & UNCERTAINTY →</button>:<div className={`${styles.result} ${pass?styles.pass:styles.fail}`}><strong>{score}/7</strong><p>{pass?"You can separate capability scope from uncertainty and decoding behavior.":"Pass is 6/7. Re-open the experiments."}</p>{!pass&&<button onClick={()=>{setA({});setSub(false)}}>TRY AGAIN</button>}</div>}</div>}
export function ScopeUncertaintyLesson({progress}:Props){
 const[scopeMarks,setScopeMarks]=useState<number[]>([]);const[scopeChoices,setScopeChoices]=useState<Record<string,Scope>>({});const[detInput,setDetInput]=useState(7);const[detRuns,setDetRuns]=useState<number[]>([]);const[samples,setSamples]=useState<string[]>([]);const[temp,setTemp]=useState(.8);const[controlZones,setControlZones]=useState<string[]>([]);const[pipeline,setPipeline]=useState(["Input validation","Probabilistic model","Confidence threshold","Business rule","Final action"]);const[confidence,setConfidence]=useState<Record<string,Verdict>>({});const[flipped,setFlipped]=useState<string[]>([]);const[text,setText]=useState("");const[feedback,setFeedback]=useState("");
 const scopeCorrect=scopeCases.every(x=>scopeChoices[x.id]===x.answer);const confidenceCorrect=confidenceCases.every(x=>confidence[x.id]===x.answer);const pipeCorrect=pipeline.join("|")==="Input validation|Probabilistic model|Confidence threshold|Business rule|Final action";
 useEffect(()=>{if(scopeMarks.length>=4)progress.completeTask("inspect-scope-spectrum")},[scopeMarks,progress]);useEffect(()=>{if(scopeCorrect)progress.completeTask("classify-scope")},[scopeCorrect,progress]);useEffect(()=>{if(detRuns.length>=5&&new Set(detRuns).size===1)progress.completeTask("test-determinism")},[detRuns,progress]);useEffect(()=>{if(samples.length>=12&&new Set(samples).size>=2)progress.completeTask("sample-probability")},[samples,progress]);useEffect(()=>{if(["low","mid","high"].every(x=>controlZones.includes(x)))progress.completeTask("control-sampling")},[controlZones,progress]);useEffect(()=>{if(pipeCorrect)progress.completeTask("build-hybrid-system")},[pipeCorrect,progress]);useEffect(()=>{if(confidenceCorrect)progress.completeTask("diagnose-confidence")},[confidenceCorrect,progress]);useEffect(()=>{if(flipped.length===myths.length)progress.completeTask("repair-scope-myths")},[flipped,progress]);
 const required=sections.map(x=>x.taskId);const done=required.filter(x=>progress.completedTasks[x]).length;const read=sections.filter(x=>progress.visitedSections.has(x.id)).length;const open=done===9&&read===9;
 const runDet=()=>setDetRuns(v=>[...v,(detInput*detInput+3)%17]);const probs=(()=>{const raw=[Math.pow(.62,1/temp),Math.pow(.23,1/temp),Math.pow(.10,1/temp),Math.pow(.05,1/temp)];const z=raw.reduce((a,b)=>a+b,0);return raw.map(x=>x/z)})();const words=["blue","clear","bright","stormy"];const sample=()=>{let r=Math.random(),sum=0,chosen=words[0];for(let i=0;i<words.length;i++){sum+=probs[i];if(r<=sum){chosen=words[i];break}}setSamples(v=>[...v,chosen].slice(-24))};const markZone=()=>{const z=temp<.45?"low":temp>1.2?"high":"mid";setControlZones(v=>v.includes(z)?v:[...v,z]);sample()};
 const explain=()=>{const t=text.toLowerCase();const hits=["narrow","special", "broad","agi","definition","determin", "probab", "distribution","sampling","certainty","confidence"].filter(k=>t.includes(k));if(text.trim().length<120){setFeedback("Explain both axes: capability scope and deterministic/probabilistic behavior.");return}if(hits.length<7){setFeedback("Use precise words: specialized/narrow, broad/AGI definition, deterministic repeatability, probability distribution, sampling/confidence/uncertainty.");return}setFeedback("Strong. You kept capability scope, consciousness claims and probabilistic behavior as separate questions.");progress.completeTask("explain-scope")};
 return <main className={`${styles.lesson} lesson-main`}>
 <section className={styles.hero}><div><span className={styles.tag}>MODULE 01 · LESSON 15</span><h1>HOW BROAD?<br/>HOW CERTAIN?<br/><em>DIFFERENT QUESTIONS.</em></h1><p>“General intelligence” and “probabilistic output” are often mixed together. One axis asks <strong>what range of tasks a system can robustly handle</strong>. Another asks <strong>whether behavior is fixed or modeled as uncertainty/distributions</strong>.</p><DepthSwitch value={progress.depth} onChange={progress.setDepth}/></div><div className={styles.heroBots}><ScopeBot/><ScopeBot wide/><DiceBot active/></div></section>
 <LessonSection id="scope-spectrum" onVisit={progress.markVisited} className={styles.a}><Heading n="01" k="CLICK · EXPAND SCOPE" title="Capability lives on a spectrum, not in three magic boxes.">Click through increasingly broad capability envelopes. “Narrow” can still be extremely capable; broad does not automatically settle the AGI question.</Heading><div className={styles.spectrum}>{[1,2,3,4,5].map((level,i)=><button className={scopeMarks.includes(level)?styles.marked:""} onClick={()=>setScopeMarks(v=>v.includes(level)?v:[...v,level])} key={level}><span>{["ONE TASK","TASK FAMILY","MULTI-DOMAIN","BROAD FOUNDATION","AGI CONCEPT / DEFINITION-DEPENDENT"][i]}</span><i style={{width:`${20+level*15}%`}}/><small>{["spam filter","vision suite","text + code + image","many general domains","hypothetical threshold depends on definition"][i]}</small></button>)}</div><p className={styles.note}>AGI has no single universally agreed operational definition. Treat it as a claim that must specify what “general” means and how it is measured.</p><TaskStamp done={Boolean(progress.completedTasks["inspect-scope-spectrum"])}>Inspect at least four scope levels.</TaskStamp></LessonSection>
 <LessonSection id="narrow-vs-agi" onVisit={progress.markVisited} className={styles.b}><Heading n="02" k="CLASSIFY · DON'T OVERCLAIM" title="Specialized, broad, or AGI-as-a-concept?">Classify six descriptions. “Broad” is intentionally separate from “AGI” so capability breadth is not treated as an automatic philosophical verdict.</Heading><div className={styles.cards}>{scopeCases.map(x=>{const c=scopeChoices[x.id];return <article className={c?(c===x.answer?styles.good:styles.bad):""} key={x.id}><p>{x.text}</p><div>{(["specialized","broad","agi-concept"] as Scope[]).map(v=><button className={c===v?styles.active:""} onClick={()=>setScopeChoices(s=>({...s,[x.id]:v}))} key={v}>{v==="agi-concept"?"AGI CONCEPT":v.toUpperCase()}</button>)}</div></article>})}</div><TaskStamp done={Boolean(progress.completedTasks["classify-scope"])}>Classify all six scope descriptions.</TaskStamp></LessonSection>
 <LessonSection id="deterministic-machine" onVisit={progress.markVisited} className={styles.c}><Heading n="03" k="REPEAT SAME INPUT" title="Deterministic: same relevant conditions → same result.">Run the exact same toy function five times. Then change the input and see that deterministic does not mean “always the same answer,” only the same answer for the same state/input.</Heading><div className={styles.detLab}><div className={styles.functionBox}><code>f(x) = (x² + 3) mod 17</code><label>INPUT x <input type="number" value={detInput} onChange={e=>{setDetInput(Number(e.target.value));setDetRuns([])}}/></label><button onClick={runDet}>RUN SAME FUNCTION</button></div><div className={styles.runTape}>{detRuns.map((v,i)=><motion.i initial={{scale:0}} animate={{scale:1}} key={i}>{v}</motion.i>)}</div></div><TaskStamp done={Boolean(progress.completedTasks["test-determinism"])}>Run the same input at least five times and observe one repeated result.</TaskStamp></LessonSection>
 <LessonSection id="probability-machine" onVisit={progress.markVisited} className={styles.d}><Heading n="04" k="SAMPLE · DISTRIBUTION" title="Probabilistic: the system can represent several possible outcomes.">Sample the same prompt repeatedly from a fixed distribution. Variation does not mean the model forgot the prompt; the decoding process is drawing from alternatives.</Heading><div className={styles.probLab}><div className={styles.bars}>{words.map((w,i)=><div key={w}><span>{w}</span><i><b style={{width:`${probs[i]*100}%`}}/></i><strong>{Math.round(probs[i]*100)}%</strong></div>)}</div><div className={styles.sampleBox}><DiceBot active={samples.length>0}/><button onClick={sample}>SAMPLE SAME PROMPT</button><div>{samples.map((s,i)=><i key={`${s}-${i}`}>{s}</i>)}</div><small>{samples.length}/12 minimum samples</small></div></div><TaskStamp done={Boolean(progress.completedTasks["sample-probability"])}>Sample at least 12 times and observe at least two outcomes.</TaskStamp></LessonSection>
 <LessonSection id="sampling-controls" onVisit={progress.markVisited} className={styles.e}><Heading n="05" k="SLIDE · TEST 3 ZONES" title="The model distribution and the sampling policy are related — not identical.">Move temperature. Low values sharpen the distribution; higher values flatten it. Greedy decoding can make selection deterministic while the model still computes competing scores.</Heading><div className={styles.tempLab}><label>TEMPERATURE <strong>{temp.toFixed(2)}</strong><input type="range" min=".2" max="1.8" step=".05" value={temp} onChange={e=>setTemp(Number(e.target.value))}/></label><div className={styles.tempZones}><span className={temp<.45?styles.active:""}>SHARP</span><span className={temp>=.45&&temp<=1.2?styles.active:""}>MIDDLE</span><span className={temp>1.2?styles.active:""}>FLATTER</span></div><div className={styles.bars}>{words.map((w,i)=><div key={w}><span>{w}</span><i><b style={{width:`${probs[i]*100}%`}}/></i><strong>{Math.round(probs[i]*100)}%</strong></div>)}</div><button onClick={markZone}>SAMPLE + RECORD ZONE</button><p>Zones tested: {controlZones.length}/3.</p></div><TaskStamp done={Boolean(progress.completedTasks["control-sampling"])}>Test low, medium and high temperature zones.</TaskStamp></LessonSection>
 <LessonSection id="hybrid-system" onVisit={progress.markVisited} className={styles.f}><Heading n="06" k="DRAG · BUILD PRODUCTION PATH" title="Real products mix deterministic and probabilistic parts.">Order a hybrid decision path. The model predicts probabilistically, while software around it can validate inputs, apply thresholds, enforce rules and choose actions deterministically.</Heading><div className={styles.hybrid}><Reorder.Group axis="y" values={pipeline} onReorder={setPipeline}>{pipeline.map((x,i)=><Reorder.Item className={pipeCorrect?styles.pipeGood:""} value={x} key={x}><span>{i+1}</span><strong>{x}</strong><small>drag</small></Reorder.Item>)}</Reorder.Group><div><ScopeBot wide={pipeCorrect}/><p>{pipeCorrect?"Example: validate request → model estimates risk → deterministic threshold → business policy → action. Probability is contained inside a controlled application path.":"Move the model after input validation and before threshold/rule enforcement."}</p></div></div><TaskStamp done={Boolean(progress.completedTasks["build-hybrid-system"])}>Order the deterministic/probabilistic hybrid pipeline.</TaskStamp></LessonSection>
 <LessonSection id="confidence-traps" onVisit={progress.markVisited} className={styles.g}><Heading n="07" k="TRUE / FALSE" title="Probability is not certainty, and seeds are not magic reproducibility contracts.">Judge six statements. Focus on what a probability/confidence score actually guarantees — which is less than most people assume.</Heading><div className={styles.cards}>{confidenceCases.map(x=>{const c=confidence[x.id];return <article className={c?(c===x.answer?styles.good:styles.bad):""} key={x.id}><p>{x.text}</p>{c&&<small>{x.why}</small>}<div><button className={c==="true"?styles.active:""} onClick={()=>setConfidence(s=>({...s,[x.id]:"true"}))}>TRUE</button><button className={c==="false"?styles.active:""} onClick={()=>setConfidence(s=>({...s,[x.id]:"false"}))}>FALSE</button></div></article>})}</div><TaskStamp done={Boolean(progress.completedTasks["diagnose-confidence"])}>Judge all six uncertainty statements.</TaskStamp></LessonSection>
 <LessonSection id="scope-traps" onVisit={progress.markVisited} className={styles.h}><Heading n="08" k="FLIP ALL SIX" title="Destroy six scope myths.">Click each card to reveal the correction. This is where we separate capability, autonomy, consciousness, determinism and AGI terminology.</Heading><div className={styles.mythGrid}>{myths.map(x=><button className={flipped.includes(x.id)?styles.flipped:""} onClick={()=>setFlipped(v=>v.includes(x.id)?v:[...v,x.id])} key={x.id}><strong>{flipped.includes(x.id)?"CORRECTION":x.front}</strong><p>{flipped.includes(x.id)?x.back:"CLICK TO FLIP"}</p></button>)}</div><TaskStamp done={Boolean(progress.completedTasks["repair-scope-myths"])}>Flip all six misconception cards.</TaskStamp></LessonSection>
 <LessonSection id="explain-scope" onVisit={progress.markVisited} className={styles.i}><Heading n="09" k="TYPE · TEACH" title="Explain the two axes without anthropomorphism.">Explain specialized/broad/AGI terminology on one axis and deterministic/probabilistic behavior on another.</Heading><div className={styles.explain}><div><span>🎯🎲</span><p>“If a model gives different answers, does that make it more generally intelligent?”</p></div><section><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Capability scope asks... Narrow/specialized... AGI is definition-dependent... Deterministic means... Probabilistic means... Sampling/confidence..."/><footer><span>{text.length} chars</span><button onClick={explain}>CHECK EXPLANATION</button></footer>{feedback&&<p className={progress.completedTasks["explain-scope"]?styles.feedbackGood:styles.feedbackHint}>{feedback}</p>}</section></div><TaskStamp done={Boolean(progress.completedTasks["explain-scope"])}>Explain scope and uncertainty as separate dimensions.</TaskStamp></LessonSection>
 <section className={styles.gate}><div>SECTIONS<strong>{read}/9</strong></div><div>TASKS<strong>{done}/9</strong></div><div className={open?styles.open:""}>QUIZ<strong>{open?"OPEN":"LOCKED"}</strong></div></section><section className={styles.quizSection}><h2>How broad? How repeatable?</h2><Quiz progress={progress} open={open}/></section><section className={styles.footer}><div><small>MENTAL MODEL</small><h2>Scope is not randomness. Probability is not intelligence.</h2></div><Link href="/lessons/learning-across-time-tasks">← LESSON 14</Link><Link href="/lessons/module-1-capstone">BOSS LEVEL →</Link></section>
 </main>
}
