"use client";

import Link from "next/link";
import { motion } from "motion/react";
import { ReactNode, useEffect, useState } from "react";
import { LessonProgressApi } from "@/components/course/lesson-shell";
import { DepthSwitch, LessonSection, TaskStamp } from "@/components/course/lesson-primitives";
import styles from "./generalization.module.css";

type Props={progress:LessonProgressApi};
type Diagnosis="underfit"|"overfit"|"good"|"shift";
const sections=[
 {id:"new-data",taskId:"predict-new-data"},{id:"complexity",taskId:"test-complexity"},{id:"underfitting",taskId:"repair-underfit"},{id:"overfitting",taskId:"repair-overfit"},{id:"more-data",taskId:"test-data-size"},{id:"bias-variance",taskId:"inspect-bias-variance"},{id:"outside-range",taskId:"test-extrapolation"},{id:"diagnose-generalization",taskId:"diagnose-generalization"},{id:"explain-generalization",taskId:"explain-generalization"}
] as const;
const diagnoses=[
 {id:"d1",text:"Train error high. New-data error high. Curve obviously misses the main trend.",answer:"underfit" as Diagnosis},
 {id:"d2",text:"Train error almost zero. New-data error much worse. Model wiggles around individual noisy points.",answer:"overfit" as Diagnosis},
 {id:"d3",text:"Train and new-data error are both low and similar.",answer:"good" as Diagnosis},
 {id:"d4",text:"Model worked in Serbia retail data, then fails after deployment on a very different country/domain distribution.",answer:"shift" as Diagnosis},
 {id:"d5",text:"One straight line is used for a strongly curved relationship; more training points do not fix the misspecified shape.",answer:"underfit" as Diagnosis},
 {id:"d6",text:"Huge tree memorizes rare IDs and exact training quirks; training score 100%, holdout score poor.",answer:"overfit" as Diagnosis},
 {id:"d7",text:"Regularized model has slightly worse training error but better holdout performance.",answer:"good" as Diagnosis},
 {id:"d8",text:"Input values at deployment live far outside the range represented during training.",answer:"shift" as Diagnosis}
];
const quiz=[
 {q:"What does generalization mean?",o:["Performing well on new relevant examples, not only the training examples","Getting zero training error at any cost","Using the largest model","Remembering every row"],c:0,w:"Generalization is the ability to transfer learned patterns to new examples drawn from the intended task/distribution."},
 {q:"What is underfitting?",o:["Model is too rigid/simple or otherwise unable to capture important structure","Train perfect, test bad","Dataset is always too large","Using validation data"],c:0,w:"Underfit models have excessive approximation/systematic error and often perform poorly on both training and new data."},
 {q:"What is overfitting?",o:["Learning training-specific noise/quirks so training performance is much better than new-data performance","Any high-capacity model","Any model with low test error","Only a neural-network problem"],c:0,w:"Overfitting is about poor generalization relative to fit on training data, not a specific algorithm family."},
 {q:"Why can more data help an overfitting model?",o:["It gives the learner more varied evidence, making individual quirks harder to memorize as if they were the rule","It always reduces parameter count","It deletes the loss","It guarantees no distribution shift"],c:0,w:"More representative data can constrain a flexible learner and reduce variance, though it is not a universal cure."},
 {q:"Bias in the bias/variance tradeoff means...",o:["Systematic error from restrictive assumptions/model class in this statistical context","Social prejudice only","The label column","A random seed"],c:0,w:"Statistical bias here is systematic approximation error. It is a different use of the word from social/fairness bias."},
 {q:"High variance means...",o:["The learned function changes a lot when the training sample changes","The model is always linear","No data exists","The API temperature is high"],c:0,w:"Variance captures sensitivity to the particular training sample; very flexible models can fit sampling noise."},
 {q:"Why is extrapolation risky?",o:["Outside the observed range, many different functions can fit seen data yet disagree strongly about unseen regions","Models cannot output numbers","Training data is illegal","Only because GPUs are slow"],c:0,w:"Data constrains behavior where it exists. Far outside that region, assumptions dominate and uncertainty can grow."}
] as const;
function Heading({n,k,title,children}:{n:string;k:string;title:string;children:ReactNode}){return <div className={styles.heading}><span>{n}</span><div><b>{k}</b><h2>{title}</h2><p>{children}</p></div></div>}
function CurveBot({wild=false}:{wild?:boolean}){return <motion.div className={styles.curveBot} animate={{rotate:wild?[0,-4,5,-3,0]:[0,1,-1,0],y:[0,-5,0]}} transition={{duration:wild?1.4:3,repeat:Infinity}}><div><i/><i/><strong>ƒ</strong><span>~</span></div><b>FLEX</b></motion.div>}
function NewPoint({active=false}:{active?:boolean}){return <motion.div className={styles.newPoint} animate={{scale:active?[1,1.12,1]:[1,1.03,1]}} transition={{duration:1.7,repeat:Infinity}}><div>?</div><b>NEW DATA</b></motion.div>}
function Quiz({progress,open}:{progress:LessonProgressApi;open:boolean}){const[a,setA]=useState<Record<number,number>>({});const[s,setS]=useState(false);const score=quiz.reduce((n,q,i)=>n+(a[i]===q.c?1:0),0);if(!open)return <div className={styles.lock}>📈🔒<h3>Generalization test locked.</h3><p>Break and repair the curves first.</p></div>;return <div className={styles.quiz}>{quiz.map((q,i)=><section key={q.q}><h3><span>{i+1}</span>{q.q}</h3><div>{q.o.map((x,j)=><button disabled={s} className={`${a[i]===j?styles.sel:""} ${s&&j===q.c?styles.ok:""} ${s&&a[i]===j&&j!==q.c?styles.no:""}`} onClick={()=>setA(v=>({...v,[i]:j}))} key={x}>{x}</button>)}</div>{s&&<p>{q.w}</p>}</section>)}{!s?<button className="tactile" disabled={Object.keys(a).length!==7} onClick={()=>{setS(true);progress.saveQuiz(score,score>=6)}}>CHECK GENERALIZATION →</button>:<div className={`${styles.quizResult} ${score>=6?styles.pass:styles.fail}`}><strong>{score}/7</strong><p>{score>=6?"You are optimizing for new data now, not training applause.":"Pass is 6/7. Revisit the train-vs-new-data gap."}</p>{score<6&&<button onClick={()=>{setA({});setS(false)}}>TRY AGAIN</button>}</div>}</div>}
export function GeneralizationLesson({progress}:Props){
 const[predictions,setPredictions]=useState<number[]>([]);const[complexity,setComplexity]=useState(3);const[complexZones,setComplexZones]=useState<string[]>([]);const[underComplexity,setUnderComplexity]=useState(1);const[underFixed,setUnderFixed]=useState(false);const[noise,setNoise]=useState(35);const[overComplexity,setOverComplexity]=useState(10);const[regularization,setRegularization]=useState(0);const[overBroken,setOverBroken]=useState(false);const[overFixed,setOverFixed]=useState(false);const[dataSize,setDataSize]=useState(20);const[dataRuns,setDataRuns]=useState<number[]>([]);const[biasComplexity,setBiasComplexity]=useState(3);const[biasNoise,setBiasNoise]=useState(20);const[biasData,setBiasData]=useState(80);const[biasSeen,setBiasSeen]=useState<string[]>([]);const[range,setRange]=useState(70);const[rangeTests,setRangeTests]=useState<string[]>([]);const[choices,setChoices]=useState<Record<string,Diagnosis>>({});const[text,setText]=useState("");const[feedback,setFeedback]=useState("");
 const trainErr=Math.max(.02,.54-complexity*.045);const testErr=Math.min(.8,.09+Math.pow(complexity-4,2)*.013);const underTrain=.5-underComplexity*.06;const underTest=.54-underComplexity*.065;const overTrain=Math.max(.005,.38-overComplexity*.032);const overTest=Math.max(.11,.14+noise*.004+Math.max(0,overComplexity-5)*.045-regularization*.0035);const dataGap=Math.max(.03,.42*(20/dataSize));const bias=Math.max(.04,.72-biasComplexity*.1);const variance=Math.min(.9,.08+biasComplexity*.07+(biasNoise/100)*.28-(biasData/200)*.2);const diagOk=diagnoses.every(d=>choices[d.id]===d.answer);
 useEffect(()=>{if(predictions.length>=4)progress.completeTask("predict-new-data")},[predictions.length,progress]);useEffect(()=>{if(["low","good","high"].every(z=>complexZones.includes(z)))progress.completeTask("test-complexity")},[complexZones,progress]);useEffect(()=>{if(underFixed)progress.completeTask("repair-underfit")},[underFixed,progress]);useEffect(()=>{if(overBroken&&overFixed)progress.completeTask("repair-overfit")},[overBroken,overFixed,progress]);useEffect(()=>{if(dataRuns.length>=3)progress.completeTask("test-data-size")},[dataRuns.length,progress]);useEffect(()=>{if(biasSeen.includes("high-bias")&&biasSeen.includes("high-variance")&&biasSeen.includes("balanced"))progress.completeTask("inspect-bias-variance")},[biasSeen,progress]);useEffect(()=>{if(rangeTests.includes("inside")&&rangeTests.includes("outside"))progress.completeTask("test-extrapolation")},[rangeTests,progress]);useEffect(()=>{if(diagOk)progress.completeTask("diagnose-generalization")},[diagOk,progress]);
 const required=sections.map(x=>x.taskId);const done=required.filter(x=>progress.completedTasks[x]).length;const read=sections.filter(x=>progress.visitedSections.has(x.id)).length;const quizOpen=done===9&&read===9;
 const testComplex=()=>{const z=complexity<=2?"low":complexity<=6?"good":"high";setComplexZones(s=>s.includes(z)?s:[...s,z])};const runData=()=>setDataRuns(s=>[...s,dataSize].slice(-5));const testBias=()=>{const z=bias>.42?"high-bias":variance>.42?"high-variance":"balanced";setBiasSeen(s=>s.includes(z)?s:[...s,z])};const testRange=()=>{const z=range<=100?"inside":"outside";setRangeTests(s=>s.includes(z)?s:[...s,z])};
 const explain=()=>{const t=text.toLowerCase();const hits=["general", "new", "training", "underfit", "overfit", "noise", "bias", "variance", "complex", "test"].filter(k=>t.includes(k));if(text.trim().length<110){setFeedback("Explain generalization, underfitting and overfitting with train-vs-new-data behavior.");return}if(hits.length<7){setFeedback("Add mechanism words: training data, new/test data, complexity, noise, bias/variance, underfit/overfit.");return}setFeedback("Strong. You are judging the model by performance on new relevant data, not by memorizing its homework.");progress.completeTask("explain-generalization")};
 return <main className={`${styles.lesson} lesson-main`}>
  <section className={styles.hero}><div><span className={styles.tag}>MODULE 01 · LESSON 12</span><h1>DON'T<br/>MEMORIZE<br/><em>THE HOMEWORK.</em></h1><p>The point of learning is not to look brilliant on examples you already saw. <strong>Generalization means the learned pattern still works on new relevant examples.</strong></p><DepthSwitch value={progress.depth} onChange={progress.setDepth}/></div><div className={styles.heroGraph}><CurveBot/><svg viewBox="0 0 100 70"><path d="M3 58 C18 40 28 45 40 28 S65 10 78 27 S91 48 98 12" fill="none" stroke="currentColor" strokeWidth="3"/>{[8,18,31,45,58,70,83,93].map((x,i)=><circle key={x} cx={x} cy={55-(i%4)*10+(i%2)*7} r="2.5"/>)}</svg><NewPoint active/></div></section>
  <LessonSection id="new-data" onVisit={progress.markVisited} className={styles.a}><Heading n="01" k="PREDICT · THEN REVEAL" title="Training examples are practice — new examples are the exam.">Guess four hidden outcomes. The point is to feel the difference between seeing a known training dot and predicting a fresh point.</Heading><div className={styles.newDataLab}><div className={styles.trainPanel}><span>TRAINING DATA</span>{[18,24,31,38,45,52,60,69].map((x,i)=><i style={{left:`${x}%`,bottom:`${20+(i%4)*15}%`}} key={i}/>)}</div><div className={styles.newPanel}><span>NEW / HOLDOUT POINTS</span>{[0,1,2,3].map(i=><button className={predictions.includes(i)?styles.predicted:""} onClick={()=>setPredictions(s=>s.includes(i)?s:[...s,i])} style={{left:`${20+i*19}%`,bottom:`${25+(i%3)*18}%`}} key={i}>{predictions.includes(i)?"✓":"?"}</button>)}</div></div><p className={styles.note}>A model can fit every training dot and still fail the right-hand panel. That gap is the heart of overfitting.</p><TaskStamp done={Boolean(progress.completedTasks["predict-new-data"])}>Reveal predictions for all four new points.</TaskStamp></LessonSection>
  <LessonSection id="complexity" onVisit={progress.markVisited} className={styles.b}><Heading n="02" k="SLIDE · TEST 3 ZONES" title="Complexity is a dial — not a virtue.">Move from rigid to flexible. Training error tends to fall as flexibility increases; new-data error often has a sweet spot instead of falling forever.</Heading><div className={styles.complexLab}><div className={styles.curvePlot}><svg viewBox="0 0 100 70"><path className={complexity<=2?styles.simpleCurve:complexity<=6?styles.goodCurve:styles.wildCurve} d={complexity<=2?"M3 58 L98 12":complexity<=6?"M3 58 C20 45 28 49 40 31 S65 12 80 29 S91 43 98 15":"M3 58 C10 2 18 70 28 20 S40 68 52 13 S63 62 72 18 S87 68 98 10"} fill="none" stroke="currentColor" strokeWidth="3"/>{[9,20,31,43,55,69,82,94].map((x,i)=><circle key={x} cx={x} cy={56-(i%4)*11+(i%2)*6} r="2.5"/>)}</svg><CurveBot wild={complexity>6}/></div><div className={styles.complexControls}><label>MODEL COMPLEXITY <strong>{complexity}/10</strong><input type="range" min="1" max="10" value={complexity} onChange={e=>setComplexity(Number(e.target.value))}/></label><div className={styles.errors}><div><span>TRAIN ERROR</span><strong>{trainErr.toFixed(3)}</strong></div><div><span>NEW-DATA ERROR</span><strong>{testErr.toFixed(3)}</strong></div></div><div className={styles.zones}><span className={complexity<=2?styles.active:""}>TOO SIMPLE</span><span className={complexity>2&&complexity<=6?styles.active:""}>SWEET SPOT</span><span className={complexity>6?styles.active:""}>TOO FLEXIBLE</span></div><button onClick={testComplex}>TEST THIS COMPLEXITY</button><small>tested zones {complexZones.length}/3</small></div></div><TaskStamp done={Boolean(progress.completedTasks["test-complexity"])}>Test low, useful and high-complexity zones.</TaskStamp></LessonSection>
  <LessonSection id="underfitting" onVisit={progress.markVisited} className={styles.c}><Heading n="03" k="BREAK · REPAIR" title="Underfitting: the model cannot capture the main pattern.">Start with a rigid model. Increase flexibility until both training and new-data errors become reasonable.</Heading><div className={styles.repairLab}><div className={styles.repairGraph}><svg viewBox="0 0 100 70"><path d={underComplexity<3?"M4 52 L96 31":"M4 57 C25 55 30 19 50 27 S75 57 96 14"} fill="none" stroke="currentColor" strokeWidth="4"/>{[10,22,34,47,60,73,86].map((x,i)=><circle key={x} cx={x} cy={55-(i%3)*17} r="3"/>)}</svg></div><div><label>FLEXIBILITY <strong>{underComplexity}</strong><input type="range" min="1" max="4" value={underComplexity} onChange={e=>{setUnderComplexity(Number(e.target.value));setUnderFixed(false)}}/></label><p>train error {Math.max(.08,underTrain).toFixed(2)} · new error {Math.max(.1,underTest).toFixed(2)}</p><button onClick={()=>setUnderFixed(underComplexity>=3)}>CHECK REPAIR</button>{underFixed&&<strong>✓ enough flexibility to capture the toy curve</strong>}</div></div><TaskStamp done={Boolean(progress.completedTasks["repair-underfit"])}>Repair the underfit toy model.</TaskStamp></LessonSection>
  <LessonSection id="overfitting" onVisit={progress.markVisited} className={styles.d}><Heading n="04" k="ADD NOISE · MEMORIZE · REGULARIZE" title="Overfitting: flexibility starts learning accidents as if they were laws.">Turn up noise and complexity, observe the train/new-data gap, then increase regularization until the gap improves.</Heading><div className={styles.overLab}><div className={styles.noisyGraph}><svg viewBox="0 0 100 70"><path d={overComplexity>7&&regularization<45?"M3 55 C8 4 15 70 23 11 S35 64 44 9 S55 66 66 14 S79 68 88 12 S95 61 98 20":"M3 56 C20 44 30 50 42 28 S67 13 81 29 S92 43 98 16"} fill="none" stroke="currentColor" strokeWidth="3"/>{[8,17,28,39,50,61,73,84,94].map((x,i)=><circle key={x} cx={x} cy={50-(i%4)*9+((i*noise)%17)/2} r="2.5"/>)}</svg></div><div className={styles.overControls}><label>NOISE <strong>{noise}</strong><input type="range" min="0" max="70" value={noise} onChange={e=>setNoise(Number(e.target.value))}/></label><label>COMPLEXITY <strong>{overComplexity}</strong><input type="range" min="4" max="12" value={overComplexity} onChange={e=>setOverComplexity(Number(e.target.value))}/></label><label>REGULARIZATION <strong>{regularization}</strong><input type="range" min="0" max="100" value={regularization} onChange={e=>setRegularization(Number(e.target.value))}/></label><div className={styles.errors}><div><span>TRAIN ERROR</span><strong>{overTrain.toFixed(3)}</strong></div><div><span>NEW ERROR</span><strong>{overTest.toFixed(3)}</strong></div></div><button onClick={()=>setOverBroken(noise>=30&&overComplexity>=8)}>MAKE IT OVERFIT</button><button disabled={!overBroken} onClick={()=>setOverFixed(regularization>=45&&overTest<.55)}>CHECK REGULARIZED REPAIR</button>{overBroken&&<small>overfit state witnessed ✓</small>}{overFixed&&<strong>gap reduced ✓</strong>}</div></div><TaskStamp done={Boolean(progress.completedTasks["repair-overfit"])}>Create an overfit state, then repair it with stronger regularization.</TaskStamp></LessonSection>
  <LessonSection id="more-data" onVisit={progress.markVisited} className={styles.e}><Heading n="05" k="SLIDE · RUN 3 SIZES" title="More representative data can constrain a flexible model.">Change sample size while the model stays flexible. This toy shows variance/generalization gap shrinking with more examples.</Heading><div className={styles.dataLab}><div className={styles.dataCloud}>{Array.from({length:Math.min(120,dataSize)}).map((_,i)=><i style={{left:`${5+(i*37)%90}%`,top:`${8+(i*53)%82}%`}} key={i}/>)}</div><div><label>TRAINING EXAMPLES <strong>{dataSize}</strong><input type="range" min="20" max="200" step="20" value={dataSize} onChange={e=>setDataSize(Number(e.target.value))}/></label><div className={styles.gapMeter}><span>TOY GENERALIZATION GAP</span><strong>{dataGap.toFixed(3)}</strong><i><b style={{width:`${Math.min(100,dataGap*180)}%`}}/></i></div><button onClick={runData}>TRAIN WITH THIS DATA SIZE</button><p>Runs: {dataRuns.length}/3. More data is helpful only when it is relevant, sufficiently representative and measured correctly.</p></div></div><TaskStamp done={Boolean(progress.completedTasks["test-data-size"])}>Run at least three different data sizes.</TaskStamp></LessonSection>
  <LessonSection id="bias-variance" onVisit={progress.markVisited} className={styles.f}><Heading n="06" k="MOVE THE SEESAW" title="Bias and variance are two different ways to be wrong.">Statistical <strong>bias</strong> here means systematic approximation error — not social/fairness bias. Variance means sensitivity to which training sample you happened to get.</Heading><div className={styles.seesawLab}><div className={styles.seesaw}><motion.div animate={{rotate:(variance-bias)*24}}><span>BIAS<br/><b>{bias.toFixed(2)}</b></span><i/><span>VARIANCE<br/><b>{variance.toFixed(2)}</b></span></motion.div></div><div><label>COMPLEXITY <strong>{biasComplexity}</strong><input type="range" min="1" max="8" value={biasComplexity} onChange={e=>setBiasComplexity(Number(e.target.value))}/></label><label>DATA SIZE <strong>{biasData}</strong><input type="range" min="20" max="200" step="20" value={biasData} onChange={e=>setBiasData(Number(e.target.value))}/></label><label>NOISE <strong>{biasNoise}</strong><input type="range" min="0" max="80" value={biasNoise} onChange={e=>setBiasNoise(Number(e.target.value))}/></label><button onClick={testBias}>INSPECT THIS REGIME</button><p>Find all three: high bias, high variance, and a more balanced regime. Seen {biasSeen.length}/3.</p></div></div><TaskStamp done={Boolean(progress.completedTasks["inspect-bias-variance"])}>Produce and inspect all three bias/variance regimes.</TaskStamp></LessonSection>
  <LessonSection id="outside-range" onVisit={progress.markVisited} className={styles.g}><Heading n="07" k="MOVE BEYOND THE MAP" title="Interpolation is not extrapolation.">Drag the prediction point from inside the observed range to far outside it. Training data constrains the curve where examples exist; outside that range, assumptions dominate.</Heading><div className={styles.rangeLab}><div className={styles.rangePlot}><span className={styles.seenRange}>TRAINING RANGE</span>{[15,27,39,51,63,75,87].map((x,i)=><i style={{left:`${x/1.3}%`,bottom:`${22+(i%4)*14}%`}} key={x}/>)}<motion.b animate={{left:`${Math.min(95,range/1.4)}%`}}>{range<=100?"NEW":"FAR OUT"}</motion.b><svg viewBox="0 0 100 70"><path d="M3 57 C25 46 36 51 49 28 S70 14 98 10" fill="none" stroke="currentColor" strokeWidth="3"/></svg></div><div><label>INPUT POSITION <strong>{range}</strong><input type="range" min="10" max="140" value={range} onChange={e=>setRange(Number(e.target.value))}/></label><button onClick={testRange}>TEST THIS POSITION</button><p>{range<=100?"Mostly within/near the region supported by observed examples — interpolation-like behavior.":"Outside the supported range. A different plausible function could agree on training data yet predict something very different here."}</p></div></div><TaskStamp done={Boolean(progress.completedTasks["test-extrapolation"])}>Test one point inside and one point outside the training range.</TaskStamp></LessonSection>
  <LessonSection id="diagnose-generalization" onVisit={progress.markVisited} className={styles.h}><Heading n="08" k="DIAGNOSE · CLICK" title="Name the failure before reaching for a fix.">Classify eight situations as underfit, overfit, healthy generalization, or distribution/range shift.</Heading><div className={styles.diagGrid}>{diagnoses.map(d=>{const c=choices[d.id];return <article className={c?(c===d.answer?styles.good:styles.bad):""} key={d.id}><p>{d.text}</p><div>{(["underfit","overfit","good","shift"] as Diagnosis[]).map(x=><button className={c===x?styles.active:""} onClick={()=>setChoices(v=>({...v,[d.id]:x}))} key={x}>{x.toUpperCase()}</button>)}</div></article>})}</div><TaskStamp done={Boolean(progress.completedTasks["diagnose-generalization"])}>Diagnose all eight cases.</TaskStamp></LessonSection>
  <LessonSection id="explain-generalization" onVisit={progress.markVisited} className={styles.i}><Heading n="09" k="TYPE · TEACH" title="Explain why perfect training accuracy can be bad news.">Use train-vs-new-data behavior, complexity, underfitting/overfitting and bias/variance.</Heading><div className={styles.explain}><div><span>📝</span><p>“But if the model got 100% on training data, doesn't that prove it learned everything?”</p></div><section><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Generalization means... Underfitting... Overfitting... A perfect train score can... Bias/variance..."/><footer><span>{text.length} chars</span><button onClick={explain}>CHECK EXPLANATION</button></footer>{feedback&&<p className={progress.completedTasks["explain-generalization"]?styles.feedbackGood:styles.feedbackHint}>{feedback}</p>}</section></div><TaskStamp done={Boolean(progress.completedTasks["explain-generalization"])}>Explain generalization, underfitting and overfitting.</TaskStamp></LessonSection>
  <section className={styles.gate}><div>SECTIONS<strong>{read}/9</strong></div><div>TASKS<strong>{done}/9</strong></div><div className={quizOpen?styles.open:""}>QUIZ<strong>{quizOpen?"OPEN":"LOCKED"}</strong></div></section><section className={styles.quizSection}><h2>New data is the exam.</h2><Quiz progress={progress} open={quizOpen}/></section>
  <section className={styles.footer}><div><small>MENTAL MODEL</small><h2>Fit the pattern — not every accident in the sample.</h2></div><Link href="/lessons/reinforcement-learning">← LESSON 11</Link><div><small>NEXT</small><b>Train / Validation / Test</b><span>build queue</span></div></section>
 </main>
}
