"use client";
import Link from "next/link";import {useState} from "react";import {LessonProgressApi} from "@/components/course/lesson-shell";import {LessonSection,TaskStamp} from "@/components/course/lesson-primitives";import {tokenizerA,tokenId} from "@/components/lessons/tokens-tokenization/tokenizer-data";import {cosine,points,queryVectors,vector8} from "@/components/lessons/embeddings-vectors/embedding-data";import {Cluster,DebugLayer,debugCases,defs,exam,words} from "./module-3-capstone-data";import styles from "./module-3-capstone.module.css";
type Props={progress:LessonProgressApi};
export function Module3CapstoneLesson({progress}:Props){
 const [text,setText]=useState("The puppy rides in a red truck.");const [stage,setStage]=useState(0);const [placements,setPlacements]=useState<Record<string,Cluster>>({});const [drag,setDrag]=useState("");const [metricSeen,setMetricSeen]=useState<string[]>([]);const [query,setQuery]=useState("pet");const [searches,setSearches]=useState<string[]>([]);const [limit,setLimit]=useState(10);const [multi,setMulti]=useState("");const [annSeen,setAnnSeen]=useState<string[]>([]);const [debug,setDebug]=useState<Record<number,DebugLayer>>({});const [quizAnswers,setQuizAnswers]=useState<Record<number,number>>({});const [feedback,setFeedback]=useState("");
 const tokens=tokenizerA(text),ids=tokens.map(tokenId),vectors=tokens.map(vector8);const tasks=defs.filter(([,t])=>progress.completedTasks[t]).length,rooms=defs.filter(([id])=>progress.visitedSections.has(id)).length,unlocked=tasks===8&&rooms===8;const lights=defs.map(([,t])=>!!progress.completedTasks[t]);const ranked=[...points].sort((a,b)=>cosine([b.x,b.y],queryVectors[query])-cosine([a.x,a.y],queryVectors[query]));
 const advance=()=>{const n=Math.min(4,stage+1);setStage(n);if(n===4)progress.completeTask("m3-build-pipeline")};
 const drop=(cluster:Cluster)=>{if(!drag)return;const n={...placements,[drag]:cluster};setPlacements(n);setDrag("");if(words.every(w=>n[w.word]===w.cluster))progress.completeTask("m3-place-words")};
 const seeMetric=(m:string)=>{const n=metricSeen.includes(m)?metricSeen:[...metricSeen,m];setMetricSeen(n);if(n.length===3)progress.completeTask("m3-compare-metrics")};
 const runSearch=(q:string)=>{setQuery(q);const n=searches.includes(q)?searches:[...searches,q];setSearches(n);if(n.length===3)progress.completeTask("m3-semantic-search")};
 const seeAnn=(m:string)=>{const n=annSeen.includes(m)?annSeen:[...annSeen,m];setAnnSeen(n);if(n.length===2)progress.completeTask("m3-ann-choice")};
 const diagnose=(i:number,a:DebugLayer)=>{const n={...debug,[i]:a};setDebug(n);if(debugCases.every((c,j)=>n[j]===c.answer))progress.completeTask("m3-debug-pipeline")};
 const submit=()=>{const s=exam.reduce((n,q,i)=>n+(quizAnswers[i]===q.c?1:0),0),p=s>=10;progress.saveQuiz(s,p);setFeedback(p?`MODULE 3 MASTERED · ${s}/12`:`${s}/12. Need 10/12.`)};
 return <main className={styles.root}>
 <section className={styles.hero}><div><span className={styles.eyebrow}>MODULE 3 · BOSS LAB</span><h1>Turn language into searchable geometry.</h1><p>Build the full pipeline, place concepts in semantic space, stay inside the token budget, retrieve by meaning, and debug the exact layer that breaks.</p></div><div className={styles.console}><b>LANGUAGE PIPELINE</b><div className={styles.lights}>{lights.map((on,i)=><i key={i} className={on?styles.on:""}/>)}</div><strong>{tasks}/8 missions</strong><p>{rooms}/8 rooms inspected</p></div></section>
 <LessonSection id="pipeline" onVisit={progress.markVisited} className={styles.scene}><TaskStamp done={!!progress.completedTasks["m3-build-pipeline"]}>MISSION 01 · PIPELINE</TaskStamp><h2>Text → tokens → IDs → embeddings → geometry.</h2><input className={styles.input} value={text} onChange={e=>{setText(e.target.value);setStage(0)}}/><div className={styles.pipeline}>{["TEXT","TOKENS","TOKEN IDs","EMBEDDINGS","VECTOR SPACE"].map((s,i)=><span key={s} style={{display:"contents"}}><div className={`${styles.step} ${i<=stage?styles.done:""}`}><b>{s}</b><small>{i===1&&stage>=1?`${tokens.length} pieces`:i===2&&stage>=2?ids.slice(0,3).join(", "):i===3&&stage>=3?`${vectors[0]?.length||0}D vectors`:""}</small></div>{i<4&&<b className={styles.arrow}>→</b>}</span>)}</div><button className={styles.button} onClick={advance}>Advance pipeline →</button></LessonSection>
 <LessonSection id="place-words" onVisit={progress.markVisited} className={styles.scene}><TaskStamp done={!!progress.completedTasks["m3-place-words"]}>MISSION 02 · SEMANTIC SPACE</TaskStamp><h2>Drag concepts into nearby meaning regions.</h2><div className={styles.wordBank}>{words.filter(w=>!placements[w.word]).map(w=><span key={w.word} draggable onDragStart={()=>setDrag(w.word)} className={styles.word}>{w.word}</span>)}</div><div className={styles.clusters}>{(["animals","vehicles","fruit"] as Cluster[]).map(c=><div key={c} className={styles.cluster} onDragOver={e=>e.preventDefault()} onDrop={()=>drop(c)}><h3>{c}</h3>{words.filter(w=>placements[w.word]===c).map(w=><span key={w.word} draggable onDragStart={()=>setDrag(w.word)} className={styles.word}>{w.word}</span>)}</div>)}</div></LessonSection>
 <LessonSection id="metric-room" onVisit={progress.markVisited} className={styles.scene}><TaskStamp done={!!progress.completedTasks["m3-compare-metrics"]}>MISSION 03 · METRICS</TaskStamp><h2>Know what your distance function cares about.</h2><div className={styles.controls}>{["cosine","dot","euclidean"].map(m=><button key={m} className={styles.button} onClick={()=>seeMetric(m)}>{m}</button>)}</div><div className={styles.stats}><div className={styles.stat}><span>Cosine</span><b>direction</b></div><div className={styles.stat}><span>Dot</span><b>angle + magnitude</b></div><div className={styles.stat}><span>Euclidean</span><b>coordinate distance</b></div></div><p>Metrics inspected: {metricSeen.length}/3</p></LessonSection>
 <LessonSection id="search-room" onVisit={progress.markVisited} className={styles.scene}><TaskStamp done={!!progress.completedTasks["m3-semantic-search"]}>MISSION 04 · SEMANTIC SEARCH</TaskStamp><h2>Retrieve by vector neighborhood.</h2><div className={styles.controls}>{Object.keys(queryVectors).map(q=><button key={q} className={styles.button} onClick={()=>runSearch(q)}>{q}</button>)}</div><div className={styles.results}>{ranked.slice(0,4).map(p=><div className={styles.result} key={p.id}><span>{p.label}</span><b>{cosine([p.x,p.y],queryVectors[query]).toFixed(3)}</b></div>)}</div><p>Queries completed: {searches.length}/3</p></LessonSection>
 <LessonSection id="budget-room" onVisit={progress.markVisited} className={styles.scene}><TaskStamp done={!!progress.completedTasks["m3-token-budget"]}>MISSION 05 · TOKEN BUDGET</TaskStamp><h2>Fit the model’s positions, not your word count.</h2><div className={styles.controls}><label>Limit {limit} <input type="range" min="3" max="20" value={limit} onChange={e=>setLimit(+e.target.value)}/></label><button className={styles.button} onClick={()=>{if(tokens.length<=limit)progress.completeTask("m3-token-budget");}}>Validate budget</button></div><div className={styles.meter}><i style={{width:`${Math.min(100,tokens.length/limit*100)}%`,background:tokens.length>limit?"#ff7770":undefined}}/></div><p>{tokens.length} tokenizer-A pieces / limit {limit}. {tokens.length>limit?"Overflow — raise budget or shorten input.":"Fits."}</p></LessonSection>
 <LessonSection id="multimodal-room" onVisit={progress.markVisited} className={styles.scene}><TaskStamp done={!!progress.completedTasks["m3-multimodal-match"]}>MISSION 06 · MULTIMODAL MATCH</TaskStamp><h2>Choose the image embedding closest to “a dog running”.</h2><div className={styles.controls}>{[{id:"dog",label:"🐕 running dog",score:.94},{id:"car",label:"🚗 city car",score:.18},{id:"pear",label:"🍐 pear",score:.07}].map(x=><button key={x.id} className={`${styles.button} ${multi===x.id?(x.id==="dog"?styles.correct:styles.wrong):""}`} onClick={()=>{setMulti(x.id);if(x.id==="dog")progress.completeTask("m3-multimodal-match")}}>{x.label}</button>)}</div></LessonSection>
 <LessonSection id="ann-room" onVisit={progress.markVisited} className={styles.scene}><TaskStamp done={!!progress.completedTasks["m3-ann-choice"]}>MISSION 07 · EXACT VS ANN</TaskStamp><h2>Choose a retrieval strategy at one million vectors.</h2><div className={styles.controls}><button className={styles.button} onClick={()=>seeAnn("exact")}>Exact: 1,000,000 candidates</button><button className={styles.button} onClick={()=>seeAnn("ann")}>ANN: ~320 candidates</button></div><div className={styles.stats}><div className={styles.stat}><span>Exact recall</span><b>100%</b></div><div className={styles.stat}><span>ANN recall proxy</span><b>~96%</b></div><div className={styles.stat}><span>ANN latency</span><b>much lower</b></div></div></LessonSection>
 <LessonSection id="debug-room" onVisit={progress.markVisited} className={styles.scene}><TaskStamp done={!!progress.completedTasks["m3-debug-pipeline"]}>MISSION 08 · DEBUG</TaskStamp><h2>Find the broken layer.</h2><div className={styles.caseGrid}>{debugCases.map((c,i)=><div className={styles.case} key={c.text}><p>{c.text}</p>{(["tokenizer","embedding","retrieval"] as DebugLayer[]).map(a=><button key={a} className={debug[i]===a?(a===c.answer?styles.correct:styles.wrong):""} onClick={()=>diagnose(i,a)}>{a}</button>)}</div>)}</div></LessonSection>
 <section className={styles.exam}><h2>Module 3 Mastery Exam</h2>{!unlocked?<div className={styles.locked}>Locked: {tasks}/8 missions · {rooms}/8 rooms.</div>:<>{exam.map((q,i)=><div className={styles.question} key={q.q}><strong>{i+1}. {q.q}</strong>{q.o.map((o,j)=><button key={o} className={quizAnswers[i]===j?styles.selected:""} onClick={()=>setQuizAnswers(a=>({...a,[i]:j}))}>{o}</button>)}</div>)}<button className={styles.button} onClick={submit}>Submit mastery exam</button>{feedback&&<div className={styles.feedback}>{feedback}</div>}</>}<div className={styles.footer}><Link href="/lessons/embeddings-vectors">← Embeddings</Link><Link href="/">Course map →</Link></div></section>
 </main>
}
