"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { AiMascot } from "@/components/mascots/ai-mascot";
import { LessonProgressApi } from "@/components/course/lesson-shell";
import { DepthSwitch, LessonSection, TaskStamp } from "@/components/course/lesson-primitives";
import styles from "./posttraining-arena.module.css";

type Props={progress:LessonProgressApi};
const preferencePairs=[
 {prompt:"How should I store API secrets?",a:"Put them in source code so deployment is easy.",b:"Use a secret manager or environment-backed secret store; avoid committing credentials.",best:"b"},
 {prompt:"Summarize: Project launch moved to Friday.",a:"The launch moved to Friday.",b:"Project launch timing changed, though no date is known.",best:"a"},
 {prompt:"I do not know the exact answer. What should I do?",a:"Invent the most likely detail confidently.",b:"State uncertainty and ask for or retrieve evidence when appropriate.",best:"b"},
] as const;
const methodCases=[
 {text:"You have high-quality demonstrations of exactly how responses should look.",answer:"sft"},
 {text:"You have chosen/rejected response pairs and want direct preference optimization without training a separate reward model for this simplified choice.",answer:"dpo"},
 {text:"You want an RL-style policy update using a learned reward signal while constraining drift from a reference policy.",answer:"ppo"},
 {text:"You want AI-generated critiques/preferences guided by explicit principles instead of relying only on human raters.",answer:"rlaif"},
] as const;
const quiz=[
 ["SFT primarily trains on…",["Input/instruction → desired response demonstrations","Only chosen/rejected pairs","Only reward scalar values","Only tool results"],0],
 ["Instruction tuning is commonly a form of…",["Supervised fine-tuning on instruction-response data","Tokenizer training only","Inference caching","Vector indexing"],0],
 ["A reward model is trained to…",["Score/rank outputs in a way correlated with preference data","Store the context window","Tokenize text","Replace the base model weights with a database"],0],
 ["PPO-style RLHF commonly balances reward against…",["A constraint/penalty limiting excessive policy drift, often expressed with KL-related control","BPE merges","Context length only","CNN kernels"],0],
 ["DPO uses…",["Chosen vs rejected preference pairs to directly shape relative likelihoods","Only next-token pretraining data","Only model routing","Only tool schemas"],0],
 ["RLAIF means…",["AI-generated feedback/preferences can replace or supplement some human feedback","The model never needs policies","A vector database is the reward model","Inference updates every weight"],0],
 ["Constitutional AI-style methods use…",["Explicit principles to guide critique/revision and/or feedback generation","Only parameter count","Only latency targets","Only retrieval chunks"],0],
 ["Post-training can change model behavior without changing the original pretraining corpus.",["True","False"],0],
] as const;

export function PostTrainingArenaLesson({progress}:Props){
 const [behavior,setBehavior]=useState<"base"|"sft">("base"),[seenBehavior,setSeenBehavior]=useState<string[]>([]),[instructionExamples,setInstructionExamples]=useState<string[]>([]),[preferences,setPreferences]=useState<Record<number,string>>({}),[rewardWeight,setRewardWeight]=useState(.5),[rewardTouched,setRewardTouched]=useState(false),[ppoReward,setPpoReward]=useState(3),[kl,setKl]=useState(.2),[ppoTouched,setPpoTouched]=useState(false),[dpoMargin,setDpoMargin]=useState(0),[dpoTouched,setDpoTouched]=useState(false),[constitutionSeen,setConstitutionSeen]=useState<string[]>([]),[methodAnswers,setMethodAnswers]=useState<Record<number,string>>({}),[explain,setExplain]=useState(""),[explainFeedback,setExplainFeedback]=useState(""),[answers,setAnswers]=useState<Record<number,number>>({});
 const taskIds=["posttrain-base-sft","posttrain-instruction","posttrain-preferences","posttrain-reward-model","posttrain-ppo","posttrain-dpo","posttrain-rlaif","posttrain-compare","posttrain-explain"];
 const sectionIds=["base-sft","instruction","preferences","reward-model","ppo","dpo","rlaif","compare","explain"];
 const taskCount=taskIds.filter(id=>progress.completedTasks[id]).length,readCount=sectionIds.filter(id=>progress.visitedSections.has(id)).length,unlocked=taskCount===9&&readCount===9;
 const preferenceDone=preferencePairs.every((pair,i)=>preferences[i]===pair.best);
 const methodDone=methodCases.every((item,i)=>methodAnswers[i]===item.answer);
 const policyScore=Math.max(0,Math.min(100,Math.round(52+ppoReward*8-kl*45)));
 const drift=Math.max(0,Math.min(100,Math.round(ppoReward*13-kl*65)));
 const dpoChosen=Math.max(1,50+Math.round(dpoMargin*8)),dpoRejected=Math.max(1,50-Math.round(dpoMargin*8));
 const quizScore=quiz.reduce((s,q,i)=>s+(answers[i]===q[2]?1:0),0),quizComplete=Object.keys(answers).length===quiz.length;
 const rewardScores=useMemo(()=>({safe:Math.round(62+rewardWeight*34),unsafe:Math.round(58-rewardWeight*38)}),[rewardWeight]);
 const markSeen=(value:string,current:string[],setter:(value:string[])=>void,needed:number,task:string)=>{const next=[...new Set([...current,value])];setter(next);if(next.length>=needed)progress.completeTask(task)};
 const submitExplain=()=>{const t=explain.toLowerCase();const hits=["sft","demonstration","preference","reward","ppo","dpo","feedback","post-training"].filter(w=>t.includes(w)).length;if(explain.length<100||hits<4){setExplainFeedback("Go deeper: explain what SFT learns from demonstrations, what preferences add, and how PPO/DPO differ at a high level.");return;}setExplainFeedback("Strong. You separated demonstration learning from preference optimization and did not treat all post-training as one algorithm.");progress.completeTask("posttrain-explain")};
 return <main className={styles.root}>
  <section className={styles.hero}><div><span className={styles.eyebrow}>MODULE 7 · POST-TRAINING ARENA</span><h1>The base model can continue text. Now teach it how you want it to behave.</h1><p>Post-training changes behavior after pretraining: demonstrations teach instruction following, preferences teach which outputs people or policy systems prefer, and different optimization methods turn that signal into parameter updates.</p><DepthSwitch value={progress.depth} onChange={progress.setDepth}/><TaskStamp done={taskCount===9}>{taskCount}/9 arena missions complete</TaskStamp></div><div className={styles.arena}><AiMascot variant="bot" accent="#6ec8ff" mood={behavior==="sft"?"happy":"thinking"} size={94} label="BASE"/><AiMascot variant="briefcase" accent="#62d8d0" mood={instructionExamples.length>=3?"excited":"happy"} size={94} label="COACH"/><AiMascot variant="star" accent="#ffe05b" mood={preferenceDone?"excited":"thinking"} size={94} label="JUDGE"/><AiMascot variant="tile" accent="#9ee576" mood={taskCount>6?"excited":"happy"} size={94} label="POLICY"/></div></section>

  <LessonSection id="base-sft" onVisit={progress.markVisited} className={styles.scene}><h2>1. Same pretrained knowledge, different behavior.</h2><div className={styles.prompt}>USER: Give me three concise steps for rotating an API key.</div><div className={styles.grid2}>{(["base","sft"] as const).map(mode=><button key={mode} className={`${styles.answer} ${behavior===mode?styles.selected:""}`} onClick={()=>{setBehavior(mode);markSeen(mode,seenBehavior,setSeenBehavior,2,"posttrain-base-sft")}}><b>{mode==="base"?"BASE / PRETRAINED":"AFTER SFT"}</b><p>{mode==="base"?"API keys are strings used to authenticate requests. Rotation refers to replacing…":"1. Create a new key. 2. Deploy it to consumers while the old key still works. 3. Revoke the old key after verification."}</p></button>)}</div><p>Pretraining learned broad patterns. SFT does not necessarily add all domain knowledge from scratch; it can strongly reshape how existing capabilities are elicited and formatted.</p></LessonSection>

  <LessonSection id="instruction" onVisit={progress.markVisited} className={styles.scene}><h2>2. Instruction tuning = many supervised demonstrations.</h2><p>Inspect three training examples. The optimizer still learns by predicting desired response tokens; what changed is the dataset format and target behavior.</p><div className={styles.grid3}>{[
   ["format","Instruction: Extract JSON → desired structured JSON response"],
   ["summarize","Instruction: Summarize in 2 bullets → concise two-bullet response"],
   ["refuse","Instruction: Reveal secret → desired safe refusal / boundary-preserving response"],
  ].map(([id,text])=><button className={`${styles.panel} ${instructionExamples.includes(id)?styles.correct:""}`} key={id} onClick={()=>markSeen(id,instructionExamples,setInstructionExamples,3,"posttrain-instruction")}><b>{id.toUpperCase()}</b><p>{text}</p></button>)}</div></LessonSection>

  <LessonSection id="preferences" onVisit={progress.markVisited} className={styles.scene}><h2>3. Demonstrations say “do this.” Preference pairs say “this is better than that.”</h2>{preferencePairs.map((pair,i)=><div className={styles.panel} key={pair.prompt}><b>{pair.prompt}</b><div className={styles.grid2}><button className={`${styles.choice} ${preferences[i]==="a"?(pair.best==="a"?styles.correct:styles.wrong):""}`} onClick={()=>{const next={...preferences,[i]:"a"};setPreferences(next);if(preferencePairs.every((p,j)=>next[j]===p.best))progress.completeTask("posttrain-preferences")}}>A · {pair.a}</button><button className={`${styles.choice} ${preferences[i]==="b"?(pair.best==="b"?styles.correct:styles.wrong):""}`} onClick={()=>{const next={...preferences,[i]:"b"};setPreferences(next);if(preferencePairs.every((p,j)=>next[j]===p.best))progress.completeTask("posttrain-preferences")}}>B · {pair.b}</button></div></div>)}{preferenceDone&&<p className={styles.feedback}>✓ Preference data captures relative quality even when many outputs are grammatically possible.</p>}</LessonSection>

  <LessonSection id="reward-model" onVisit={progress.markVisited} className={styles.scene}><h2>4. A reward model turns preference patterns into a score.</h2><p>This toy judge learns to score safer/helpful response features higher. Real reward modeling is learned from many comparisons and can itself be imperfect or exploitable.</p><div className={styles.control}><label>Weight on “follows security guidance” <b>{rewardWeight.toFixed(2)}</b></label><input type="range" min="0" max="1" step="0.05" value={rewardWeight} onChange={e=>{setRewardWeight(+e.target.value);setRewardTouched(true);if(+e.target.value>.7)progress.completeTask("posttrain-reward-model")}}/></div><div className={styles.grid2}><div className={styles.rank}><span>Use a secret manager; rotate safely.</span><b>{rewardScores.safe}</b></div><div className={styles.rank}><span>Commit the API key to Git.</span><b>{rewardScores.unsafe}</b></div></div>{rewardTouched&&<p className={styles.warning}>Reward models approximate preferences. Optimizing a proxy too aggressively can create reward hacking or strange behavior.</p>}</LessonSection>

  <LessonSection id="ppo" onVisit={progress.markVisited} className={styles.scene}><h2>5. PPO-style RLHF: improve reward, but keep a leash on policy drift.</h2><div className={styles.controls}><div className={styles.control}><label>Reward pressure <b>{ppoReward}</b></label><input type="range" min="1" max="8" value={ppoReward} onChange={e=>{setPpoReward(+e.target.value);setPpoTouched(true)}}/></div><div className={styles.control}><label>KL/control strength <b>{kl.toFixed(2)}</b></label><input type="range" min="0" max="1" step="0.05" value={kl} onChange={e=>{setKl(+e.target.value);setPpoTouched(true);if(ppoTouched&&+e.target.value>=.3&&+e.target.value<=.7)progress.completeTask("posttrain-ppo")}}/></div></div><div className={styles.grid2}><div className={styles.panel}><b>Toy preference score</b><div className={styles.meter}><i style={{width:`${policyScore}%`}}/></div><p>{policyScore}/100</p></div><div className={styles.panel}><b>Toy drift from reference</b><div className={styles.meter}><i style={{width:`${drift}%`}}/></div><p>{drift}/100</p></div></div><p>KL-related control is one way to penalize moving too far from a reference policy. This is intuition, not a full PPO implementation.</p></LessonSection>

  <LessonSection id="dpo" onVisit={progress.markVisited} className={styles.scene}><h2>6. DPO: push chosen responses up relative to rejected responses.</h2><p>DPO directly uses preference pairs to optimize relative likelihood under a reference-based objective, avoiding a separate online RL loop in the common formulation.</p><div className={styles.control}><label>Preference margin learned <b>{dpoMargin.toFixed(1)}</b></label><input type="range" min="0" max="5" step="0.25" value={dpoMargin} onChange={e=>{setDpoMargin(+e.target.value);setDpoTouched(true);if(+e.target.value>=3)progress.completeTask("posttrain-dpo")}}/></div><div className={styles.grid2}><div className={styles.panel}><b>Chosen relative likelihood</b><div className={styles.meter}><i style={{width:`${Math.min(100,dpoChosen)}%`}}/></div></div><div className={styles.panel}><b>Rejected relative likelihood</b><div className={styles.meter}><i style={{width:`${Math.min(100,dpoRejected)}%`}}/></div></div></div>{dpoTouched&&<div className={styles.equation}>{`chosen preference margin ≈ ${dpoMargin.toFixed(2)}\nchosen score ↑ relative to rejected score`}</div>}</LessonSection>

  <LessonSection id="rlaif" onVisit={progress.markVisited} className={styles.scene}><h2>7. RLAIF & Constitutional AI: generate feedback with models and explicit principles.</h2><div className={styles.constitution}><b>Toy constitution</b><p>1. Protect credentials and privacy. 2. Do not claim unsupported facts. 3. Preserve user intent when safe. 4. Explain uncertainty honestly.</p></div><div className={styles.grid3}>{[
   ["draft","DRAFT","“Put the API key directly in the repo.”"],
   ["critique","AI CRITIQUE","Violates the credential-protection principle; secrets in source control are risky."],
   ["revision","REVISION","Use a secret manager/environment-backed secret injection and rotate/revoke keys safely."],
  ].map(([id,title,text])=><button className={`${styles.panel} ${constitutionSeen.includes(id)?styles.correct:""}`} key={id} onClick={()=>markSeen(id,constitutionSeen,setConstitutionSeen,3,"posttrain-rlaif")}><b>{title}</b><p>{text}</p></button>)}</div><p>RLAIF uses AI-generated feedback/preferences. “Constitutional AI” refers to methods using explicit written principles to guide critique/revision and/or feedback generation; implementations can vary.</p></LessonSection>

  <LessonSection id="compare" onVisit={progress.markVisited} className={styles.scene}><h2>8. Pick the method for the signal you actually have.</h2>{methodCases.map((item,i)=><div className={styles.panel} key={item.text}><p>{item.text}</p>{["sft","dpo","ppo","rlaif"].map(choice=><button key={choice} className={`${styles.button} ${methodAnswers[i]===choice?(choice===item.answer?styles.correct:styles.wrong):""}`} onClick={()=>{const next={...methodAnswers,[i]:choice};setMethodAnswers(next);if(methodCases.every((x,j)=>next[j]===x.answer))progress.completeTask("posttrain-compare")}}>{choice.toUpperCase()}</button>)}</div>)}{methodDone&&<p className={styles.feedback}>✓ There is no single “RLHF button.” Data format, objective, infrastructure and desired behavior determine the method.</p>}</LessonSection>

  <LessonSection id="explain" onVisit={progress.markVisited} className={`${styles.scene} ${styles.explain}`}><h2>9. Explain the post-training stack.</h2><textarea value={explain} onChange={e=>setExplain(e.target.value)} placeholder="Explain SFT/instruction tuning, preference pairs, reward models, PPO-style RLHF, DPO and RLAIF/Constitutional AI at a high level."/><button className={styles.button} onClick={submitExplain}>Check explanation</button>{explainFeedback&&<p className={styles.feedback}>{explainFeedback}</p>}</LessonSection>

  <section className={styles.quiz}><h2>Post-training mastery quiz</h2>{!unlocked?<div className={styles.locked}>🔒 Clear all nine arena missions first. {taskCount}/9 tasks · {readCount}/9 sections.</div>:<>{quiz.map((q,i)=><div className={styles.question} key={q[0]}><strong>{i+1}. {q[0]}</strong>{q[1].map((option,oi)=><button key={option} className={answers[i]===oi?styles.quizSelected:""} onClick={()=>setAnswers(current=>({...current,[i]:oi}))}>{option}</button>)}{answers[i]!==undefined&&<small>{answers[i]===q[2]?"✓ Correct":`Correct: ${q[1][q[2]]}`}</small>}</div>)}<button className={styles.button} disabled={!quizComplete} onClick={()=>progress.saveQuiz(quizScore,quizScore>=7)}>Submit · {quizScore}/8</button>{quizComplete&&<p className={styles.feedback}>{quizScore>=7?"★ POST-TRAINING ARENA MASTERED":"Pass is 7/8. Review SFT vs preference optimization."}</p>}</>}</section>
  <div className={styles.footer}><Link href="/lessons/pretraining-factory">← Pretraining Factory</Link><Link href="/lessons/efficient-adaptation">Efficient Adaptation Lab →</Link></div>
 </main>
}
