"use client";

import Link from "next/link";
import { AnimatePresence, motion, Reorder } from "motion/react";
import { ReactNode, useEffect, useMemo, useState } from "react";
import { LessonProgressApi } from "@/components/course/lesson-shell";
import { DepthSwitch, LessonSection, TaskStamp } from "@/components/course/lesson-primitives";
import { symbolicNeuralSections } from "@/content/course";
import { ExplanationDepth } from "@/lib/course-progress";
import styles from "./symbolic-vs-neural.module.css";

type Props = { progress: LessonProgressApi };
type Mind = "symbolic" | "neural";
type DepthCopy = Record<ExplanationDepth, ReactNode>;

const intro: Record<Mind, DepthCopy> = {
  symbolic: {
    simple: <>Knowledge is written as <strong>named things, facts and rules</strong> the computer can follow.</>,
    real: <>Symbolic AI represents concepts explicitly and performs operations such as rule matching, search, logic and planning over them.</>,
    expert: <>Symbolic systems operate over discrete representations — predicates, rules, graphs, constraints, programs or search states — with explicit semantics and often inspectable inference paths.</>,
  },
  neural: {
    simple: <>Knowledge is spread across <strong>many learned numbers</strong> that become useful after seeing examples.</>,
    real: <>Neural systems learn distributed representations and decision boundaries by adjusting weights from data.</>,
    expert: <>Neural models encode statistical structure in high-dimensional parameter tensors and latent activations rather than a human-readable inventory of facts and IF/THEN rules.</>,
  },
};

const proofEdges = [
  { from: "MILO", to: "DOG", label: "is a" },
  { from: "DOG", to: "MAMMAL", label: "is a" },
  { from: "MAMMAL", to: "ANIMAL", label: "is a" },
  { from: "ANIMAL", to: "NEEDS FOOD", label: "rule" },
] as const;

const trainExamples = [
  { id:"cat1", icon:"🐱", label:"CAT", tone:"warm" }, { id:"dog1", icon:"🐶", label:"DOG", tone:"cool" },
  { id:"cat2", icon:"🐈", label:"CAT", tone:"warm" }, { id:"dog2", icon:"🐕", label:"DOG", tone:"cool" },
  { id:"cat3", icon:"😺", label:"CAT", tone:"warm" }, { id:"dog3", icon:"🦮", label:"DOG", tone:"cool" },
] as const;

const repairRules = [
  { id:"fur", text:"IF has_fur → MAMMAL", correct:false },
  { id:"dog-mammal", text:"DOG → is_a → MAMMAL", correct:true },
  { id:"food", text:"IF hungry → NEEDS FOOD", correct:false },
] as const;

const compareRows = [
  { label:"Explicit reasoning path", symbolic:94, neural:35 },
  { label:"Learns from raw examples", symbolic:18, neural:96 },
  { label:"Works with fuzzy perception", symbolic:28, neural:92 },
  { label:"Easy to encode hard constraints", symbolic:95, neural:46 },
  { label:"Needs hand-authored knowledge", symbolic:88, neural:24 },
  { label:"Scales naturally to pixels/audio/text", symbolic:25, neural:95 },
] as const;

const hybridCorrect = ["Neural perception", "Symbolic constraints", "Human approval", "Action"];

const quizQuestions = [
  { q:"What is most characteristic of symbolic AI?", options:["All behavior lives in billions of hidden weights","Concepts, facts, rules or search states are represented explicitly","It can only generate images","It never uses algorithms"], correct:1, why:"Symbolic AI works with explicit representations such as facts, predicates, rules, constraints and search states." },
  { q:"What is most characteristic of neural AI?", options:["Every decision is one readable IF statement","Useful behavior is learned into distributed weights/representations from data","It requires no data","It cannot classify images"], correct:1, why:"Neural systems learn statistical structure by adjusting many parameters rather than relying only on hand-authored symbolic rules." },
  { q:"Why can a symbolic knowledge graph be easy to audit?", options:["It is always correct","You can often inspect the exact facts and rule chain used for an inference","It has no software","It never changes"], correct:1, why:"Its semantics and inference steps are often explicit, although the rules can still be incomplete or wrong." },
  { q:"What commonly breaks a neural learner?", options:["Only missing semicolons","Bad, biased, mislabeled or unrepresentative training data","Using any examples","Having probabilities"], correct:1, why:"Learned behavior depends strongly on the quality and coverage of training data and objective." },
  { q:"What commonly breaks a symbolic system?", options:["Only GPU memory","Missing rules, wrong facts, combinatorial search or brittle knowledge coverage","Any explicit policy","Using logic"], correct:1, why:"If the needed knowledge/rule is absent or the search becomes huge, symbolic reasoning can fail even when its reasoning is transparent." },
  { q:"What is a sensible hybrid pattern?", options:["Neural perception → symbolic constraints → human approval/action","Delete all rules and all models","Always put action before validation","Use a neural model for exact legal limits with no guardrails"], correct:0, why:"Neural models can handle fuzzy perception while symbolic constraints and approvals enforce explicit non-negotiable rules." },
  { q:"Best mental model?", options:["Symbolic AI is old and useless","Neural AI is always superior","They encode intelligence differently and can complement each other","They are synonyms"], correct:2, why:"Neither mechanism dominates every task. Good systems choose or combine them based on uncertainty, data, constraints, interpretability and cost." },
] as const;

function getDepth(copy:DepthCopy,depth:ExplanationDepth){return copy[depth]}
function Heading({n,kicker,title,children}:{n:string;kicker:string;title:string;children:ReactNode}){return <div className={styles.heading}><span>{n}</span><div><b>{kicker}</b><h2>{title}</h2><p>{children}</p></div></div>}

function Logi({active=false}:{active?:boolean}){return <motion.div className={styles.logi} animate={{y:active?[0,-10,0]:[0,-5,0],rotate:[0,-1,1,0]}} transition={{duration:active?1.5:3.1,repeat:Infinity}}><div><span>◇</span><i/><i/><b>IF</b></div><strong>LOGI</strong></motion.div>}
function Nova({active=false}:{active?:boolean}){return <motion.div className={styles.nova} animate={{scale:active?[1,1.06,.99,1]:[1,1.025,1],rotate:[0,2,-1,0]}} transition={{duration:active?1.6:3.4,repeat:Infinity}}><div>{Array.from({length:9}).map((_,i)=><i key={i}/>)}<span/><span/><b>∿</b></div><strong>NOVA</strong></motion.div>}

function Quiz({progress,unlocked}:{progress:LessonProgressApi;unlocked:boolean}){
  const [answers,setAnswers]=useState<Record<number,number>>({});const [submitted,setSubmitted]=useState(false);const count=Object.keys(answers).length;const score=quizQuestions.reduce((s,q,i)=>s+(answers[i]===q.correct?1:0),0);const passed=score>=6;
  if(!unlocked)return <div className={styles.quizLock}><motion.span animate={{rotate:[-4,4,-4],scale:[1,1.08,1]}} transition={{duration:2.1,repeat:Infinity}}>🔒</motion.span><h3>Lab exam locked.</h3><p>Inspect, break and repair both kinds of intelligence first.</p></div>;
  const submit=()=>{if(count===quizQuestions.length){setSubmitted(true);progress.saveQuiz(score,passed)}};
  return <div className={styles.quiz}>{quizQuestions.map((q,i)=><div className={styles.question} key={q.q}><h3><span>{i+1}</span>{q.q}</h3><div>{q.options.map((o,j)=><motion.button key={o} whileTap={{scale:.97}} disabled={submitted} onClick={()=>setAnswers(a=>({...a,[i]:j}))} className={`${answers[i]===j?styles.selected:""} ${submitted&&j===q.correct?styles.correct:""} ${submitted&&answers[i]===j&&j!==q.correct?styles.wrong:""}`}><i>{String.fromCharCode(65+j)}</i>{o}</motion.button>)}</div>{submitted&&<p>{q.why}</p>}</div>)}{!submitted?<button className={`${styles.submit} tactile`} disabled={count!==quizQuestions.length} onClick={submit}>CHECK BOTH MINDS →</button>:<motion.div className={`${styles.result} ${passed?styles.pass:styles.fail}`} initial={{scale:.9}} animate={{scale:1}}><strong>{score}/7</strong><div><h3>{passed?"Two mental models unlocked.":"Repair the weak spots."}</h3><p>{passed?"You can now distinguish explicit symbolic reasoning from learned neural representation — and know why hybrids exist.":"Pass is 6/7. Use the explanations to fix the gaps."}</p></div>{!passed&&<button onClick={()=>{setAnswers({});setSubmitted(false)}}>TRY AGAIN</button>}</motion.div>}</div>;
}

export function SymbolicVsNeuralLesson({progress}:Props){
  const [inspected,setInspected]=useState<Mind[]>([]);const [proofStep,setProofStep]=useState(0);const [fed,setFed]=useState<string[]>([]);const [trained,setTrained]=useState(false);const [hidden,setHidden]=useState(0);
  const [symbolicBroken,setSymbolicBroken]=useState(false);const [repairChoice,setRepairChoice]=useState("");const [symbolicRepaired,setSymbolicRepaired]=useState(false);
  const [corruptId,setCorruptId]=useState("dog2");const [noiseOn,setNoiseOn]=useState(false);const [neuralRepaired,setNeuralRepaired]=useState(false);
  const [decisionSeen,setDecisionSeen]=useState<Mind[]>([]);const [traceAnswer,setTraceAnswer]=useState<Mind|"">("");const [compareSeen,setCompareSeen]=useState<Mind[]>([]);
  const [pipeline,setPipeline]=useState(["Human approval","Neural perception","Action","Symbolic constraints"]);const [pipelineRun,setPipelineRun]=useState(false);const [explanation,setExplanation]=useState("");const [feedback,setFeedback]=useState("");

  const inspect=(m:Mind)=>setInspected(s=>s.includes(m)?s:[...s,m]);
  const decisionInspect=(m:Mind)=>setDecisionSeen(s=>s.includes(m)?s:[...s,m]);
  const compareInspect=(m:Mind)=>setCompareSeen(s=>s.includes(m)?s:[...s,m]);
  const pipelineCorrect=pipeline.join("|")===hybridCorrect.join("|");
  const neuralConfidence=trained?Math.max(51,94-(noiseOn&&!neuralRepaired?31:0)-Math.abs(hidden-62)*.15):50;

  useEffect(()=>{if(inspected.length===2)progress.completeTask("inspect-two-minds")},[inspected.length,progress]);
  useEffect(()=>{if(proofStep===proofEdges.length)progress.completeTask("prove-symbolic-chain")},[proofStep,progress]);
  useEffect(()=>{if(trained&&fed.length===trainExamples.length&&hidden>=45)progress.completeTask("train-neural-pattern")},[trained,fed.length,hidden,progress]);
  useEffect(()=>{if(symbolicBroken&&symbolicRepaired)progress.completeTask("repair-symbolic")},[symbolicBroken,symbolicRepaired,progress]);
  useEffect(()=>{if(noiseOn&&neuralRepaired)progress.completeTask("repair-neural")},[noiseOn,neuralRepaired,progress]);
  useEffect(()=>{if(decisionSeen.length===2&&traceAnswer==="symbolic")progress.completeTask("inspect-decisions")},[decisionSeen.length,traceAnswer,progress]);
  useEffect(()=>{if(compareSeen.length===2)progress.completeTask("compare-symbolic-neural")},[compareSeen.length,progress]);
  useEffect(()=>{if(pipelineCorrect&&pipelineRun)progress.completeTask("build-hybrid-brain")},[pipelineCorrect,pipelineRun,progress]);

  const required=symbolicNeuralSections.map(s=>s.taskId);const done=required.filter(id=>progress.completedTasks[id]).length;const read=symbolicNeuralSections.filter(s=>progress.visitedSections.has(s.id)).length;const quizUnlocked=done===9&&read===9;
  const feed=(id:string)=>setFed(s=>s.includes(id)?s:[...s,id]);
  const nextProof=()=>{if(proofStep<proofEdges.length)setProofStep(s=>s+1)};
  const chooseRepair=(id:string)=>{setRepairChoice(id);if(repairRules.find(r=>r.id===id)?.correct)setSymbolicRepaired(true)};
  const submitExplain=()=>{const t=explanation.toLowerCase();const hits=["symbol","rule","fact","logic","explicit","neural","weight","data","example","learn","hybrid"].filter(k=>t.includes(k));if(explanation.trim().length<90){setFeedback("Use at least three sentences: explain symbolic representation, neural learned representation, and one reason to combine them.");return}if(hits.length<6){setFeedback("Add mechanism words: facts/rules/logic for symbolic AI; data/examples/weights/learning for neural AI; then explain a hybrid.");return}setFeedback("Strong. You described how knowledge is represented — not just which approach is newer.");progress.completeTask("explain-symbolic-neural")};

  return <main className={`${styles.lesson} lesson-main`}>
    <section className={styles.hero}><div><span className={styles.tag}>MODULE 01 · LESSON 05</span><h1>Two ways to<br/><em>store intelligence.</em></h1><p>One writes knowledge in explicit symbols and rules. The other learns distributed patterns in weights. Neither is magic — and neither wins every problem.</p><DepthSwitch value={progress.depth} onChange={progress.setDepth}/></div><div className={styles.heroLab}><div className={styles.half}><Logi active/><span>FACTS · RULES · LOGIC</span></div><div className={styles.split}>×</div><div className={styles.half}><Nova active/><span>DATA · WEIGHTS · PATTERNS</span></div></div></section>

    <LessonSection id="open-two-minds" onVisit={progress.markVisited} className={styles.sceneA}><Heading n="01" kicker="CLICK · X-RAY" title="Open both minds.">Do not memorize names. Inspect <strong>where each system puts its knowledge.</strong></Heading><div className={styles.mindGrid}><motion.button onClick={()=>inspect("symbolic")} className={inspected.includes("symbolic")?styles.mindDone:""} whileHover={{y:-5}}><Logi active={inspected.includes("symbolic")}/><h3>SYMBOLIC MIND</h3><div className={styles.symbolShelf}><span>DOG</span><i>is a</i><span>MAMMAL</span><i>→</i><span>ANIMAL</span></div><p>{getDepth(intro.symbolic,progress.depth)}</p><small>{inspected.includes("symbolic")?"INSPECTED ✓":"CLICK TO INSPECT"}</small></motion.button><motion.button onClick={()=>inspect("neural")} className={inspected.includes("neural")?styles.mindDone:""} whileHover={{y:-5}}><Nova active={inspected.includes("neural")}/><h3>NEURAL MIND</h3><div className={styles.weightShelf}>{[24,62,41,86,53,74,33,68].map((v,i)=><i key={i} style={{height:`${v}%`}}/>)}</div><p>{getDepth(intro.neural,progress.depth)}</p><small>{inspected.includes("neural")?"INSPECTED ✓":"CLICK TO INSPECT"}</small></motion.button></div><TaskStamp done={Boolean(progress.completedTasks["inspect-two-minds"])}>Inspect both representation styles.</TaskStamp></LessonSection>

    <LessonSection id="knowledge-graph" onVisit={progress.markVisited} className={styles.sceneB}><Heading n="02" kicker="CLICK · PROVE" title="Symbolic reasoning can show its work.">Prove the statement <strong>“Milo needs food”</strong> by walking through explicit facts and rules.</Heading><div className={styles.proofLab}><div className={styles.graph}>{["MILO","DOG","MAMMAL","ANIMAL","NEEDS FOOD"].map((node,i)=><motion.div key={node} className={`${styles.node} ${i<=proofStep?styles.nodeLit:""}`} animate={i===proofStep?{scale:[1,1.08,1]}:undefined}>{node}</motion.div>)}{proofEdges.map((edge,i)=><button key={edge.to} className={`${styles.edge} ${i<proofStep?styles.edgeDone:""}`} disabled={i!==proofStep} onClick={nextProof}><span>{edge.label}</span><b>→</b></button>)}</div><div className={styles.proofPanel}><Logi active/><span>QUERY</span><h3>Does MILO need food?</h3><p>{proofStep===0?"Start with the explicit fact: MILO is a DOG.":proofStep<4?`Proof has ${proofStep} explicit step${proofStep>1?"s":""}. Continue the chain.`:"Yes. The full proof path is visible and inspectable."}</p><strong>{proofStep===4?"PROVED ✓":`${proofStep}/4 edges proven`}</strong></div></div><TaskStamp done={Boolean(progress.completedTasks["prove-symbolic-chain"])}>Click the four explicit inference edges in order.</TaskStamp></LessonSection>

    <LessonSection id="neural-learner" onVisit={progress.markVisited} className={styles.sceneC}><Heading n="03" kicker="FEED · TRAIN · SLIDE" title="A neural learner stores the pattern differently.">Feed labeled examples, train the toy network, then move its hidden activation knob and inspect the prediction.</Heading><div className={styles.trainLab}><div className={styles.examples}>{trainExamples.map(e=><motion.button key={e.id} onClick={()=>feed(e.id)} className={`${styles.example} ${fed.includes(e.id)?styles.fed:""}`} whileTap={{scale:.94}}><span>{e.icon}</span><strong>{e.label}</strong><small>{fed.includes(e.id)?"FED ✓":"feed"}</small></motion.button>)}</div><div className={styles.network}><div className={styles.layers}>{[4,6,5,2].map((count,li)=><div key={li}>{Array.from({length:count}).map((_,i)=><motion.i key={i} animate={trained?{scale:[1,1.15,1],opacity:[.5,1,.7]}:undefined} transition={{delay:(li+i)*.04,duration:.9}} style={{background:trained?`hsl(${220+li*25} 85% ${62-i*2}%)`:"#ddd"}}/>)}</div>)}</div><button disabled={fed.length<6} className="tactile" onClick={()=>setTrained(true)}>{trained?"NETWORK TRAINED ✓":"TRAIN ON 6 EXAMPLES"}</button></div><div className={styles.testPanel}><Nova active={trained}/><span>MYSTERY INPUT</span><strong>🐈‍⬛</strong><label>HIDDEN ACTIVATION <b>{hidden}</b><input type="range" min="0" max="100" value={hidden} onChange={e=>setHidden(Number(e.target.value))}/></label><div className={styles.confidence}><span>CAT</span><i><motion.b animate={{width:`${neuralConfidence}%`}}/></i><strong>{Math.round(neuralConfidence)}%</strong></div><p>The learned pattern lives across weights and activations, not as one rule saying “black cat → CAT.”</p></div></div><TaskStamp done={Boolean(progress.completedTasks["train-neural-pattern"])}>Feed all six examples, train, and move hidden activation past 45.</TaskStamp></LessonSection>

    <LessonSection id="break-symbolic" onVisit={progress.markVisited} className={styles.sceneD}><Heading n="04" kicker="BREAK · REPAIR" title="Transparent can still be brittle.">Delete one piece of knowledge. The proof fails cleanly — then you repair the missing rule.</Heading><div className={styles.breakGrid}><div className={styles.brokenGraph}><button onClick={()=>{setSymbolicBroken(true);setSymbolicRepaired(false);setRepairChoice("")}} className="tactile">✂ DELETE DOG → MAMMAL RULE</button><div><span>MILO</span><b>→</b><span>DOG</span><b className={symbolicBroken&&!symbolicRepaired?styles.missing:""}>{symbolicBroken&&!symbolicRepaired?"✕ MISSING ✕":"→"}</b><span>MAMMAL</span><b>→</b><span>ANIMAL</span></div><p>{symbolicBroken&&!symbolicRepaired?"The engine cannot prove the chain. It does not invent the missing ontology relation.":symbolicRepaired?"Rule restored. The proof path works again.":"Break the graph to see explicit knowledge failure."}</p></div><div className={styles.repairBox}><Logi active={symbolicBroken}/><h3>PATCH KNOWLEDGE BASE</h3>{repairRules.map(r=><button key={r.id} disabled={!symbolicBroken||symbolicRepaired} onClick={()=>chooseRepair(r.id)} className={`${repairChoice===r.id?(r.correct?styles.correctPick:styles.wrongPick):""}`}>{r.text}</button>)}{symbolicRepaired&&<strong>ONTOLOGY REPAIRED ✓</strong>}</div></div><TaskStamp done={Boolean(progress.completedTasks["repair-symbolic"])}>Delete the relation, then choose the exact missing symbolic rule.</TaskStamp></LessonSection>

    <LessonSection id="break-neural" onVisit={progress.markVisited} className={styles.sceneE}><Heading n="05" kicker="POISON · DIAGNOSE" title="A learned system can absorb bad examples.">Mislabel one training example. Watch confidence fall, identify the poisoned point, then repair the data.</Heading><div className={styles.poisonLab}><div className={styles.dataSheet}><header><span>TRAINING ROW</span><span>LABEL</span><span>STATUS</span></header>{trainExamples.map(e=>{const corrupt=noiseOn&&e.id===corruptId&&!neuralRepaired;return <button key={e.id} onClick={()=>{if(noiseOn&&e.id===corruptId)setNeuralRepaired(true)}} className={corrupt?styles.corrupt:neuralRepaired&&e.id===corruptId?styles.repaired:""}><span>{e.icon} {e.id}</span><strong>{corrupt?(e.label==="CAT"?"DOG":"CAT"):e.label}</strong><i>{corrupt?"?":neuralRepaired&&e.id===corruptId?"✓":"·"}</i></button>})}</div><div className={styles.poisonControls}><Nova active={noiseOn}/><button onClick={()=>{setNoiseOn(true);setNeuralRepaired(false);setCorruptId("dog2")}} className="tactile">☣ FLIP ONE TRAINING LABEL</button><div className={styles.metric}><span>TEST CONFIDENCE</span><strong>{noiseOn&&!neuralRepaired?63:94}%</strong><i><motion.b animate={{width:`${noiseOn&&!neuralRepaired?63:94}%`}}/></i></div><p>{!noiseOn?"Introduce one mislabeled example.":!neuralRepaired?"One row is wrong. Click the suspicious row to repair its label.":"Data repaired. The lesson: learned systems can faithfully learn mistakes present in their data."}</p></div></div><TaskStamp done={Boolean(progress.completedTasks["repair-neural"])}>Poison one label, find it and repair the dataset.</TaskStamp></LessonSection>

    <LessonSection id="inside-decision" onVisit={progress.markVisited} className={styles.sceneF}><Heading n="06" kicker="X-RAY · COMPARE" title="“Why?” means different things in each system.">Inspect the same decision through a symbolic trace and a neural activation view.</Heading><div className={styles.decisionGrid}><motion.button onClick={()=>decisionInspect("symbolic")} className={decisionSeen.includes("symbolic")?styles.seenDecision:""} whileHover={{y:-4}}><Logi/><h3>SYMBOLIC TRACE</h3><ol><li>invoice.total = €12,400</li><li>policy.limit = €10,000</li><li>IF total &gt; limit → approval_required</li><li className={styles.finalTrace}>RESULT: HOLD</li></ol><small>{decisionSeen.includes("symbolic")?"TRACE OPEN ✓":"CLICK TO OPEN TRACE"}</small></motion.button><motion.button onClick={()=>decisionInspect("neural")} className={decisionSeen.includes("neural")?styles.seenDecision:""} whileHover={{y:-4}}><Nova/><h3>NEURAL ACTIVATIONS</h3><div className={styles.heatmap}>{Array.from({length:30}).map((_,i)=><i key={i} style={{opacity:.2+((i*17)%80)/100}}/>)}</div><p>Risk score emerges from many learned interactions. Attribution tools can help inspect influence, but there is no single authored IF line equal to the whole result.</p><small>{decisionSeen.includes("neural")?"ACTIVATIONS OPEN ✓":"CLICK TO INSPECT"}</small></motion.button></div><div className={styles.traceQuestion}><strong>Which system can naturally show the exact authored proof rule above?</strong><button onClick={()=>setTraceAnswer("symbolic")} className={traceAnswer==="symbolic"?styles.chosen:""}>SYMBOLIC</button><button onClick={()=>setTraceAnswer("neural")} className={traceAnswer==="neural"?styles.chosen:""}>NEURAL</button>{traceAnswer==="neural"&&<span>Neural models can be inspected, but this particular exact policy proof is represented explicitly in the symbolic rule.</span>}</div><TaskStamp done={Boolean(progress.completedTasks["inspect-decisions"])}>Inspect both decisions and answer the traceability question.</TaskStamp></LessonSection>

    <LessonSection id="tradeoff-console" onVisit={progress.markVisited} className={styles.sceneG}><Heading n="07" kicker="SWITCH · COMPARE" title="Pick the representation that matches the problem.">Inspect both profiles. These are teaching tendencies, not universal laws — implementation details matter.</Heading><div className={styles.compareLab}><div className={styles.compareTabs}><button className={compareSeen.includes("symbolic")?styles.tabSeen:""} onClick={()=>compareInspect("symbolic")}><Logi/><span>SYMBOLIC PROFILE</span></button><button className={compareSeen.includes("neural")?styles.tabSeen:""} onClick={()=>compareInspect("neural")}><Nova/><span>NEURAL PROFILE</span></button></div><div className={styles.compareTable}><header><span>PROPERTY</span><b>SYMBOLIC</b><b>NEURAL</b></header>{compareRows.map(row=><div key={row.label}><strong>{row.label}</strong><i><b style={{width:`${row.symbolic}%`}}/></i><i><b style={{width:`${row.neural}%`}}/></i></div>)}</div></div><div className={styles.compareNote}><b>DO NOT TURN THIS INTO A RELIGION.</b><span>Rules can be learned, neural systems can use structured tools, and modern production systems often combine mechanisms.</span></div><TaskStamp done={Boolean(progress.completedTasks["compare-symbolic-neural"])}>Inspect both profiles.</TaskStamp></LessonSection>

    <LessonSection id="hybrid-brain" onVisit={progress.markVisited} className={styles.sceneH}><Heading n="08" kicker="DRAG · RUN" title="Give each mechanism the job it is good at.">Build a document-processing pipeline where neural perception handles messy pixels, symbolic rules enforce policy, and a human approves the costly edge case.</Heading><div className={styles.hybridLab}><div className={styles.invoice}><span>📄</span><strong>INVOICE PHOTO</strong><small>blurry image · €18,950 · foreign vendor</small></div><Reorder.Group axis="x" values={pipeline} onReorder={p=>{setPipeline(p);setPipelineRun(false)}} className={styles.pipeline}>{pipeline.map(item=><Reorder.Item key={item} value={item} whileDrag={{scale:1.07,rotate:2,zIndex:3}} className={`${styles.pipeBlock} ${item.startsWith("Neural")?styles.pipeNeural:item.startsWith("Symbolic")?styles.pipeSymbolic:item.startsWith("Human")?styles.pipeHuman:styles.pipeAction}`}><span>{item.startsWith("Neural")?"◉":item.startsWith("Symbolic")?"◇":item.startsWith("Human")?"👤":"→"}</span><strong>{item}</strong><small>drag</small></Reorder.Item>)}</Reorder.Group><div className={styles.pipelineFooter}><p>{pipelineCorrect?"Neural perception extracts uncertain visual information → symbolic constraints apply explicit policy → human approves → action happens.":"Put perception first and irreversible action last. Explicit constraints should evaluate the extracted information before approval/action."}</p><button disabled={!pipelineCorrect} className="tactile" onClick={()=>setPipelineRun(true)}>RUN HYBRID BRAIN</button></div><AnimatePresence>{pipelineRun&&<motion.div className={styles.pipelineResult} initial={{scaleX:.15,opacity:0}} animate={{scaleX:1,opacity:1}}><span>TEXT EXTRACTED 96%</span><span>LIMIT RULE TRIGGERED</span><span>HUMAN REVIEW</span><strong>HOLD</strong></motion.div>}</AnimatePresence></div><TaskStamp done={Boolean(progress.completedTasks["build-hybrid-brain"])}>Arrange and run the neuro-symbolic pipeline.</TaskStamp></LessonSection>

    <LessonSection id="explain-symbolic-neural" onVisit={progress.markVisited} className={styles.sceneI}><Heading n="09" kicker="TYPE · TEACH" title="Explain where the knowledge lives.">Teach the difference without saying “old AI vs new AI.” Then give one reason to combine them.</Heading><div className={styles.explainLab}><div className={styles.listener}><span>🧠</span><p>“So symbolic AI has rules and neural AI just... thinks?”</p></div><div><textarea value={explanation} onChange={e=>setExplanation(e.target.value)} placeholder="Symbolic AI represents... Neural AI learns... A hybrid can..."/><footer><span>{explanation.length} chars</span><button className="tactile" onClick={submitExplain}>CHECK EXPLANATION</button></footer>{feedback&&<motion.p className={progress.completedTasks["explain-symbolic-neural"]?styles.feedbackGood:styles.feedbackHint} initial={{opacity:0,y:6}} animate={{opacity:1,y:0}}>{feedback}</motion.p>}</div></div><TaskStamp done={Boolean(progress.completedTasks["explain-symbolic-neural"])}>Explain both representations and a hybrid use.</TaskStamp></LessonSection>

    <section className={styles.gate}><div><span>SECTIONS</span><strong>{read}/9</strong></div><div><span>TASKS</span><strong>{done}/9</strong></div><div className={quizUnlocked?styles.gateOpen:""}><span>QUIZ</span><strong>{quizUnlocked?"OPEN":"LOCKED"}</strong></div></section>
    <section className={styles.quizSection}><header><span>LESSON 05 QUIZ</span><h2>Rules, weights — or both?</h2><p>Pass 6/7. The point is representation, failure modes and system design.</p></header><Quiz progress={progress} unlocked={quizUnlocked}/></section>
    <section className={styles.footer}><div><span>MENTAL MODEL</span><h2>Symbols make knowledge explicit. Neural nets learn distributed patterns.</h2><p>Modern AI systems can use either mechanism — and powerful systems often compose them with tools, constraints and human oversight.</p></div><Link href="/lessons/generative-vs-predictive">← LESSON 04</Link><div><small>NEXT</small><strong>Training vs Inference</strong><span>build queue</span></div></section>
  </main>
}
