"use client";

import Link from "next/link";
import { motion, Reorder } from "motion/react";
import { useMemo, useState } from "react";
import { AiMascot } from "@/components/mascots/ai-mascot";
import { LessonProgressApi } from "@/components/course/lesson-shell";
import { DepthSwitch, LessonSection, TaskStamp } from "@/components/course/lesson-primitives";
import { tokenizerA } from "@/components/lessons/tokens-tokenization/tokenizer-data";
import styles from "./context-backpack.module.css";

type Props={progress:LessonProgressApi};
type BlockType="system"|"user"|"history"|"tool"|"doc"|"summary";
type Block={id:string;type:BlockType;title:string;text:string;importance:number};

const palette:Block[]=[
{id:"sys",type:"system",title:"System instructions",text:"You are a careful travel assistant. Never invent booking availability. Prefer verified evidence.",importance:10},
{id:"user",type:"user",title:"Current user request",text:"Find me a quiet hotel near the conference center and explain why it fits.",importance:10},
{id:"history",type:"history",title:"Conversation history",text:"Earlier the user said they prefer quiet rooms, late check-in, breakfast, a gym, and no nightclub nearby. They also discussed three unrelated restaurant ideas and a laptop purchase.",importance:6},
{id:"doc",type:"doc",title:"Retrieved hotel document",text:"Hotel Linden is 350m from the conference center. Quiet-floor rooms available, breakfast 06:30–10:30, gym open 24h.",importance:9},
{id:"tool",type:"tool",title:"Booking tool result",text:"Live availability check: Hotel Linden has two quiet-floor rooms for the requested dates. Rate: 184 EUR/night.",importance:9},
{id:"noise",type:"doc",title:"Irrelevant old document",text:"A long archived article about airport runway resurfacing, parking regulations, coffee beans, baggage dimensions and a 2019 conference sponsor list.",importance:1},
];
const cacheCases=[
{text:"Reuse the exact same long prompt prefix so the provider does not have to recompute it from scratch.",answer:"prompt"},
{text:"Reuse intermediate attention K/V tensors from previous decoded positions while generating the next token.",answer:"kv"},
{text:"Your app stores/reuses an assembled context or result outside the model so it can avoid rebuilding/re-fetching it.",answer:"context"},
] as const;
const quiz=[
["Context is best described as…",["Information available to the model for the current computation/request","Everything the model ever learned","Only the system prompt","Persistent memory automatically"],0],
["A tool result can become part of context after…",["External code executes the tool and returns the result to the model/application","The model updates its weights","The tokenizer retrains","The GPU stores it forever"],0],
["Context overflow means…",["The assembled input exceeds the model/system token budget and must be handled","The model has too many parameters","The database is full","A gradient exploded"],0],
["Summarization can reduce context size, but…",["It may lose detail and introduce summary errors","It always preserves every token exactly","It changes model weights","It is the same as KV cache"],0],
["Lost-in-the-middle refers to…",["Long-context retrieval/usage quality sometimes degrading for information buried in the middle","A tokenizer losing spaces","A server losing a GPU","A model forgetting its weights"],0],
["Prompt cache and KV cache are identical.",["True","False"],1],
["Context engineering is broader than wording a prompt because it includes…",["Selecting, ordering, retrieving, compressing and managing all information the model sees","Only choosing font size","Only system prompts","Only fine-tuning"],0],
] as const;

const tokens=(text:string)=>tokenizerA(text).length;

export function ContextBackpackLesson({progress}:Props){
 const [bag,setBag]=useState<Block[]>([]),[limit,setLimit]=useState(80),[overflowed,setOverflowed]=useState(false),[repaired,setRepaired]=useState(false),[priorityChoices,setPriorityChoices]=useState<string[]>([]),[middleSeen,setMiddleSeen]=useState(false),[longLimit,setLongLimit]=useState(128),[longTouched,setLongTouched]=useState(false),[cacheAnswers,setCacheAnswers]=useState<Record<number,string>>({}),[explain,setExplain]=useState(""),[explainFeedback,setExplainFeedback]=useState(""),[answers,setAnswers]=useState<Record<number,number>>({});
 const used=useMemo(()=>bag.reduce((sum,b)=>sum+tokens(b.text),0),[bag]); const pct=Math.min(100,Math.round(used/limit*100)); const overloaded=used>limit;
 const requiredKinds=["system","user","history","doc","tool"];
 const packedKinds=new Set(bag.map(b=>b.type)); const basePacked=requiredKinds.every(kind=>packedKinds.has(kind as BlockType));
 const add=(block:Block)=>{if(bag.some(b=>b.id===block.id))return;const next=[...bag,block];setBag(next);if(requiredKinds.every(kind=>new Set(next.map(b=>b.type)).has(kind as BlockType)))progress.completeTask("pack-context")};
 const summarizeHistory=()=>{const next=bag.map(b=>b.id==="history"?{...b,id:"history-summary",type:"summary" as const,title:"Compressed history summary",text:"User prefers quiet rooms, late check-in, breakfast, gym, and no nightclub nearby.",importance:8}:b).filter(b=>b.id!=="noise");setBag(next);setRepaired(true);if(next.reduce((s,b)=>s+tokens(b.text),0)<=limit)progress.completeTask("repair-overflow")};
 const priorityCorrect=["sys","user","doc","tool"].every(id=>priorityChoices.includes(id))&&!priorityChoices.includes("noise");
 const cacheDone=cacheCases.every((item,i)=>cacheAnswers[i]===item.answer);
 const taskIds=["inspect-context-backpack","pack-context","overflow-context","repair-overflow","prioritize-context","inspect-lost-middle","compare-long-context","separate-cache-types","explain-context"];
 const sectionIds=["what-is-context","pack-context","overflow","truncate-compress","prioritize","lost-middle","long-context","cache-types","explain-context"];
 const taskCount=taskIds.filter(id=>progress.completedTasks[id]).length, readCount=sectionIds.filter(id=>progress.visitedSections.has(id)).length, quizUnlocked=taskCount===9&&readCount===9;
 const quizScore=quiz.reduce((s,q,i)=>s+(answers[i]===q[2]?1:0),0),quizComplete=Object.keys(answers).length===quiz.length;
 const mood=overloaded?"excited":pct>70?"thinking":"happy";
 const lostProfile=[82,68,54,43,38,44,55,69,84];
 const submitExplain=()=>{const text=explain.toLowerCase();const hits=["current","token","system","history","tool","document","select","compress","window"].filter(w=>text.includes(w)).length;if(explain.length<80||hits<4){setExplainFeedback("Go deeper: context is what the model can see now. Mention the token/window budget and at least two possible sources such as system instructions, history, documents or tool results.");return;}setExplainFeedback("Strong. You described context as a managed current working set, not permanent model memory.");progress.completeTask("explain-context")};
 return <main className={styles.root}>
  <section className={styles.hero}><div><span className={styles.eyebrow}>MODULE 6 · CONTEXT</span><h1>Your model has a backpack. It cannot carry everything.</h1><p>Context is the working information available for the current model computation. You decide what enters, what gets dropped, what is compressed, and what deserves precious token space.</p><DepthSwitch value={progress.depth} onChange={progress.setDepth}/><TaskStamp done={taskCount===9}>{taskCount}/9 context missions complete</TaskStamp></div><div className={styles.backpackStage}><AiMascot variant="bot" accent="#6ec6ff" mood={mood} size={105} label={overloaded?"OVERLOAD":pct>70?"HEAVY":"READY"}/><div className={styles.bag}><div className={styles.bagMeter}><motion.i animate={{width:`${pct}%`}}/></div><div className={styles.bagContents}>{bag.slice(0,6).map(b=><span key={b.id} className={styles.chip} data-type={b.type}>{b.title}</span>)}</div></div></div></section>

  <LessonSection id="what-is-context" onVisit={progress.markVisited} className={styles.scene}><h2>1. Open the backpack.</h2><p>The model's weights are learned long-term parameters. <b>Context</b> is different: it is the request-time working set — instructions, messages, evidence and tool results the model is allowed to see now.</p><div className={styles.grid3}>{[{t:"WEIGHTS",d:"Learned during training/post-training. Not rewritten for each normal chat turn."},{t:"CONTEXT",d:"Temporary working information supplied to this request/sequence."},{t:"MEMORY",d:"Application data persisted elsewhere and selectively retrieved back into context."}].map(card=><div className={styles.panel} key={card.t}><b>{card.t}</b><p>{card.d}</p></div>)}</div><button className={styles.button} onClick={()=>progress.completeTask("inspect-context-backpack")}>I can separate weights, context and memory</button></LessonSection>

  <LessonSection id="pack-context" onVisit={progress.markVisited} className={styles.scene}><h2>2. Pack the current request.</h2><p>Add the system instructions, user request, relevant history, retrieved evidence and a tool result. The model does not magically know tool output until the application puts that result back into its working context.</p><div className={styles.grid2}><div className={styles.palette}>{palette.slice(0,5).map(block=><button key={block.id} onClick={()=>add(block)}><b>{block.title}</b><small>{tokens(block.text)} tokens</small></button>)}</div><div className={styles.panel}><b>Bag contents · {used}/{limit} tokens</b><div className={styles.stack}>{bag.map(b=><div className={styles.stackItem} key={b.id}><div><b>{b.title}</b><small>{b.type} · {tokens(b.text)} tokens</small></div><button onClick={()=>setBag(current=>current.filter(x=>x.id!==b.id))}>×</button></div>)}</div></div></div>{basePacked&&<p className={styles.feedback}>✓ The complete request-time working set is packed.</p>}</LessonSection>

  <LessonSection id="overflow" onVisit={progress.markVisited} className={styles.scene}><h2>3. Now break the context window.</h2><p>Token limits apply to the assembled sequence. Add the irrelevant archive and shrink the model window until the bag no longer fits.</p><div className={styles.controls}><button className={styles.button} onClick={()=>add(palette[5])}>Add noisy archive</button><div className={styles.control}><label>Context budget <b>{limit} tokens</b></label><input type="range" min="36" max="100" value={limit} onChange={e=>{setLimit(+e.target.value);const now=used>+e.target.value;if(now){setOverflowed(true);progress.completeTask("overflow-context")}}}/></div></div><p className={overloaded?styles.warning:styles.feedback}>Used <b>{used}</b> / {limit}. {overloaded?"OVERFLOW: this exact assembled input no longer fits the toy window.":"Still fits. Shrink the limit or add more context."}</p></LessonSection>

  <LessonSection id="truncate-compress" onVisit={progress.markVisited} className={styles.scene}><h2>4. Repair overflow — but understand the trade-offs.</h2><div className={styles.grid3}><div className={styles.panel}><b>TRUNCATE</b><p>Drop some content. Fast, but you may cut away the exact evidence needed later.</p></div><div className={styles.panel}><b>SUMMARIZE</b><p>Rewrite long history into fewer tokens. Saves space, but detail can be lost or distorted.</p></div><div className={styles.panel}><b>SELECT</b><p>Retrieve/keep only relevant evidence. Often better than blindly stuffing every available document.</p></div></div><button className={styles.button} disabled={!overflowed} onClick={summarizeHistory}>Compress history + remove irrelevant archive</button>{repaired&&<p className={styles.feedback}>✓ Repaired: {bag.reduce((s,b)=>s+tokens(b.text),0)}/{limit} tokens. Smaller is not automatically better — the goal is useful evidence per token.</p>}</LessonSection>

  <LessonSection id="prioritize" onVisit={progress.markVisited} className={styles.scene}><h2>5. Context engineering is selection, not hoarding.</h2><p>You can keep only four blocks for the hotel answer. Choose what deserves the space.</p><div className={styles.palette}>{palette.map(block=><button key={block.id} className={priorityChoices.includes(block.id)?styles.correct:""} onClick={()=>{const next=priorityChoices.includes(block.id)?priorityChoices.filter(x=>x!==block.id):[...priorityChoices,block.id];setPriorityChoices(next);if(["sys","user","doc","tool"].every(id=>next.includes(id))&&!next.includes("noise")){progress.completeTask("prioritize-context")}}}><b>{block.title}</b><small>importance signal: {block.importance}/10</small></button>)}</div>{priorityCorrect&&<p className={styles.feedback}>✓ Strong selection. System constraints + current user goal + grounded document + live tool result beat irrelevant volume.</p>}</LessonSection>

  <LessonSection id="lost-middle" onVisit={progress.markVisited} className={styles.scene}><h2>6. Long context can have a middle problem.</h2><p>A simplified research finding/engineering intuition: some models or setups use information near the beginning/end more reliably than details buried deep in a long sequence. This is not a universal law, but it is a real failure mode worth testing.</p><div className={styles.middleTrack}>{lostProfile.map((v,i)=><motion.i key={i} animate={{height:`${v}%`}} style={{height:`${v}%`}}/>)}</div><div className={styles.controls}><button className={styles.button} onClick={()=>{setMiddleSeen(true);progress.completeTask("inspect-lost-middle")}}>Move critical evidence from slot 5 → near the answer</button></div>{middleSeen&&<p className={styles.feedback}>✓ Context placement can matter. Retrieval, chunk ordering and explicit recency can improve effective use — but should be evaluated, not assumed.</p>}</LessonSection>

  <LessonSection id="long-context" onVisit={progress.markVisited} className={styles.scene}><h2>7. Bigger window ≠ infinite understanding.</h2><div className={styles.control}><label>Advertised toy context window <b>{longLimit}K</b></label><input type="range" min="16" max="1024" step="16" value={longLimit} onChange={e=>{setLongLimit(+e.target.value);setLongTouched(true);if(+e.target.value>=512)progress.completeTask("compare-long-context")}}/></div><div className={styles.grid3}><div className={styles.panel}><b>Capacity</b><p>More positions can physically fit.</p></div><div className={styles.panel}><b>Quality</b><p>Effective recall/reasoning across those positions still needs evaluation.</p></div><div className={styles.panel}><b>Cost</b><p>Longer inputs can increase latency/compute and make relevance management harder.</p></div></div>{longTouched&&<p className={styles.feedback}>The window is a capacity boundary, not a guarantee that every token receives equal useful attention.</p>}</LessonSection>

  <LessonSection id="cache-types" onVisit={progress.markVisited} className={styles.scene}><h2>8. Three “cache” phrases, three different layers.</h2><div className={styles.grid3}>{cacheCases.map((item,i)=><div className={styles.cacheCard} key={item.text}><p>{item.text}</p>{["prompt","context","kv"].map(choice=><button key={choice} className={cacheAnswers[i]===choice?(choice===item.answer?styles.correct:styles.wrong):""} onClick={()=>{const next={...cacheAnswers,[i]:choice};setCacheAnswers(next);if(cacheCases.every((x,j)=>next[j]===x.answer))progress.completeTask("separate-cache-types")}}>{choice.toUpperCase()} cache</button>)}</div>)}</div>{cacheDone&&<p className={styles.feedback}>✓ Prompt-prefix reuse, application/context reuse and decode-time KV tensors are no longer one fuzzy concept.</p>}</LessonSection>

  <LessonSection id="explain-context" onVisit={progress.markVisited} className={`${styles.scene} ${styles.explain}`}><h2>9. Explain context without saying “memory.”</h2><textarea value={explain} onChange={e=>setExplain(e.target.value)} placeholder="What is context, where can it come from, what limits it, and what does context engineering do?"/><button className={styles.button} onClick={submitExplain}>Check my explanation</button>{explainFeedback&&<p className={styles.feedback}>{explainFeedback}</p>}</LessonSection>

  <section className={styles.quiz}><h2>Context mastery quiz</h2>{!quizUnlocked?<div className={styles.locked}>🔒 Finish all 9 scenes and tasks first. {taskCount}/9 tasks · {readCount}/9 sections.</div>:<>{quiz.map((q,i)=><div className={styles.question} key={q[0]}><strong>{i+1}. {q[0]}</strong>{q[1].map((option,oi)=><button key={option} className={answers[i]===oi?styles.selected:""} onClick={()=>setAnswers(current=>({...current,[i]:oi}))}>{option}</button>)}{answers[i]!==undefined&&<small>{answers[i]===q[2]?"✓ Correct":`Correct: ${q[1][q[2]]}`}</small>}</div>)}<button className={styles.button} disabled={!quizComplete} onClick={()=>progress.saveQuiz(quizScore,quizScore>=6)}>Submit · {quizScore}/7</button>{quizComplete&&<p className={styles.feedback}>{quizScore>=6?"★ CONTEXT MASTERED":"Pass is 6/7. Repack the backpack and retry."}</p>}</>}</section>
  <div className={styles.footer}><Link href="/lessons/module-5-capstone">← LLM generation</Link><Link href="/lessons/prompting-instruction-hierarchy">Prompting & hierarchy →</Link></div>
 </main>
}
