"use client";

import Link from "next/link";
import { motion } from "motion/react";
import { ReactNode, useEffect, useMemo, useState } from "react";
import { LessonProgressApi } from "@/components/course/lesson-shell";
import { DepthSwitch, LessonSection, TaskStamp } from "@/components/course/lesson-primitives";
import { sigmoid } from "@/lib/toy-neural-network";
import styles from "./weights-bias-activations.module.css";

type Props={progress:LessonProgressApi};
type ActivationChoice="relu"|"sigmoid"|"softmax"|"linear";
const sections=[{id:"weight-influence",taskId:"test-weight-influence"},{id:"bias-offset",taskId:"test-bias-offset"},{id:"linear-stack",taskId:"break-linear-stack"},{id:"relu",taskId:"explore-relu"},{id:"sigmoid",taskId:"explore-sigmoid"},{id:"softmax",taskId:"explore-softmax"},{id:"activation-router",taskId:"route-activations"},{id:"saturation",taskId:"inspect-saturation"},{id:"explain-activations",taskId:"explain-activations"}] as const;
const activationCases=[
 {id:"a1",text:"Hidden layer in a basic modern MLP where we want a cheap nonlinearity and positive-region gradient.",answer:"relu" as ActivationChoice},
 {id:"a2",text:"Single output representing probability of one binary class under a logistic model.",answer:"sigmoid" as ActivationChoice},
 {id:"a3",text:"Three mutually exclusive class logits that should become probabilities summing to 1.",answer:"softmax" as ActivationChoice},
 {id:"a4",text:"Regression output predicting an unconstrained house price/value before task-specific transforms.",answer:"linear" as ActivationChoice},
 {id:"a5",text:"Binary classifier final logit → probability between 0 and 1.",answer:"sigmoid" as ActivationChoice},
 {id:"a6",text:"Ten-class digit classifier final logits → class distribution.",answer:"softmax" as ActivationChoice},
 {id:"a7",text:"Hidden units in a simple teaching network where negative pre-activations should clamp to zero.",answer:"relu" as ActivationChoice},
 {id:"a8",text:"Output should be any real number, not normalized as a probability.",answer:"linear" as ActivationChoice}
] as const;
const quiz=[
 {q:"What does a weight control?",o:["Strength/sign of influence from one signal to another","The number of test rows","Whether the model is AGI","The browser theme"],c:0,w:"Weights are learned coefficients that scale incoming activations."},
 {q:"What does a bias do in z = w·x + b?",o:["Adds an offset so activation/threshold need not be anchored at zero input","Deletes a feature","Creates a dataset split","Only represents unfairness"],c:0,w:"Bias shifts the pre-activation and therefore where a unit turns on/off."},
 {q:"Why isn't stacking only linear layers enough for nonlinear patterns?",o:["The composition of linear/affine maps is still another affine map","GPUs cannot run linear math","Weights disappear","Bias becomes a label"],c:0,w:"Without nonlinear activations, depth does not create nonlinear decision structure."},
 {q:"ReLU(z) is...",o:["max(0,z)","1/(1+e^-z)","e^z / Σe^z across classes","z²"],c:0,w:"ReLU passes positive values and clamps negative values to zero."},
 {q:"Sigmoid is useful when...",o:["A scalar logit should map to a value between 0 and 1, such as binary probability","All hidden layers must sum to one","Predicting any unconstrained real value","Creating train/test splits"],c:0,w:"Sigmoid squashes a scalar to (0,1)."},
 {q:"Softmax differs from applying sigmoid independently because...",o:["Softmax couples class logits into a normalized distribution summing to 1","Softmax has no exponentials","Softmax is a training dataset","They are always identical"],c:0,w:"Softmax normalizes relative class logits jointly."},
 {q:"What is saturation?",o:["A region where activation changes very little as input changes, often yielding small derivatives","A checkpoint format","Too much data","A deterministic seed"],c:0,w:"Sigmoid/tanh can saturate at extremes, weakening gradient flow through those units."}
] as const;
function Heading({n,k,title,children}:{n:string;k:string;title:string;children:ReactNode}){return <div className={styles.heading}><span>{n}</span><div><b>{k}</b><h2>{title}</h2><p>{children}</p></div></div>}
function WeightBot({positive=true}:{positive?:boolean}){return <motion.div className={`${styles.weightBot} ${positive?styles.positive:styles.negative}`} animate={{rotate:positive?[0,2,0]:[0,-2,0],y:[0,-4,0]}} transition={{duration:2.7,repeat:Infinity}}><div><i/><i/><strong>{positive?"+W":"−W"}</strong></div><b>WEIGHT</b></motion.div>}
function BiasBot(){return <motion.div className={styles.biasBot} animate={{x:[0,6,0]}} transition={{duration:2.8,repeat:Infinity}}><div><i/><i/><strong>+b</strong></div><b>BIAS</b></motion.div>}
function ActivationBot(){return <motion.div className={styles.activationBot} animate={{scale:[1,1.05,1]}} transition={{duration:2.6,repeat:Infinity}}><div><i/><i/><strong>ƒ</strong></div><b>ACTIVATE</b></motion.div>}
function Quiz({progress,open}:{progress:LessonProgressApi;open:boolean}){const[a,setA]=useState<Record<number,number>>({});const[sub,setSub]=useState(false);const score=quiz.reduce((n,q,i)=>n+(a[i]===q.c?1:0),0);const pass=score>=6;if(!open)return <div className={styles.lock}>🎚️🔒<h3>Activation exam locked.</h3><p>Push every signal through the microscope first.</p></div>;return <div className={styles.quiz}>{quiz.map((q,i)=><section key={q.q}><h3><span>{i+1}</span>{q.q}</h3><div>{q.o.map((x,j)=><button disabled={sub} className={`${a[i]===j?styles.selected:""} ${sub&&j===q.c?styles.correct:""} ${sub&&a[i]===j&&j!==q.c?styles.wrong:""}`} onClick={()=>setA(v=>({...v,[i]:j}))} key={x}>{x}</button>)}</div>{sub&&<p>{q.w}</p>}</section>)}{!sub?<button disabled={Object.keys(a).length!==quiz.length} onClick={()=>{setSub(true);progress.saveQuiz(score,pass)}}>CHECK SIGNAL FLOW →</button>:<div className={`${styles.result} ${pass?styles.pass:styles.fail}`}><strong>{score}/7</strong><p>{pass?"You can separate learned influence, offset and nonlinearity.":"Pass is 6/7. Re-open the activations."}</p>{!pass&&<button onClick={()=>{setA({});setSub(false)}}>TRY AGAIN</button>}</div>}</div>}
export function WeightsBiasActivationsLesson({progress}:Props){
 const[input,setInput]=useState(.7);const[weight,setWeight]=useState(1);const[weightZones,setWeightZones]=useState<string[]>([]);const[bias,setBias]=useState(0);const[biasZones,setBiasZones]=useState<string[]>([]);const[linearChecks,setLinearChecks]=useState<number[]>([]);const[reluZ,setReluZ]=useState(-2);const[reluSeen,setReluSeen]=useState<string[]>([]);const[sigZ,setSigZ]=useState(0);const[sigSeen,setSigSeen]=useState<string[]>([]);const[logits,setLogits]=useState([1.5,.4,-.3]);const[softSeen,setSoftSeen]=useState<string[]>([]);const[choices,setChoices]=useState<Record<string,ActivationChoice>>({});const[satZ,setSatZ]=useState(0);const[satSeen,setSatSeen]=useState<string[]>([]);const[text,setText]=useState("");const[feedback,setFeedback]=useState("");
 const weighted=input*weight;const pre=weighted+bias;const relu=Math.max(0,reluZ);const sig=sigmoid(sigZ);const sigGrad=sig*(1-sig);const exps=logits.map(v=>Math.exp(v-Math.max(...logits)));const sum=exps.reduce((a,b)=>a+b,0);const soft=exps.map(v=>v/sum);const sat=sigmoid(satZ);const satGrad=sat*(1-sat);const routeOk=activationCases.every(x=>choices[x.id]===x.answer);
 useEffect(()=>{if(["neg","small","large"].every(z=>weightZones.includes(z)))progress.completeTask("test-weight-influence")},[weightZones,progress]);useEffect(()=>{if(["left","middle","right"].every(z=>biasZones.includes(z)))progress.completeTask("test-bias-offset")},[biasZones,progress]);useEffect(()=>{if(linearChecks.length>=4)progress.completeTask("break-linear-stack")},[linearChecks,progress]);useEffect(()=>{if(["negative","zero","positive"].every(z=>reluSeen.includes(z)))progress.completeTask("explore-relu")},[reluSeen,progress]);useEffect(()=>{if(["left","center","right"].every(z=>sigSeen.includes(z)))progress.completeTask("explore-sigmoid")},[sigSeen,progress]);useEffect(()=>{if(softSeen.length>=3)progress.completeTask("explore-softmax")},[softSeen,progress]);useEffect(()=>{if(routeOk)progress.completeTask("route-activations")},[routeOk,progress]);useEffect(()=>{if(["left-sat","center","right-sat"].every(z=>satSeen.includes(z)))progress.completeTask("inspect-saturation")},[satSeen,progress]);
 const required=sections.map(x=>x.taskId);const done=required.filter(x=>progress.completedTasks[x]).length;const read=sections.filter(x=>progress.visitedSections.has(x.id)).length;const open=done===9&&read===9;
 const markWeight=()=>{const z=weight<0?"neg":Math.abs(weight)<.6?"small":"large";setWeightZones(v=>v.includes(z)?v:[...v,z])};const markBias=()=>{const threshold=weight===0?0:-bias/weight;const z=threshold<-.5?"left":threshold>.5?"right":"middle";setBiasZones(v=>v.includes(z)?v:[...v,z])};const markRelu=()=>{const z=reluZ<0?"negative":reluZ===0?"zero":"positive";setReluSeen(v=>v.includes(z)?v:[...v,z])};const markSig=()=>{const z=sigZ<-3?"left":sigZ>3?"right":"center";setSigSeen(v=>v.includes(z)?v:[...v,z])};const changeLogit=(i:number,value:number)=>{setLogits(v=>v.map((x,j)=>j===i?value:x));setSoftSeen(v=>v.includes(String(i))?v:[...v,String(i)])};const markSat=()=>{const z=satZ<-5?"left-sat":satZ>5?"right-sat":"center";setSatSeen(v=>v.includes(z)?v:[...v,z])};
 const explain=()=>{const t=text.toLowerCase();const hits=["weight","influence","bias","offset","activation","nonlinear","relu","sigmoid","softmax","logit","satur"].filter(k=>t.includes(k));if(text.trim().length<125){setFeedback("Explain weight, bias, and at least two activation functions with what each one changes.");return}if(hits.length<8){setFeedback("Use mechanism words: weight/influence, bias/offset, nonlinear activation, ReLU, sigmoid, softmax/logits, saturation.");return}setFeedback("Strong. You separated the learned affine part from the nonlinear function applied afterward.");progress.completeTask("explain-activations")};
 const xSamples=[-2,-1,0,1,2];
 return <main className={`${styles.lesson} lesson-main`}>
 <section className={styles.hero}><div><span className={styles.tag}>MODULE 02 · LESSON 02</span><h1>SCALE.<br/>SHIFT.<br/><em>BEND.</em></h1><p>A neuron has three jobs: <strong>weights scale influence</strong>, <strong>bias shifts the pre-activation</strong>, and an <strong>activation function introduces the shape/nonlinearity</strong> the network needs.</p><DepthSwitch value={progress.depth} onChange={progress.setDepth}/></div><div className={styles.heroBots}><WeightBot/><BiasBot/><ActivationBot/><WeightBot positive={false}/></div></section>
 <LessonSection id="weight-influence" onVisit={progress.markVisited} className={styles.a}><Heading n="01" k="SLIDE · TEST 3 REGIMES" title="Weight changes both strength and direction of influence.">Hold input x fixed and move w from negative to near-zero to large positive. The weighted signal x·w flips sign and magnitude.</Heading><div className={styles.weightLab}><div className={styles.weightStage}><span>INPUT</span><strong>{input.toFixed(2)}</strong><motion.b animate={{scaleX:Math.max(.08,Math.abs(weight)/2),rotate:weight<0?180:0}}>→</motion.b><WeightBot positive={weight>=0}/><span>WEIGHTED SIGNAL</span><motion.strong key={weighted} initial={{scale:.8}} animate={{scale:1}}>{weighted.toFixed(3)}</motion.strong></div><div className={styles.controls}><label>INPUT x <b>{input.toFixed(2)}</b><input type="range" min="0" max="1" step=".05" value={input} onChange={e=>setInput(Number(e.target.value))}/></label><label>WEIGHT w <b>{weight.toFixed(2)}</b><input type="range" min="-2" max="2" step=".05" value={weight} onChange={e=>setWeight(Number(e.target.value))}/></label><button onClick={markWeight}>RECORD WEIGHT REGIME</button><p>Find negative, near-zero magnitude, and large-magnitude regimes. Seen {weightZones.length}/3.</p></div></div><TaskStamp done={Boolean(progress.completedTasks["test-weight-influence"])}>Test negative, small and large weight influence.</TaskStamp></LessonSection>
 <LessonSection id="bias-offset" onVisit={progress.markVisited} className={styles.b}><Heading n="02" k="SHIFT · MOVE THRESHOLD" title="Bias lets the neuron activate away from the origin.">For z = wx + b, changing b slides the zero-crossing threshold. With positive w, threshold is x = −b/w.</Heading><div className={styles.biasLab}><div className={styles.numberLine}><span>-2</span><i/><i/><i/><i/><i/><motion.b animate={{left:`${Math.max(3,Math.min(97,50+(-bias/(weight||.01))*22))}%`}}>z=0</motion.b><motion.strong animate={{left:`${50+input*22}%`}}>x</motion.strong></div><div className={styles.controls}><label>WEIGHT w <b>{weight.toFixed(2)}</b><input type="range" min=".2" max="2" step=".05" value={Math.max(.2,weight)} onChange={e=>setWeight(Number(e.target.value))}/></label><label>BIAS b <b>{bias.toFixed(2)}</b><input type="range" min="-2" max="2" step=".05" value={bias} onChange={e=>setBias(Number(e.target.value))}/></label><div className={styles.equation}>z = {weighted.toFixed(2)} + {bias.toFixed(2)} = <strong>{pre.toFixed(2)}</strong></div><button onClick={markBias}>RECORD THRESHOLD POSITION</button><p>Move z=0 left, near middle and right. Seen {biasZones.length}/3.</p></div></div><TaskStamp done={Boolean(progress.completedTasks["test-bias-offset"])}>Move the threshold through three regions.</TaskStamp></LessonSection>
 <LessonSection id="linear-stack" onVisit={progress.markVisited} className={styles.c}><Heading n="03" k="CLICK · PROVE THE COLLAPSE" title="Many linear layers without activation are still just one linear map.">Run four x values through y = 2(3x + 1) − 4. Then compare the algebraically collapsed y = 6x − 2. Same result every time.</Heading><div className={styles.linearLab}><div className={styles.linearMachine}><code>L1(x)=3x+1</code><b>→</b><code>L2(h)=2h−4</code><b>=</b><code>6x−2</code></div><div className={styles.linearSamples}>{xSamples.map((x,i)=>{const stacked=2*(3*x+1)-4,collapsed=6*x-2;return <button className={linearChecks.includes(i)?styles.checked:""} onClick={()=>setLinearChecks(v=>v.includes(i)?v:[...v,i])} key={x}><span>x={x}</span><code>stack {stacked}</code><code>collapsed {collapsed}</code><strong>{stacked===collapsed?"MATCH ✓":"?"}</strong></button>})}</div><p className={styles.note}>Depth becomes much more expressive when nonlinear activations are inserted between affine layers. Otherwise, the whole stack can be rewritten as one affine transformation.</p><TaskStamp done={Boolean(progress.completedTasks["break-linear-stack"])}>Verify at least four stacked-vs-collapsed examples.</TaskStamp></LessonSection>
 <LessonSection id="relu" onVisit={progress.markVisited} className={styles.d}><Heading n="04" k="SLIDE · RELU" title="ReLU: pass positive, clamp negative.">ReLU(z)=max(0,z). Slide across negative, exactly zero, and positive regions.</Heading><div className={styles.activationLab}><div className={styles.plot}><svg viewBox="0 0 100 70"><path d="M5 58 L50 58 L95 8" fill="none" stroke="currentColor" strokeWidth="4"/><line x1="50" y1="5" x2="50" y2="65"/><line x1="5" y1="58" x2="95" y2="58"/></svg><motion.i animate={{left:`${50+reluZ*10}%`,top:`${58-Math.max(0,reluZ)*10}%`}}/></div><div className={styles.activationConsole}><ActivationBot/><label>z <strong>{reluZ.toFixed(2)}</strong><input type="range" min="-4" max="4" step=".25" value={reluZ} onChange={e=>setReluZ(Number(e.target.value))}/></label><strong>ReLU(z) = {relu.toFixed(2)}</strong><button onClick={markRelu}>RECORD REGION</button><p>Negative: output 0. Positive: output follows z. At exactly zero, frameworks conventionally use a subgradient choice for optimization.</p></div></div><TaskStamp done={Boolean(progress.completedTasks["explore-relu"])}>Visit negative, zero and positive ReLU regions.</TaskStamp></LessonSection>
 <LessonSection id="sigmoid" onVisit={progress.markVisited} className={styles.e}><Heading n="05" k="SLIDE · SIGMOID" title="Sigmoid squashes a scalar into 0…1.">Move the logit across the S-curve and watch both output and derivative. Near extremes the curve becomes flat.</Heading><div className={styles.activationLab}><div className={styles.plot}><svg viewBox="0 0 100 70"><path d="M5 61 C22 61 29 59 38 52 C47 45 50 35 55 24 C62 10 72 8 95 8" fill="none" stroke="currentColor" strokeWidth="4"/><line x1="50" y1="5" x2="50" y2="65"/></svg><motion.i animate={{left:`${50+sigZ*7}%`,top:`${62-sig*54}%`}}/></div><div className={styles.activationConsole}><label>logit z <strong>{sigZ.toFixed(2)}</strong><input type="range" min="-6" max="6" step=".25" value={sigZ} onChange={e=>setSigZ(Number(e.target.value))}/></label><strong>σ(z) = {sig.toFixed(4)}</strong><code>derivative ≈ {sigGrad.toFixed(4)}</code><button onClick={markSig}>RECORD SIGMOID REGION</button><p>Use a scalar sigmoid output for common binary-probability parameterizations; hidden-layer use is possible but saturation can make deep optimization harder.</p></div></div><TaskStamp done={Boolean(progress.completedTasks["explore-sigmoid"])}>Visit far-left saturation, center and far-right saturation.</TaskStamp></LessonSection>
 <LessonSection id="softmax" onVisit={progress.markVisited} className={styles.f}><Heading n="06" k="SLIDE 3 LOGITS" title="Softmax turns competing class logits into a joint distribution.">Move each class logit. Increasing one changes all normalized probabilities because they share the same denominator.</Heading><div className={styles.softmaxLab}><div className={styles.logitControls}>{logits.map((v,i)=><label key={i}>CLASS {String.fromCharCode(65+i)} LOGIT <strong>{v.toFixed(2)}</strong><input type="range" min="-3" max="3" step=".1" value={v} onChange={e=>changeLogit(i,Number(e.target.value))}/></label>)}</div><div className={styles.softmaxBars}>{soft.map((p,i)=><div key={i}><span>{String.fromCharCode(65+i)}</span><i><motion.b animate={{width:`${p*100}%`}}/></i><strong>{(p*100).toFixed(1)}%</strong></div>)}<p>Sum = {(soft.reduce((a,b)=>a+b,0)*100).toFixed(1)}%</p></div></div><TaskStamp done={Boolean(progress.completedTasks["explore-softmax"])}>Move all three logits at least once.</TaskStamp></LessonSection>
 <LessonSection id="activation-router" onVisit={progress.markVisited} className={styles.g}><Heading n="07" k="ROUTE · CHOOSE OUTPUT SHAPE" title="Activation choice depends on what the layer/output must represent.">Classify eight situations as ReLU, sigmoid, softmax or linear. These are common teaching defaults, not universal laws.</Heading><div className={styles.router}>{activationCases.map(x=>{const c=choices[x.id];return <article className={c?(c===x.answer?styles.good:styles.bad):""} key={x.id}><p>{x.text}</p><div>{(["relu","sigmoid","softmax","linear"] as ActivationChoice[]).map(v=><button className={c===v?styles.active:""} onClick={()=>setChoices(s=>({...s,[x.id]:v}))} key={v}>{v.toUpperCase()}</button>)}</div></article>})}</div><TaskStamp done={Boolean(progress.completedTasks["route-activations"])}>Route all eight activation scenarios.</TaskStamp></LessonSection>
 <LessonSection id="saturation" onVisit={progress.markVisited} className={styles.h}><Heading n="08" k="PUSH TO EXTREMES" title="Saturation makes local sensitivity tiny.">Push sigmoid to far negative, center, and far positive. Watch the derivative σ(z)(1−σ(z)). This is one ingredient behind vanishing-gradient problems we will study later.</Heading><div className={styles.satLab}><div className={styles.satGauge}><span>LEFT SATURATION</span><motion.i animate={{left:`${50+satZ*4}%`}}/><span>CENTER</span><span>RIGHT SATURATION</span></div><div><label>z <strong>{satZ.toFixed(1)}</strong><input type="range" min="-10" max="10" step=".5" value={satZ} onChange={e=>setSatZ(Number(e.target.value))}/></label><strong>σ={sat.toFixed(4)}</strong><strong>local derivative={satGrad.toFixed(5)}</strong><button onClick={markSat}>RECORD REGION</button><p>Seen {satSeen.length}/3. Small local derivative means changes upstream can have little effect through this unit.</p></div></div><TaskStamp done={Boolean(progress.completedTasks["inspect-saturation"])}>Inspect both saturated extremes and the sensitive center.</TaskStamp></LessonSection>
 <LessonSection id="explain-activations" onVisit={progress.markVisited} className={styles.i}><Heading n="09" k="TYPE · TEACH" title="Explain scale → shift → nonlinearity.">Use weights, bias and activation as three separate operations, then compare ReLU, sigmoid and softmax.</Heading><div className={styles.explain}><div><span>🎚️ƒ</span><p>“Why can't the network just use weights? Why does it need bias and activation too?”</p></div><section><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="A weight scales... bias shifts... activation introduces... ReLU... sigmoid... softmax... saturation..."/><footer><span>{text.length} chars</span><button onClick={explain}>CHECK EXPLANATION</button></footer>{feedback&&<p className={progress.completedTasks["explain-activations"]?styles.feedbackGood:styles.feedbackHint}>{feedback}</p>}</section></div><TaskStamp done={Boolean(progress.completedTasks["explain-activations"])}>Explain weights, bias and activation functions.</TaskStamp></LessonSection>
 <section className={styles.gate}><div>SECTIONS<strong>{read}/9</strong></div><div>TASKS<strong>{done}/9</strong></div><div className={open?styles.open:""}>QUIZ<strong>{open?"OPEN":"LOCKED"}</strong></div></section><section className={styles.quizSection}><h2>Scale. Shift. Bend.</h2><Quiz progress={progress} open={open}/></section><section className={styles.footer}><div><small>MENTAL MODEL</small><h2>z = weighted sum + bias. a = activation(z).</h2></div><Link href="/lessons/neural-networks">← LESSON 01</Link><div><small>NEXT</small><b>Loss, Gradients & Backprop</b><span>build queue</span></div></section>
 </main>
}
