"use client";

import Link from "next/link";
import { AnimatePresence, motion, Reorder } from "motion/react";
import { ReactNode, useEffect, useMemo, useState } from "react";
import { LessonProgressApi } from "@/components/course/lesson-shell";
import { DepthSwitch, LessonSection, TaskStamp } from "@/components/course/lesson-primitives";
import { trainingInferenceSections } from "@/content/course";
import { ExplanationDepth } from "@/lib/course-progress";
import styles from "./training-vs-inference.module.css";

type Props={progress:LessonProgressApi};
type Floor="training"|"inference";
type DepthCopy=Record<ExplanationDepth,ReactNode>;

const floorCopy:Record<Floor,DepthCopy>={
  training:{
    simple:<>The model practices on examples and <strong>changes its internal numbers</strong> to make fewer mistakes.</>,
    real:<>Training repeatedly computes predictions, measures loss, calculates update directions and changes model parameters over batches/epochs.</>,
    expert:<>Training optimizes parameters against an objective, typically via forward computation, loss evaluation, automatic differentiation and optimizer updates across distributed batches.</>,
  },
  inference:{
    simple:<>The finished model gets a new input and <strong>uses what it learned</strong> without practicing again.</>,
    real:<>Inference runs the trained model forward on new inputs using a chosen checkpoint; weights normally remain unchanged.</>,
    expert:<>Inference executes forward computation with fixed parameters, often using batching, caching, quantization and serving infrastructure while gradients/optimizer state are absent or disabled.</>,
  }
};

const trainingExamples=[
  {id:"a",input:"📩 'FREE MONEY NOW!!!'",label:"SPAM"},{id:"b",input:"📩 'Meeting notes attached'",label:"NOT SPAM"},{id:"c",input:"📩 'YOU WON A PRIZE'",label:"SPAM"},{id:"d",input:"📩 'Invoice for August'",label:"NOT SPAM"},{id:"e",input:"📩 'Claim gift card today'",label:"SPAM"},{id:"f",input:"📩 'Dinner at 8?'",label:"NOT SPAM"},
] as const;
const inferenceRequests=[
  {id:"r1",input:"Urgent: reset your password here",out:"SPAM · 91%"},{id:"r2",input:"Project update for Tuesday",out:"NOT SPAM · 94%"},{id:"r3",input:"You've been selected for a reward",out:"SPAM · 88%"},{id:"r4",input:"Flight itinerary attached",out:"NOT SPAM · 92%"},{id:"r5",input:"Exclusive cash offer",out:"SPAM · 90%"},
] as const;
const lifecycleCorrect=["Collect data","Train / update weights","Evaluate + checkpoint","Deploy frozen version","Run inference","Monitor behavior","Retrain when needed"];

const quizQuestions=[
  {q:"What changes during training?",options:["Only the user's screen","Model parameters/weights are updated to reduce an objective or improve behavior","Nothing","Only the file name"],correct:1,why:"Training is the phase where learning happens: parameters are adjusted based on data/objectives."},
  {q:"What normally happens to weights during inference?",options:["They update after every user request","They stay fixed while the model processes new inputs","They are deleted","They turn into rules"],correct:1,why:"Ordinary inference uses a chosen trained checkpoint without optimizer updates."},
  {q:"What is a checkpoint?",options:["A screenshot","A saved state/version of model parameters (and sometimes training state) at a point in training","A quiz answer","A user prompt"],correct:1,why:"Checkpoints preserve model state so it can be evaluated, resumed, deployed or compared."},
  {q:"Why is training usually more computationally expensive than one inference request?",options:["Training needs forward work plus loss/gradient/update work over lots of examples","Inference has no math","Training only uses CPUs","Because training always uses the internet"],correct:0,why:"Training repeatedly processes large datasets and computes gradients/optimizer updates in addition to forward passes."},
  {q:"Does using a chatbot automatically train its base model on your message in real time?",options:["Yes, every reply permanently changes weights","No — normal serving inference does not update the model weights for each request","Only if the message is long","Only on weekends"],correct:1,why:"Conversation context can affect the current response without changing model parameters. Online learning is a separate explicitly designed process."},
  {q:"What is online learning?",options:["Normal synonym for inference","A deliberate system where model parameters can be updated as new data arrives","Browsing a website","Streaming tokens"],correct:1,why:"Online/continual learning exists, but it is a distinct learning design — not the default behavior of every inference call."},
  {q:"Best lifecycle mental model?",options:["Train once and never monitor","Train → checkpoint/version → deploy → infer many times → monitor → retrain deliberately when needed","Inference → random weight changes → training","Prompt = training"],correct:1,why:"Production ML separates deliberate learning/versioning from serving, then monitors behavior and retrains under controlled processes."},
] as const;

function getDepth(copy:DepthCopy,depth:ExplanationDepth){return copy[depth]}
function Heading({n,kicker,title,children}:{n:string;kicker:string;title:string;children:ReactNode}){return <div className={styles.heading}><span>{n}</span><div><b>{kicker}</b><h2>{title}</h2><p>{children}</p></div></div>}
function Forge({hot=false}:{hot?:boolean}){return <motion.div className={styles.forge} animate={{y:[0,-5,0],rotate:hot?[0,-2,2,0]:[0,1,0]}} transition={{duration:hot?1.2:3,repeat:Infinity}}><div><i/><i/><strong>⚙</strong><motion.span animate={hot?{scale:[1,1.25,.9,1],opacity:[.7,1,.6,.7]}:undefined}/></div><b>FORGE</b></motion.div>}
function Zip({fast=false}:{fast?:boolean}){return <motion.div className={styles.zip} animate={fast?{x:[0,10,-4,0],scale:[1,1.04,1]}:{y:[0,-5,0]}} transition={{duration:fast?.8:3,repeat:Infinity}}><div><i/><i/><strong>→</strong><span/></div><b>ZIP</b></motion.div>}

function Quiz({progress,unlocked}:{progress:LessonProgressApi;unlocked:boolean}){
 const [answers,setAnswers]=useState<Record<number,number>>({});const [submitted,setSubmitted]=useState(false);const count=Object.keys(answers).length;const score=quizQuestions.reduce((n,q,i)=>n+(answers[i]===q.correct?1:0),0);const passed=score>=6;
 if(!unlocked)return <div className={styles.quizLock}><motion.span animate={{y:[0,-6,0],rotate:[-3,3,-3]}} transition={{duration:2,repeat:Infinity}}>🏭🔒</motion.span><h3>Factory exam locked.</h3><p>Train, freeze, serve, break and repair the model lifecycle first.</p></div>;
 const submit=()=>{if(count===quizQuestions.length){setSubmitted(true);progress.saveQuiz(score,passed)}};
 return <div className={styles.quiz}>{quizQuestions.map((q,i)=><div className={styles.question} key={q.q}><h3><span>{i+1}</span>{q.q}</h3><div>{q.options.map((o,j)=><motion.button key={o} whileTap={{scale:.97}} disabled={submitted} onClick={()=>setAnswers(a=>({...a,[i]:j}))} className={`${answers[i]===j?styles.selected:""} ${submitted&&j===q.correct?styles.correct:""} ${submitted&&answers[i]===j&&j!==q.correct?styles.wrong:""}`}><i>{String.fromCharCode(65+j)}</i>{o}</motion.button>)}</div>{submitted&&<p>{q.why}</p>}</div>)}{!submitted?<button className={`${styles.submit} tactile`} disabled={count!==quizQuestions.length} onClick={submit}>CHECK THE FACTORY →</button>:<motion.div className={`${styles.result} ${passed?styles.pass:styles.fail}`} initial={{scale:.9}} animate={{scale:1}}><strong>{score}/7</strong><div><h3>{passed?"Factory mental model mastered.":"One more maintenance pass."}</h3><p>{passed?"You can now separate learning-time weight updates from serving-time forward passes.":"Pass is 6/7. Read the explanations and repair the weak concepts."}</p></div>{!passed&&<button onClick={()=>{setAnswers({});setSubmitted(false)}}>TRY AGAIN</button>}</motion.div>}</div>
}

export function TrainingVsInferenceLesson({progress}:Props){
 const [floors,setFloors]=useState<Floor[]>([]);const [batch,setBatch]=useState(0);const [trainPhase,setTrainPhase]=useState(0);const [weight,setWeight]=useState(18);const [weightTouched,setWeightTouched]=useState(false);const [optSteps,setOptSteps]=useState(0);
 const [checkpoint,setCheckpoint]=useState(false);const [checkpointWeight,setCheckpointWeight]=useState(0);const [served,setServed]=useState<string[]>([]);const [accidentalOn,setAccidentalOn]=useState(false);const [accidentalRuns,setAccidentalRuns]=useState(0);const [drift,setDrift]=useState(0);const [restored,setRestored]=useState(false);
 const [trainGpus,setTrainGpus]=useState(4);const [batchSize,setBatchSize]=useState(64);const [replicas,setReplicas]=useState(2);const [computeTouched,setComputeTouched]=useState<string[]>([]);const [lifecycle,setLifecycle]=useState(["Run inference","Collect data","Train / update weights","Monitor behavior","Evaluate + checkpoint","Deploy frozen version","Retrain when needed"]);const [explanation,setExplanation]=useState("");const [feedback,setFeedback]=useState("");
 const loss=Math.max(.08,1.4*Math.exp(-batch*.31));const trainingWeight=Math.min(82,18+batch*8);const hillLoss=Math.round((Math.pow(weight-68,2)/130+0.08)*100)/100;const lifecycleOk=lifecycle.join("|")===lifecycleCorrect.join("|");
 const trainCompute=Math.round(trainGpus*batchSize*1.7);const trainTime=Math.max(8,Math.round(110/(trainGpus*.65+1)));const inferLatency=Math.max(18,Math.round(78/Math.sqrt(replicas)));const throughput=Math.round(replicas*42);
 const touchCompute=(k:string)=>setComputeTouched(s=>s.includes(k)?s:[...s,k]);const inspectFloor=(f:Floor)=>setFloors(s=>s.includes(f)?s:[...s,f]);
 useEffect(()=>{if(floors.length===2)progress.completeTask("inspect-factory-floors")},[floors.length,progress]);useEffect(()=>{if(batch>=6&&trainPhase>=4)progress.completeTask("run-training-line")},[batch,trainPhase,progress]);useEffect(()=>{if(weightTouched&&optSteps>=4&&hillLoss<1)progress.completeTask("optimize-weight")},[weightTouched,optSteps,hillLoss,progress]);useEffect(()=>{if(checkpoint)progress.completeTask("freeze-checkpoint")},[checkpoint,progress]);useEffect(()=>{if(served.length===5&&checkpoint)progress.completeTask("serve-inference")},[served.length,checkpoint,progress]);useEffect(()=>{if(accidentalRuns>=2&&restored&&!accidentalOn)progress.completeTask("stop-accidental-learning")},[accidentalRuns,restored,accidentalOn,progress]);useEffect(()=>{if(computeTouched.length===3)progress.completeTask("compare-compute")},[computeTouched.length,progress]);useEffect(()=>{if(lifecycleOk)progress.completeTask("build-lifecycle")},[lifecycleOk,progress]);
 const required=trainingInferenceSections.map(s=>s.taskId);const done=required.filter(id=>progress.completedTasks[id]).length;const read=trainingInferenceSections.filter(s=>progress.visitedSections.has(s.id)).length;const quizUnlocked=done===9&&read===9;
 const runBatch=()=>{setBatch(b=>Math.min(10,b+1));setTrainPhase(4)};const optimizerStep=()=>{setWeightTouched(true);setOptSteps(s=>s+1);setWeight(w=>Math.round((w+(68-w)*.48)*10)/10)};const freeze=()=>{if(batch>=6){setCheckpoint(true);setCheckpointWeight(trainingWeight)}};
 const serve=(id:string)=>{if(!checkpoint)return;setServed(s=>s.includes(id)?s:[...s,id])};const accidentalServe=()=>{if(!accidentalOn)return;setAccidentalRuns(r=>r+1);setDrift(d=>d+4.5);setRestored(false)};const restore=()=>{if(checkpoint){setDrift(0);setAccidentalOn(false);setRestored(true)}};
 const submitExplain=()=>{const t=explanation.toLowerCase();const hits=["train","weight","parameter","loss","gradient","checkpoint","inference","frozen","forward","update"].filter(k=>t.includes(k));if(explanation.trim().length<95){setFeedback("Use at least three sentences: explain what changes in training, what stays fixed in inference, and what a checkpoint/deployment does.");return}if(hits.length<6){setFeedback("Add mechanism words such as weights/parameters, loss/gradient/update, checkpoint, frozen and inference/forward pass.");return}setFeedback("Good. You separated learning from serving and explained the role of a frozen/versioned checkpoint.");progress.completeTask("explain-train-infer")};

 return <main className={`${styles.lesson} lesson-main`}>
  <section className={styles.hero}><div><span className={styles.tag}>MODULE 01 · LESSON 06</span><h1>TRAIN<br/><em>then</em><br/>INFER.</h1><p>The same model lives through two very different jobs: first <strong>change the weights</strong> using data; later <strong>use those weights</strong> to answer new requests.</p><DepthSwitch value={progress.depth} onChange={progress.setDepth}/></div><div className={styles.factoryHero}><div className={styles.topFloor}><Forge hot/><span>TRAINING FLOOR</span><b>weights change</b></div><div className={styles.elevator}>↓ CHECKPOINT ↓</div><div className={styles.bottomFloor}><Zip fast/><span>INFERENCE FLOOR</span><b>weights frozen</b></div></div></section>

  <LessonSection id="two-floors" onVisit={progress.markVisited} className={styles.sceneA}><Heading n="01" kicker="CLICK · INSPECT" title="Open both floors of the AI factory.">The most important difference is simple: <strong>training changes the model; ordinary inference uses the model.</strong></Heading><div className={styles.floorGrid}>{(["training","inference"] as Floor[]).map(f=><motion.button key={f} onClick={()=>inspectFloor(f)} className={floors.includes(f)?styles.floorSeen:""} whileHover={{y:-5}}>{f==="training"?<Forge hot={floors.includes(f)}/>:<Zip fast={floors.includes(f)}/>}<h3>{f.toUpperCase()}</h3><p>{getDepth(floorCopy[f],progress.depth)}</p><div className={styles.floorFacts}>{f==="training"?<><span>DATASET</span><span>LOSS</span><span>GRADIENTS</span><span>OPTIMIZER</span><strong>WEIGHTS UPDATE</strong></>:<><span>NEW INPUT</span><span>FORWARD PASS</span><span>OUTPUT</span><span>SERVING</span><strong>WEIGHTS STAY FIXED</strong></>}</div><small>{floors.includes(f)?"INSPECTED ✓":"CLICK TO OPEN"}</small></motion.button>)}</div><TaskStamp done={Boolean(progress.completedTasks["inspect-factory-floors"])}>Inspect both factory floors.</TaskStamp></LessonSection>

  <LessonSection id="training-line" onVisit={progress.markVisited} className={styles.sceneB}><Heading n="02" kicker="CLICK · LOOP" title="Training repeats a correction loop.">Push batches through <strong>Forward → Loss → Gradient → Update</strong>. Watch loss fall and the toy weight move.</Heading><div className={styles.trainingLab}><div className={styles.exampleBelt}>{trainingExamples.map((e,i)=><motion.div key={e.id} className={i<batch%7?styles.exampleActive:""} animate={i<batch%7?{y:[0,-4,0]}:undefined}><span>{e.input}</span><b>{e.label}</b></motion.div>)}</div><div className={styles.trainMachine}><div className={styles.phaseRail}>{["FORWARD","LOSS","GRADIENT","UPDATE"].map((p,i)=><button key={p} onClick={()=>setTrainPhase(Math.max(trainPhase,i+1))} className={trainPhase>=i+1?styles.phaseDone:""}><span>{i+1}</span>{p}</button>)}</div><div className={styles.metrics}><div><span>BATCHES</span><strong>{batch}</strong></div><div><span>LOSS</span><strong>{loss.toFixed(3)}</strong></div><div><span>TOY WEIGHT</span><strong>{trainingWeight}</strong></div></div><button className="tactile" onClick={runBatch}>⚙ RUN NEXT TRAINING BATCH</button></div></div><div className={styles.loopNote}><span>ONE BATCH</span><b>input → prediction → compare with target → calculate update → change parameters</b></div><TaskStamp done={Boolean(progress.completedTasks["run-training-line"])}>Open all four phases and run at least six batches.</TaskStamp></LessonSection>

  <LessonSection id="optimizer-hill" onVisit={progress.markVisited} className={styles.sceneC}><Heading n="03" kicker="SLIDE · STEP" title="Optimization is trying to move toward lower loss.">This one-dimensional hill is a toy. Real models optimize enormous parameter spaces, but the local idea is useful.</Heading><div className={styles.hillLab}><div className={styles.hill}><svg viewBox="0 0 100 60" preserveAspectRatio="none"><path d="M0 8 C22 48 42 57 68 58 C84 57 92 41 100 11" fill="none" stroke="currentColor" strokeWidth="2.5"/></svg><motion.div className={styles.ball} animate={{left:`${weight}%`,bottom:`${Math.min(80,10+hillLoss*4)}%`}} transition={{type:"spring",stiffness:180,damping:22}}>W</motion.div><span className={styles.optimum}>LOW LOSS<br/>OPTIMUM</span></div><div className={styles.hillControls}><label>MANUAL WEIGHT <strong>{weight.toFixed(1)}</strong><input type="range" min="5" max="95" step=".5" value={weight} onChange={e=>{setWeightTouched(true);setWeight(Number(e.target.value))}}/></label><div className={styles.lossCard}><span>LOSS</span><motion.strong key={hillLoss} initial={{scale:.8}} animate={{scale:1}}>{hillLoss.toFixed(2)}</motion.strong></div><button className="tactile" onClick={optimizerStep}>↓ OPTIMIZER STEP</button><p>{optSteps} optimizer steps · target ≈ weight 68</p></div></div><TaskStamp done={Boolean(progress.completedTasks["optimize-weight"])}>Move the weight yourself, then take at least four optimizer steps until loss is low.</TaskStamp></LessonSection>

  <LessonSection id="checkpoint" onVisit={progress.markVisited} className={styles.sceneD}><Heading n="04" kicker="FREEZE · VERSION" title="Save what training learned.">A checkpoint gives you a reproducible model state you can evaluate, compare, resume or deploy.</Heading><div className={styles.freezeLab}><div className={styles.liveModel}><Forge hot={batch>=6}/><span>LIVE TRAINING MODEL</span><strong>weight {trainingWeight}</strong><i className={batch>=6?styles.hot:""}>CHANGING</i></div><motion.div className={styles.freezeArrow} animate={{x:[0,9,0]}} transition={{duration:1.6,repeat:Infinity}}>→</motion.div><div className={`${styles.checkpointBox} ${checkpoint?styles.frozen:""}`}><span>MODEL CHECKPOINT</span>{checkpoint?<><b>v1.0</b><strong>weight {checkpointWeight}</strong><i>❄ FROZEN SNAPSHOT</i></>:<><b>?</b><strong>no saved state</strong></>}<button disabled={batch<6||checkpoint} onClick={freeze} className="tactile">{checkpoint?"CHECKPOINT SAVED ✓":"FREEZE MODEL v1.0"}</button></div></div><p className={styles.checkpointNote}>A deployment may use a checkpoint of weights while training continues elsewhere on a newer candidate version.</p><TaskStamp done={Boolean(progress.completedTasks["freeze-checkpoint"])}>Train enough batches, then freeze checkpoint v1.0.</TaskStamp></LessonSection>

  <LessonSection id="inference-line" onVisit={progress.markVisited} className={styles.sceneE}><Heading n="05" kicker="SERVE · CLICK" title="Now use the frozen model many times.">New requests flow through the same checkpoint. Notice: <strong>outputs change with inputs, but the checkpoint weight does not.</strong></Heading><div className={styles.inferLab}><div className={styles.server}><Zip fast={checkpoint}/><span>SERVING</span><strong>MODEL v1.0</strong><div>frozen weight: <b>{checkpoint?checkpointWeight:"—"}</b></div><small>{checkpoint?"READY":"FREEZE A CHECKPOINT FIRST"}</small></div><div className={styles.requestStack}>{inferenceRequests.map(r=><button disabled={!checkpoint} key={r.id} onClick={()=>serve(r.id)} className={served.includes(r.id)?styles.served:""}><span>{r.input}</span><strong>{served.includes(r.id)?r.out:"CLICK TO SERVE →"}</strong></button>)}</div></div><div className={styles.weightInvariant}><span>BEFORE REQUESTS</span><strong>{checkpoint?checkpointWeight:"—"}</strong><b>=</b><span>AFTER {served.length} REQUESTS</span><strong>{checkpoint?checkpointWeight:"—"}</strong></div><TaskStamp done={Boolean(progress.completedTasks["serve-inference"])}>Serve all five new inputs through the frozen checkpoint.</TaskStamp></LessonSection>

  <LessonSection id="accidental-learning" onVisit={progress.markVisited} className={styles.sceneF}><Heading n="06" kicker="BREAK · RESTORE" title="Inference context is not the same as weight learning.">Turn on a dangerous teaching toggle, mutate the serving model, then restore the checkpoint. This makes the separation visceral.</Heading><div className={styles.dangerLab}><div className={styles.toggleBox}><span>LIVE SERVING CONFIG</span><button onClick={()=>{setAccidentalOn(v=>!v);setRestored(false)}} className={accidentalOn?styles.toggleOn:""}><i/><b>UPDATE WEIGHTS AFTER REQUEST</b><strong>{accidentalOn?"ON":"OFF"}</strong></button><p>{accidentalOn?"You have deliberately enabled an online-learning-like update path. This is NOT ordinary inference.":"Normal serving: use context + frozen checkpoint; no optimizer update per request."}</p></div><div className={styles.driftBox}><span>SERVING WEIGHT</span><strong>{checkpoint?Number(checkpointWeight+drift).toFixed(1):"—"}</strong><i><b style={{width:`${Math.min(100,20+drift*7)}%`}}/></i><button disabled={!checkpoint||!accidentalOn} onClick={accidentalServe}>SEND REQUEST + UPDATE</button><small>{accidentalRuns} accidental updates</small></div><div className={styles.restoreBox}><span>KNOWN GOOD</span><strong>v1.0 · {checkpoint?checkpointWeight:"—"}</strong><button disabled={!checkpoint||accidentalRuns<2} onClick={restore} className="tactile">↺ RESTORE CHECKPOINT</button><p>{restored?"Restored. Serving weight matches the versioned checkpoint again.":"Cause at least two accidental updates, then recover."}</p></div></div><TaskStamp done={Boolean(progress.completedTasks["stop-accidental-learning"])}>Enable updates, mutate twice, turn learning off by restoring the checkpoint.</TaskStamp></LessonSection>

  <LessonSection id="compute-console" onVisit={progress.markVisited} className={styles.sceneG}><Heading n="07" kicker="SLIDE · COMPARE" title="Training and inference optimize different economics.">Training often spends huge compute to create/update a model. Serving optimizes latency, throughput and cost across many requests.</Heading><div className={styles.computeLab}><div className={styles.computeControls}><label>TRAINING GPUs <strong>{trainGpus}</strong><input type="range" min="1" max="16" value={trainGpus} onChange={e=>{setTrainGpus(Number(e.target.value));touchCompute("gpus")}}/></label><label>TRAIN BATCH SIZE <strong>{batchSize}</strong><input type="range" min="16" max="256" step="16" value={batchSize} onChange={e=>{setBatchSize(Number(e.target.value));touchCompute("batch")}}/></label><label>INFERENCE REPLICAS <strong>{replicas}</strong><input type="range" min="1" max="8" value={replicas} onChange={e=>{setReplicas(Number(e.target.value));touchCompute("replicas")}}/></label></div><div className={styles.computeDashboard}><div className={styles.trainDash}><Forge/><span>TRAINING</span><strong>{trainCompute}</strong><small>relative compute units</small><b>~{trainTime} min toy epoch</b></div><div className={styles.inferDash}><Zip/><span>INFERENCE</span><strong>{inferLatency} ms</strong><small>toy request latency</small><b>{throughput} req/s capacity</b></div></div></div><p className={styles.toyNote}>These numbers are intentionally illustrative, not hardware benchmarks. The lesson is the optimization objective: training throughput/optimization versus serving latency/throughput/cost.</p><TaskStamp done={Boolean(progress.completedTasks["compare-compute"])}>Move all three compute/serving controls.</TaskStamp></LessonSection>

  <LessonSection id="lifecycle" onVisit={progress.markVisited} className={styles.sceneH}><Heading n="08" kicker="DRAG · ORDER" title="Build the deliberate model lifecycle.">Serving is not the end. Monitor the deployed version and retrain through a controlled loop when new evidence justifies it.</Heading><div className={styles.lifecycleLab}><Reorder.Group axis="y" values={lifecycle} onReorder={setLifecycle}>{lifecycle.map((item,i)=><Reorder.Item key={item} value={item} className={`${styles.lifeItem} ${lifecycleOk?styles.lifeCorrect:""}`} whileDrag={{scale:1.035,rotate:1}}><span>{i+1}</span><strong>{item}</strong><small>drag</small></Reorder.Item>)}</Reorder.Group><div className={styles.lifePanel}>{lifecycleOk?<><strong>✓ CONTROLLED LIFECYCLE</strong><p>Collect → train → evaluate/checkpoint → deploy → infer → monitor → deliberately retrain.</p></>:<><strong>Put learning before serving.</strong><p>And put monitoring after deployment so retraining is a deliberate response, not an accidental side effect of every request.</p></>}</div></div><TaskStamp done={Boolean(progress.completedTasks["build-lifecycle"])}>Drag the lifecycle into the correct controlled order.</TaskStamp></LessonSection>

  <LessonSection id="explain-train-infer" onVisit={progress.markVisited} className={styles.sceneI}><Heading n="09" kicker="TYPE · TEACH" title="Explain why chatting is not automatically training.">Explain training, checkpointing and inference to someone who thinks every prompt permanently rewrites the model.</Heading><div className={styles.explainLab}><div className={styles.listener}><span>💬</span><p>“I told the chatbot my name. Did that retrain the model weights?”</p></div><div><textarea value={explanation} onChange={e=>setExplanation(e.target.value)} placeholder="Training is when... A checkpoint is... During normal inference... Conversation context can..."/><footer><span>{explanation.length} chars</span><button className="tactile" onClick={submitExplain}>CHECK EXPLANATION</button></footer>{feedback&&<motion.p className={progress.completedTasks["explain-train-infer"]?styles.feedbackGood:styles.feedbackHint} initial={{opacity:0,y:6}} animate={{opacity:1,y:0}}>{feedback}</motion.p>}</div></div><TaskStamp done={Boolean(progress.completedTasks["explain-train-infer"])}>Explain learning-time updates versus serving-time context/frozen weights.</TaskStamp></LessonSection>

  <section className={styles.gate}><div><span>SECTIONS</span><strong>{read}/9</strong></div><div><span>TASKS</span><strong>{done}/9</strong></div><div className={quizUnlocked?styles.gateOpen:""}><span>QUIZ</span><strong>{quizUnlocked?"OPEN":"LOCKED"}</strong></div></section>
  <section className={styles.quizSection}><header><span>LESSON 06 QUIZ</span><h2>Learning or serving?</h2><p>Pass 6/7. You should know exactly when weights change.</p></header><Quiz progress={progress} unlocked={quizUnlocked}/></section>
  <section className={styles.footer}><div><span>MENTAL MODEL</span><h2>Training changes weights. Inference uses weights.</h2><p>Context can change what a model sees for one request without changing the checkpoint itself.</p></div><Link href="/lessons/symbolic-vs-neural">← LESSON 05</Link><div><small>NEXT</small><strong>Models / Algorithms / Data</strong><span>build queue</span></div></section>
 </main>
}
