"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { AiMascot } from "@/components/mascots/ai-mascot";
import { LessonProgressApi } from "@/components/course/lesson-shell";
import { LessonSection, TaskStamp } from "@/components/course/lesson-primitives";
import styles from "./image-generation-lab.module.css";

type Props={progress:LessonProgressApi};
const latentCases=[
["VAE encoder compresses an image into a lower-dimensional latent representation","encode"],["Diffusion denoiser operates in latent space in latent-diffusion systems","latent-denoise"],["VAE decoder maps final latent back toward image pixels","decode"],["Latent diffusion means the model stores every training image in a hidden folder","false"],
] as const;
const denoiserCases=[
["Convolutional U-Net-style denoisers were central to many influential diffusion systems","unet"],["Diffusion Transformer / DiT-style models use transformer blocks as denoising backbone","dit"],["Both names describe the exact same layer implementation","false"],
] as const;
const conditioningCases=[
["'a yellow robot under moonlight'","text"],["Negative/avoid concepts in supported systems","guidance"],["Reference structure such as edge/depth/pose","structure"],["Random seed","sampling"],
] as const;
const clipCases=[
["Text 'golden retriever' near matching dog image embedding","aligned"],["Image of airplane near 'fresh sushi' text embedding","not-aligned"],["Joint representation can help connect language and visual concepts","aligned"],
] as const;
const controlCases=[
["Keep pose while changing clothing/style","pose"],["Preserve edges/layout while regenerating appearance","edge"],["Use depth map to preserve scene geometry","depth"],["ControlNet-style conditioning is simply another name for the final VAE decoder","false"],
] as const;
const editingCases=[
["Replace damaged area inside an existing image","inpaint"],["Extend canvas beyond original borders","outpaint"],["Regenerate entire image from pure noise only","generate"],["Mask tells the system which region may change","mask"],
] as const;
const img2imgCases=[
["Use an input image as starting visual condition and transform it","image-to-image"],["Higher transformation strength usually permits larger deviation from input","strength"],["Style transfer changes appearance while attempting to preserve selected content/structure","style"],["Image-to-image always copies pixels exactly","false"],
] as const;
const quiz=[
["Diffusion image generation is usefully pictured as…",["Starting from noise and iteratively denoising toward a sample conditioned by inputs","Searching a database for the closest saved image","Running OCR only","A single deterministic paint command"],0],
["In latent diffusion, denoising can happen…",["In a compressed learned latent representation instead of full pixel space","Only in English text","Only in model weights","Only in browser memory"],0],
["A VAE decoder commonly…",["Maps latent representation back toward image/pixel space","Chooses an API tool","Stores cookies","Builds a Git diff"],0],
["U-Net and DiT refer to…",["Different denoising-backbone architectural families used in diffusion systems","Exactly the same implementation","Only tokenizers","Only vector databases"],0],
["Text conditioning influences…",["What visual content/style the denoising process is encouraged to produce","Only image file size","Only browser state","Only training split"],0],
["ControlNet-style conditioning is useful for…",["Adding spatial/structural control such as pose, edges or depth","Changing API auth","Tokenizing captions","Creating SQL indexes"],0],
["Inpainting typically changes…",["A masked region inside an existing image","Only the canvas outside the image","Only audio","Only metadata"],0],
["Outpainting typically…",["Extends/generates beyond existing image boundaries","Removes all context","Runs ASR","Fine-tunes model weights"],0],
["Image-to-image transformation strength affects…",["How much output can deviate from the input visual condition","Only the file name","Only user authentication","Only token IDs"],0],
["A diffusion system's exact architecture can vary widely across model families.",["True","False"],0],
] as const;

export function ImageGenerationLabLesson({progress}:Props){
 const [denoise,setDenoise]=useState(0),[steps,setSteps]=useState(20),[seed,setSeed]=useState(7),[latent,setLatent]=useState<Record<number,string>>({}),[denoiser,setDenoiser]=useState<Record<number,string>>({}),[conditioning,setConditioning]=useState<Record<number,string>>({}),[clip,setClip]=useState<Record<number,string>>({}),[control,setControl]=useState<Record<number,string>>({}),[editing,setEditing]=useState<Record<number,string>>({}),[img2img,setImg2img]=useState<Record<number,string>>({}),[transformStrength,setTransformStrength]=useState(35),[explain,setExplain]=useState(""),[feedback,setFeedback]=useState(""),[answers,setAnswers]=useState<Record<number,number>>({});
 const tasks=["img-diffusion","img-steps","img-latent","img-denoiser","img-conditioning","img-clip","img-control","img-editing","img-img2img","img-explain"],sections=["diffusion","steps","latent","denoiser","conditioning","clip","control","editing","img2img","explain"];
 const done=tasks.filter(t=>progress.completedTasks[t]).length,read=sections.filter(s=>progress.visitedSections.has(s)).length,unlocked=done===10&&read===10;
 const quizScore=quiz.reduce((sum,q,i)=>sum+(answers[i]===q[2]?1:0),0),quizDone=Object.keys(answers).length===quiz.length;
 const solve=(current:Record<number,string>,setter:(next:Record<number,string>)=>void,cases:readonly (readonly [string,string])[],i:number,choice:string,task:string)=>{const next={...current,[i]:choice};setter(next);if(cases.every((x,j)=>next[j]===x[1]))progress.completeTask(task)};
 const cells=useMemo(()=>Array.from({length:100},(_,i)=>{const x=i%10,y=Math.floor(i/10);const body=x>2&&x<7&&y>2&&y<8;const eye=(x===4||x===6)&&y===4;const target=eye?18:body?55+y*2:215;const noise=((i*37+seed*53)%255);const t=denoise/100;return Math.round(noise*(1-t)+target*t)}),[denoise,seed]);
 const stepQuality=Math.min(100,Math.round(45+Math.log2(Math.max(1,steps))*11));
 const stepCost=Math.round(steps*2.2);
 const submit=()=>{const t=explain.toLowerCase();const hits=["noise","denois","latent","vae","unet","dit","condition","control","inpaint","outpaint","image-to-image"].filter(w=>t.includes(w)).length;if(explain.length<150||hits<8){setFeedback("Go deeper: explain noise→denoise, sampling steps, latent/VAE, denoiser backbone, text/structural conditioning and image editing modes.");return;}setFeedback("Strong. You described image generation as an iterative conditioned generative process, not a hidden image lookup table.");progress.completeTask("img-explain")};
 return <main className={styles.root}>
  <section className={styles.hero}><div><span className={styles.eyebrow}>MODULE 18 · IMAGE GENERATION LAB</span><h1>Start with noise. Sculpt probability into pixels.</h1><p>Use a simplified diffusion mental model to understand denoising, latent space, VAE encode/decode, denoiser architectures and conditioning. Then edit existing images with masks, structure and transformation strength.</p><TaskStamp done={done===10}>{done}/10 image-generation missions complete</TaskStamp></div><div className={styles.heroVisual}><AiMascot variant="star" accent="#ff9bc7" size={96} mood={denoise>80?"excited":"thinking"} label="DIFFUSE"/><div className={styles.noiseGrid}>{cells.map((value,i)=><i key={i} style={{background:`rgb(${value},${Math.max(30,value-20)},${Math.min(255,value+30)})`}}/>)}</div></div></section>

  <LessonSection id="diffusion" onVisit={progress.markVisited} className={styles.scene}><h2>1. Pull structure out of noise.</h2><label className={styles.slider}>Denoising progress <b>{denoise}%</b><input type="range" min="0" max="100" value={denoise} onChange={e=>{const value=+e.target.value;setDenoise(value);if(value>=85)progress.completeTask("img-diffusion")}}/></label><div className={styles.noiseStage}><div className={styles.noiseGrid}>{cells.map((value,i)=><i key={i} style={{background:`rgb(${value},${Math.max(30,value-20)},${Math.min(255,value+30)})`}}/>)}</div><div><b>0%</b><span>mostly noise</span><b>→ 100%</b><span>toy structure emerges</span></div></div><p>Real diffusion samplers do much richer learned denoising than this toy interpolation. The useful intuition is iterative refinement from a noisy state under a learned denoising process and conditioning.</p></LessonSection>

  <LessonSection id="steps" onVisit={progress.markVisited} className={styles.scene}><h2>2. Sampling steps trade compute/latency against approximation quality.</h2><div className={styles.twoSliders}><label>Sampling steps <b>{steps}</b><input type="range" min="4" max="80" value={steps} onChange={e=>{setSteps(+e.target.value);progress.completeTask("img-steps")}}/></label><label>Seed <b>{seed}</b><input type="range" min="1" max="30" value={seed} onChange={e=>setSeed(+e.target.value)}/></label></div><div className={styles.metrics}><div><span>toy quality proxy</span><b>{stepQuality}%</b></div><div><span>toy compute units</span><b>{stepCost}</b></div><div><span>seed</span><b>{seed}</b></div></div><p>More steps do not improve every sampler/model indefinitely. Modern samplers can reach strong outputs in fewer steps; the exact curve is model/scheduler dependent.</p></LessonSection>

  <LessonSection id="latent" onVisit={progress.markVisited} className={styles.scene}><h2>3. Latent diffusion compresses the workspace.</h2><div className={styles.latentFlow}><span>IMAGE 512×512×3</span><b>VAE encoder →</b><span>LATENT h×w×c</span><b>diffusion/denoise →</b><span>LATENT</span><b>VAE decoder →</b><span>IMAGE</span></div>{latentCases.map((c,i)=><div className={styles.card} key={c[0]}><p>{c[0]}</p>{["encode","latent-denoise","decode","false"].map(choice=><button key={choice} className={`${styles.button} ${latent[i]===choice?(choice===c[1]?styles.good:styles.bad):""}`} onClick={()=>solve(latent,setLatent,latentCases,i,choice,"img-latent")}>{choice}</button>)}</div>)}</LessonSection>

  <LessonSection id="denoiser" onVisit={progress.markVisited} className={styles.scene}><h2>4. The denoiser backbone can change across generations of systems.</h2>{denoiserCases.map((c,i)=><div className={styles.card} key={c[0]}><p>{c[0]}</p>{["unet","dit","false"].map(choice=><button key={choice} className={`${styles.button} ${denoiser[i]===choice?(choice===c[1]?styles.good:styles.bad):""}`} onClick={()=>solve(denoiser,setDenoiser,denoiserCases,i,choice,"img-denoiser")}>{choice}</button>)}</div>)}<div className={styles.archCompare}><div><b>U-NET FAMILY</b><span>multi-scale convolutional encoder/decoder + skip connections; historically central to many diffusion systems</span></div><div><b>DiT FAMILY</b><span>transformer-based denoising backbone operating over latent/image tokens</span></div></div></LessonSection>

  <LessonSection id="conditioning" onVisit={progress.markVisited} className={styles.scene}><h2>5. Conditioning tells the generative process what to aim toward.</h2>{conditioningCases.map((c,i)=><div className={styles.card} key={c[0]}><p>{c[0]}</p>{["text","guidance","structure","sampling"].map(choice=><button key={choice} className={`${styles.button} ${conditioning[i]===choice?(choice===c[1]?styles.good:styles.bad):""}`} onClick={()=>solve(conditioning,setConditioning,conditioningCases,i,choice,"img-conditioning")}>{choice}</button>)}</div>)}<div className={styles.promptBox}><code>PROMPT: “small white robot, glossy toy plastic, studio lighting”</code><span>text encoder → conditioning representations → denoiser</span></div></LessonSection>

  <LessonSection id="clip" onVisit={progress.markVisited} className={styles.scene}><h2>6. Joint text-image representations help connect words with visual concepts.</h2>{clipCases.map((c,i)=><div className={styles.card} key={c[0]}><p>{c[0]}</p>{["aligned","not-aligned"].map(choice=><button key={choice} className={`${styles.button} ${clip[i]===choice?(choice===c[1]?styles.good:styles.bad):""}`} onClick={()=>solve(clip,setClip,clipCases,i,choice,"img-clip")}>{choice}</button>)}</div>)}<p>CLIP-style contrastive image/text alignment is one important historical approach. Modern generation systems may use different text encoders and conditioning mechanisms; do not reduce all image generation to “CLIP.”</p></LessonSection>

  <LessonSection id="control" onVisit={progress.markVisited} className={styles.scene}><h2>7. Add structure constraints without hand-drawing every output pixel.</h2><div className={styles.controlDemo}><div className={styles.pose}>○<i/><b>╱│╲</b><b>╱ ╲</b></div><span>POSE / EDGE / DEPTH CONDITION</span><b>+</b><span>TEXT PROMPT</span><b>→</b><AiMascot variant="bot" accent="#9ae6b6" size={78} mood="happy" label="CONTROL"/></div>{controlCases.map((c,i)=><div className={styles.card} key={c[0]}><p>{c[0]}</p>{["pose","edge","depth","false"].map(choice=><button key={choice} className={`${styles.button} ${control[i]===choice?(choice===c[1]?styles.good:styles.bad):""}`} onClick={()=>solve(control,setControl,controlCases,i,choice,"img-control")}>{choice}</button>)}</div>)}<p>“ControlNet” is a specific family/technique name; the durable concept is additional spatial/structural conditioning that guides generation while preserving a learned generative model.</p></LessonSection>

  <LessonSection id="editing" onVisit={progress.markVisited} className={styles.scene}><h2>8. Inpaint inside. Outpaint outside.</h2><div className={styles.canvasDemo}><div className={styles.original}><span>ORIGINAL</span><i className={styles.mask}/></div><div className={styles.expanded}><span>OUTPAINT AREA</span><div>original canvas</div></div></div>{editingCases.map((c,i)=><div className={styles.card} key={c[0]}><p>{c[0]}</p>{["inpaint","outpaint","generate","mask"].map(choice=><button key={choice} className={`${styles.button} ${editing[i]===choice?(choice===c[1]?styles.good:styles.bad):""}`} onClick={()=>solve(editing,setEditing,editingCases,i,choice,"img-editing")}>{choice}</button>)}</div>)}</LessonSection>

  <LessonSection id="img2img" onVisit={progress.markVisited} className={styles.scene}><h2>9. Image-to-image starts from a visual condition, not necessarily pure noise.</h2><label className={styles.slider}>Transformation strength <b>{transformStrength}%</b><input type="range" min="5" max="95" value={transformStrength} onChange={e=>{setTransformStrength(+e.target.value);progress.completeTask("img-img2img")}}/></label><div className={styles.transform}><div style={{filter:`saturate(${1+transformStrength/100}) contrast(${1+transformStrength/250})`}}>🏠 🌳 ☁️</div><b>→</b><div style={{transform:`scale(${1+transformStrength/500}) rotate(${(transformStrength-50)/50}deg)`}}>🏠 🌳 ✨</div></div>{img2imgCases.map((c,i)=><div className={styles.card} key={c[0]}><p>{c[0]}</p>{["image-to-image","strength","style","false"].map(choice=><button key={choice} className={`${styles.button} ${img2img[i]===choice?(choice===c[1]?styles.good:styles.bad):""}`} onClick={()=>solve(img2img,setImg2img,img2imgCases,i,choice,"img-img2img")}>{choice}</button>)}</div>)}</LessonSection>

  <LessonSection id="explain" onVisit={progress.markVisited} className={styles.scene}><h2>10. Explain image generation without saying “the model imagines it.”</h2><textarea className={styles.textarea} value={explain} onChange={e=>setExplain(e.target.value)} placeholder="Explain noise/denoising, steps, latent/VAE, U-Net vs DiT, text/structural conditioning, inpaint/outpaint and image-to-image."/><button className={styles.primary} onClick={submit}>Check explanation</button>{feedback&&<p className={styles.feedback}>{feedback}</p>}</LessonSection>

  <section className={styles.quiz}><h2>Image Generation Lab quiz</h2>{!unlocked?<div className={styles.locked}>🔒 Complete all 10 rooms. {done}/10 tasks · {read}/10 sections.</div>:<>{quiz.map((q,i)=><div className={styles.question} key={q[0]}><strong>{i+1}. {q[0]}</strong>{q[1].map((option,oi)=><button key={option} className={answers[i]===oi?styles.selected:""} onClick={()=>setAnswers(a=>({...a,[i]:oi}))}>{option}</button>)}{answers[i]!==undefined&&<small>{answers[i]===q[2]?"✓ Correct":`Correct: ${q[1][q[2]]}`}</small>}</div>)}<button className={styles.primary} disabled={!quizDone} onClick={()=>progress.saveQuiz(quizScore,quizScore>=9)}>Submit · {quizScore}/10</button>{quizDone&&<p className={styles.feedback}>{quizScore>=9?"★ IMAGE GENERATION MENTAL MODEL MASTERED":"Pass is 9/10. Revisit latent diffusion and conditioning."}</p>}</>}</section>
  <div className={styles.footer}><Link href="/lessons/multimodal-room">← Multimodal Room</Link><Link href="/lessons/voice-agent-lab">Voice Agents →</Link></div>
 </main>
}
